import {open,E} from './browser.mjs';import fs from 'node:fs';import assert from 'node:assert/strict';
const t=await open('flow',375,667,true),events=[],stamp=Date.now();const mark=async n=>{const s=await t.capture('flow-'+n);events.push({name:n,wall_seconds:(Date.now()-stamp)/1000,screen:s.screen,save:s.save,build:s.build});await t.p.waitForTimeout(850);return s;};
try{
 await t.goto('home');await mark('01-home');await t.tap('chapters');await mark('02-map');await t.tap('map-detail');await mark('03-map-detail');await t.tap('map-depart');await mark('04-prepare');await t.tap('tab-weapons');await t.swipe(0,-270);await mark('05-weapons-scroll');
 await t.tap('back');await t.tap('collection');await mark('06-collection');await t.tap('person-hua');await mark('07-person');await t.tap('person-equip');await t.tap('back');await t.tap('tab-weapons');await t.tap('item-spear');await mark('08-weapon-detail');let before=await t.snap();await t.tap('upgrade-item');let after=await t.snap();assert.equal(after.save.weaponLevels.spear,before.save.weaponLevels.spear+1);await mark('09-upgraded');await t.tap('back');await t.tap('tab-treasures');await t.tap('item-taiping');await mark('10-treasure-detail');await t.tap('equip-item');await t.tap('back');await t.tap('back');await t.tap('settings');await mark('11-settings');await t.tap('sfx');await t.tap('vibration');await t.tap('motion');await t.tap('back');await t.tap('start');await t.tap('depart');await t.p.waitForTimeout(1800);await t.tap('pause');await mark('12-pause');let paused=(await t.snap()).battle.t;await t.tap('quit');await mark('13-confirm');await t.tap('back');assert.equal((await t.snap()).battle.t,paused);await t.tap('continue');await t.p.waitForTimeout(300);await t.tap('pause');await t.tap('quit');await t.tap('confirm-quit');await mark('14-back-home');
 // New isolated scenario between independent flows is explicitly labelled in events; video stays continuous.
 await t.goto('milestone:9');await mark('15-upper-reward');let reward=await t.snap(),xp=reward.save.xp;await t.swipe(0,-270);await mark('16-reward-tray');await t.tap('reward-done');assert.equal((await t.snap()).save.xp,xp);await mark('17-after-reward');
 await t.goto('result');await mark('18-repeat-result');await t.tap('next');await mark('19-transition');await t.tap('prepare-next');await mark('20-next-prepare');
 await t.goto('milestone:19');await mark('21-final');await t.tap('reward-done');await mark('22-complete-home');
 await t.goto('defeat');await mark('23-defeat');await t.tap('view-reward');await mark('24-adjust');
 await t.goto('error');await mark('25-resource-error');await t.tap('retry');await t.p.waitForFunction(()=>__YLCG__.snapshot().screen==='home');await mark('26-recovered');
 await t.goto('save-error');await mark('27-save-error');await t.tap('retry-save');await mark('28-save-retried');assert.deepEqual(t.errors,[]);
}finally{const video=await t.close();fs.writeFileSync(E+'/page-flow.json',JSON.stringify({events,video,pageErrors:t.errors,input:'Chromium system touch events, not physical finger',scenario_boundaries:'goto entries start new isolated memory fixture; within each flow use real page buttons',speed:'original browser wall time'},null,2));console.log(video);}
