import {open,E} from './browser.mjs';import fs from 'node:fs';import assert from 'node:assert/strict';const t=await open('states'),rows=[];const shot=async(n)=>{const s=await t.capture(n);rows.push({name:n,screen:s.screen,save:s.save,buttons:s.buttons,build:s.build});return s;};
try{
 await t.goto('person:guan');const original=(await t.snap()).save.companions;await t.tap('person-equip');await shot('state-full-party');await t.tap('back');assert.deepEqual((await t.snap()).save.companions,original);await t.tap('person-equip');await t.tap('replace-zhao');assert.ok((await t.snap()).save.companions.includes('guan'));await shot('state-replaced-party');
 await t.goto('person:liubei');await shot('state-allied-person');await t.goto('person:diao');await shot('state-support-person');
 await t.goto('new');await t.tap('start');await shot('state-empty-prepare');await t.tap('tab-support');await shot('state-empty-support');await t.tap('tab-treasures');await shot('state-locked-slots');await t.tap('back');await t.tap('collection');await t.tap('tab-weapons');await t.tap('item-guandao');await shot('state-unowned-weapon');assert.ok(!(await t.snap()).buttons.some(b=>b.id==='upgrade-item'));
 await t.goto('item:liannu');let s=await t.snap();while(s.save.weaponLevels.liannu<5){await t.tap('upgrade-item');s=await t.snap();}await shot('state-max-weapon');assert.ok(!s.buttons.some(b=>b.id==='upgrade-item'));await t.tap('back');await t.tap('tab-weapons');await t.tap('item-spear');s=await t.snap();while(s.buttons.some(b=>b.id==='upgrade-item')){await t.tap('upgrade-item');s=await t.snap();}await shot('state-upgrade-ended');
 await t.goto('reward:1');await t.tap('reward-primary');await shot('state-reward-detail');await t.tap('back');let reward=await t.snap();await t.tap('back');await shot('state-pending-home');assert.ok((await t.snap()).buttons.some(b=>b.id==='recover-reward'));await t.tap('recover-reward');await t.p.waitForTimeout(500);assert.equal((await t.snap()).save.xp,reward.save.xp);await t.tap('reward-done');await shot('state-reward-ack');
 await t.goto('complete');await t.tap('chapters');await shot('state-map-end');await t.swipe(0,320);await t.swipe(0,320);await shot('state-map-scrolled');await t.tap('map-current');await shot('state-map-current');
 assert.deepEqual(t.errors,[]);
}catch(e){console.error(e);throw e;}finally{fs.writeFileSync(E+'/page-states.json',JSON.stringify({rows,pageErrors:t.errors,scope:'actual Cocos system touch on memory-only legal fixtures'},null,2));await Promise.race([t.close(),new Promise(r=>setTimeout(r,7000))]);}
