"""Pack generated rear-facing riders; preserves original RGBA source pixels.
Only isolated transparent-background specks are removed by alpha-component ownership.
No pose drawing, pixel recolouring, or synthetic leg animation is performed here.
"""
from pathlib import Path
from collections import deque
from PIL import Image,ImageFilter,ImageDraw
import numpy as np,json,hashlib,uuid
P=Path(__file__).resolve().parent;R=P.parents[1];O=R/'assets/resources/formal20260927'
poses=['run0','run1','run2','run3','wind','rel','rec','hurt']
# Full original sheet pixel positions, manually checked on mounted-anchor-inspection.jpg.
pivots=[(270,437),(696,437),(1137,437),(1580,437),(272,869),(697,869),(1138,869),(1580,869)]
rights=[(332,126),(760,128),(1203,130),(1630,127),(333,505),(801,488),(1203,552),(1621,527)]
lefts=[(197,128),(614,133),(1049,128),(1492,129),(193,554),(613,553),(1049,567),(1492,563)]
frames={};sheets={};hands={};metadata={};checks=[]
for mount in ['jingfan','dilu','jueying','chitu']:
 source=P/f'mounted-{mount}-source.png';im=Image.open(source).convert('RGBA');sha=hashlib.sha256(source.read_bytes()).hexdigest();atlas=Image.new('RGBA',(1792,896));board=Image.new('RGB',(1792,896),'#233745');dr=ImageDraw.Draw(board)
 for n,pose in enumerate(poses):
  ox,oy=round(n%4*im.width/4),round(n//4*im.height/2);ex,ey=round((n%4+1)*im.width/4),round((n//4+1)*im.height/2);raw=im.crop((ox,oy,ex,ey));a=np.array(raw);mask=a[:,:,3]>24;seen=np.zeros(mask.shape,bool);largest=[];counts=[]
  for sy,sx in zip(*np.where(mask)):
   if seen[sy,sx]:continue
   q=deque([(int(sx),int(sy))]);seen[sy,sx]=True;coords=[]
   while q:
    x,y=q.popleft();coords.append((x,y))
    for xx,yy in [(x-1,y),(x+1,y),(x,y-1),(x,y+1)]:
     if 0<=xx<raw.width and 0<=yy<raw.height and mask[yy,xx] and not seen[yy,xx]:seen[yy,xx]=True;q.append((xx,yy))
   counts.append(len(coords))
   if len(coords)>len(largest):largest=coords
  keep=np.zeros(mask.shape,np.uint8)
  for x,y in largest:keep[y,x]=255
  keep=np.array(Image.fromarray(keep).filter(ImageFilter.MaxFilter(5)));a[:,:,3]=np.minimum(a[:,:,3],keep)
  clean=Image.fromarray(a);assert len(largest)>30000,(mount,pose,len(largest))
  cell=Image.new('RGBA',(448,448));cell.alpha_composite(clean,(2,2));tx,ty=n%4*448,n//4*448;atlas.alpha_composite(cell,(tx,ty));board.paste(cell,(tx,ty),cell)
  point=lambda p:[round((p[0]-ox+2)/448,6),round((p[1]-oy+2)/448,6)]
  foot=point(pivots[n]);right=point(rights[n]);left=point(lefts[n]);key=f'feel_ride_{mount}_{pose}';sid=f'feel_mounted_{mount}'
  frames[key]={'s':sid,'r':[tx,ty,448,448],'a':[foot[0],round(1-foot[1],6)],'bh':424}
  hands[key]={'right':right,'left':left};metadata[key]={'role':'hero','camera':'march-rear','semanticPose':pose,'source':str(source.relative_to(R)),'sourceSha':sha,'bodyHeight':424,'feetAnchor':foot,'bodyBox':[.16,.025,.69,.96],'pelvisAnchor':[foot[0],.48],'canonicalScale':1,'metadataBasis':'manual_full_cell_feet_and_fists','qualityStatus':'source_checked_runtime_pending'}
  checks.append({'key':key,'sourceSha':sha,'sourceCell':n,'alphaBounds':cell.getbbox(),'largestAlphaComponent':len(largest),'removedComponents':sorted(counts,reverse=True)[1:10],'rightFist':right,'leftHandOccludedByCape':left})
  dr.text((tx+5,ty+6),pose,fill='white');fx,fy=tx+foot[0]*448,ty+foot[1]*448;dr.ellipse((fx-3,fy-3,fx+3,fy+3),fill='cyan');rx,ry=tx+right[0]*448,ty+right[1]*448;dr.ellipse((rx-3,ry-3,rx+3,ry+3),outline='red',width=2)
 path=O/f'feel-mounted-{mount}.png';atlas.save(path);sheets[sid]=f'formal20260927/feel-mounted-{mount}'
 base=json.loads((O/'r2-chitu-crossbow.png.meta').read_text());u=str(uuid.uuid5(uuid.NAMESPACE_URL,'yilu/battle-feel-20261004/'+path.name));base['uuid']=u;base['userData']['redirect']=u+'@6c48a';sub=base['subMetas']['6c48a'];sub['uuid']=u+'@6c48a';sub['displayName']=path.stem;sub['userData']['imageUuidOrDatabaseUri']=u;sub['userData']['wrapModeS']='clamp-to-edge';sub['userData']['wrapModeT']='clamp-to-edge';path.with_suffix('.png.meta').write_text(json.dumps(base,indent=2)+'\n');board.save(P/f'mounted-{mount}-anchors.jpg',quality=94)
(R/'assets/scripts/formal/BattleFeelArt.ts').write_text('// Generated by art-source/battle-feel-20261004/pack-mounted.py. Battle-only; menus retain original assets.\nexport const BATTLE_FEEL_ART:any='+json.dumps({'sheets':sheets,'frames':frames},separators=(',',':'))+';\nexport const BATTLE_FEEL_HANDS:any='+json.dumps(hands,separators=(',',':'))+';\nexport const BATTLE_FEEL_ACTOR_META:any='+json.dumps(metadata,separators=(',',':'))+';\n')
(P/'mounted-frame-audit.json').write_text(json.dumps({'frames':checks,'runtime':'pending','bodyHeight':424,'camera':'rear toward world forward','sourceMethod':'built-in imagegen, then connected-alpha component slicing; no generated pose deformation'},indent=2)+'\n')
print('Packed',len(frames),'frames across',len(sheets),'atlases; source RGBA retained.')
