from pathlib import Path
from PIL import Image,ImageFilter,ImageDraw
from collections import deque
import numpy as np,json,hashlib,uuid
P=Path(__file__).resolve().parent;R=P.parents[1];O=R/'assets/resources/formal20260927';frames={};sheets={};meta={};checks=[]
for mount in ['jingfan','dilu','jueying','chitu']:
 src=P/f'mounted-ranged-{mount}-source.png';im=Image.open(src).convert('RGBA');sha=hashlib.sha256(src.read_bytes()).hexdigest();atlas=Image.new('RGBA',(1600,1200));board=Image.new('RGB',atlas.size,'#273b48');dr=ImageDraw.Draw(board)
 for row,(weapon,y0,y1,foot,refH) in enumerate([('liannu',0,342,337,311),('yanlinggong',342,712,706,307),('jiguannu',712,1024,1022,282)]):
  for col,pose in enumerate(['run','wind','rel','rec']):
   raw=im.crop((col*384,y0,(col+1)*384,y1));a=np.array(raw);mask=a[:,:,3]>24;seen=np.zeros(mask.shape,bool);main=[];counts=[]
   for sy,sx in zip(*np.where(mask)):
    if seen[sy,sx]:continue
    q=deque([(int(sx),int(sy))]);seen[sy,sx]=True;coords=[]
    while q:
     x,y=q.popleft();coords.append((x,y))
     for xx,yy in [(x-1,y),(x+1,y),(x,y-1),(x,y+1)]:
      if 0<=xx<raw.width and 0<=yy<raw.height and mask[yy,xx] and not seen[yy,xx]:seen[yy,xx]=True;q.append((xx,yy))
    counts.append(len(coords))
    if len(coords)>len(main):main=coords
   keep=np.zeros(mask.shape,np.uint8)
   for x,y in main:keep[y,x]=255
   a[:,:,3]=np.minimum(a[:,:,3],np.array(Image.fromarray(keep).filter(ImageFilter.MaxFilter(3))))
   clean=Image.fromarray(a);assert len(main)>20000,(mount,weapon,pose,len(main));cell=Image.new('RGBA',(400,400));cell.alpha_composite(clean,(8,8));x,y=col*400,row*400;atlas.alpha_composite(cell,(x,y));board.paste(cell,(x,y),cell)
   # Center the physical horse feet using its lower-leg alpha extent, not wide cape / weapon bounds.
   low=mask[max(0,foot-y0-85):max(1,foot-y0-10),:];ys,xs=np.where(low);cx=(int(xs.min())+int(xs.max()))/2+8
   fy=foot-y0+8;key=f'feel_ride_{mount}_{weapon}_{pose}';sid='feel_ranged_'+mount
   frames[key]={'s':sid,'r':[x,y,400,400],'a':[round(cx/400,6),round(1-fy/400,6)],'bh':refH}
   meta[key]={'actorId':'player','role':'hero_mounted','camera':'march-rear','semanticPose':pose,'source':str(src.relative_to(R)),'sourceSha':sha,'bodyHeight':refH,'feetAnchor':[round(cx/400,6),round(fy/400,6)],'bodyBox':[.22,.065,.58,.85],'pelvisAnchor':[round(cx/400,6),.5],'canonicalScale':1,'metadataBasis':'whole_source_alpha; row_body_height_and_feet','qualityStatus':'source_checked_runtime_pending','bodyContainsWeapon':True,'weaponId':weapon}
   checks.append({'key':key,'alphaBounds':cell.getbbox(),'largestAlphaComponent':len(main),'removedComponents':sorted(counts,reverse=True)[1:6]});dr.text((x+5,y+5),weapon+' '+pose,fill='white');dr.ellipse((x+cx-3,y+fy-3,x+cx+3,y+fy+3),fill='cyan')
 path=O/f'feel-ranged-{mount}.png';atlas.save(path);sheets['feel_ranged_'+mount]='formal20260927/'+path.stem
 base=json.loads((O/'r2-chitu-crossbow.png.meta').read_text());u=str(uuid.uuid5(uuid.NAMESPACE_URL,'yilu/battle-feel-20261004/'+path.name));base['uuid']=u;base['userData']['redirect']=u+'@6c48a';sub=base['subMetas']['6c48a'];sub['uuid']=u+'@6c48a';sub['displayName']=path.stem;sub['userData']['imageUuidOrDatabaseUri']=u;sub['userData']['wrapModeS']='clamp-to-edge';sub['userData']['wrapModeT']='clamp-to-edge';path.with_suffix('.png.meta').write_text(json.dumps(base,indent=2)+'\n');board.save(P/f'mounted-ranged-{mount}-anchors.jpg',quality=94)
(P/'mounted-ranged-audit.json').write_text(json.dumps(checks,indent=2)+'\n')
(R/'assets/scripts/formal/BattleFeelRangedArt.ts').write_text('// Generated by art-source/battle-feel-20261004/pack-ranged.py\nexport const BATTLE_FEEL_RANGED_ART:any='+json.dumps({'sheets':sheets,'frames':frames},separators=(',',':'))+';\nexport const BATTLE_FEEL_RANGED_META:any='+json.dumps(meta,separators=(',',':'))+';\n')
print('Packed',len(frames),'dedicated ranged mounted poses')
