#!/usr/bin/env python3
"""Read-only device-bundle audit. Never launches an app or records audio."""
from pathlib import Path
import json,hashlib,re,datetime,plistlib
ROOT=Path(__file__).resolve().parents[2];APP=ROOT/'build/ios-device/proj/Release-iphoneos/CocosGame.app';OUT=ROOT/'evidence/YILU-CAMPAIGN20-20260930/audio-final-audit.json'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
old=json.loads((ROOT/'art-source/weapon-sfx-20260930/asset-manifest.json').read_text());new=json.loads((ROOT/'art-source/campaign20-audio/asset-manifest.json').read_text());config=json.loads((APP/'assets/resources/cc.config.json').read_text());paths={v[0]:k for k,v in config['paths'].items()};script=(APP/'assets/main/index.js').read_text();fingerprint=re.search(r'code_fingerprint:"([a-f0-9]{64})"',script);rows=[];source_hashes={}
for r in old['files']+new['files']:
 p=ROOT/r['path'];meta=json.loads(Path(str(p)+'.meta').read_text());uid=meta['uuid'];native=APP/'assets/resources/native'/uid[:2]/(uid+'.wav');resource='audio/weapons/'+r['id'];sources=[]
 for s in r['sources']:
  source=ROOT/'art-source/weapon-sfx-20260930'/s['file'];key=str(source)
  if key not in source_hashes:source_hashes[key]=sha(source) if source.exists() else None
  sources.append({'path':str(source.relative_to(ROOT)),'expectedSha256':s['sha256'],'currentSha256':source_hashes[key],'matches':source_hashes[key]==s['sha256']})
 rows.append({'id':r['id'],'baseline':r in old['files'],'resource':resource,'resourceRegistered':resource in paths,'uuid':uid,'sourceSha256':sha(p),'manifestSha256':r['sha256'],'sourceUnchanged':sha(p)==r['sha256'],'builtPath':str(native.relative_to(ROOT)),'builtSha256':sha(native) if native.exists() else None,'builtBytesEqual':native.exists() and sha(native)==r['sha256'],'sources':sources})
block=bool(re.search(r'(?:"block"===\w+\.phase|\w+\.phase==="block")\?"impact-wood"',script));model=json.loads((ROOT/'evidence/YILU-CAMPAIGN20-20260930/audio-event-final-audit.json').read_text());srcs=['assets/scripts/formal/WeaponSfx.ts','assets/scripts/formal/battle.ts','assets/scripts/formal/FormalGame.ts','assets/scripts/Platform.ts'];info=plistlib.loads((APP/'Info.plist').read_bytes())
checks={'resourceCount':len(rows),'old51SourceByteIdentical':all(r['sourceUnchanged'] for r in rows if r['baseline']),'old51BuiltByteIdentical':all(r['builtBytesEqual'] for r in rows if r['baseline']),'new21RegisteredAndBuilt':all(r['resourceRegistered'] and r['builtBytesEqual'] for r in rows if not r['baseline']),'allSourceRecordingHashesVerified':all(s['matches'] for r in rows for s in r['sources']),'newSixReleaseVariantCount':18,'newMechanismLoadVariantCount':3,'blockRoutingCompiled':block,'rewardContextCompiled':':reward:' in script and 'logMessage' in script,'blockRoutingSourceModel':model['blockUsesMaterialClip'],'noDuplicateLegacyHitPath':"this.platform.sound('hit')" not in (ROOT/srcs[2]).read_text(),'nativePlaybackNotPerformedByAudit':True}
result={'task':'YILU-CAMPAIGN20-20260930','producedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'captureType':'static-native-bundle-plus-pure-model','scope':'Actual Release iPhone bundle byte/resource audit and source event model. No launch, recording, subjective listening or phone loudness acceptance.','app':{'path':str(APP),'bundleId':info['CFBundleIdentifier'],'version':info['CFBundleShortVersionString'],'build':info['CFBundleVersion'],'embeddedCodeFingerprint':fingerprint[1] if fingerprint else None,'mainScriptSha256':sha(APP/'assets/main/index.js'),'resourcesConfigSha256':sha(APP/'assets/resources/cc.config.json')},'audioSourceSHA256':{s:sha(ROOT/s) for s in srcs},'checks':checks,'resourceRows':rows,'license':{'new21':'CC0 1.0','sources':new['sources'],'cachedLicensePage':'art-source/weapon-sfx-20260930/license-page-0.html','editManifest':'art-source/campaign20-audio/asset-manifest.json','licensePageSha256':sha(ROOT/'art-source/weapon-sfx-20260930/license-page-0.html'),'allLayerInputsRetained':checks['allSourceRecordingHashesVerified']},'mixer':{'perKind':1,'globalVoices':3,'globalVolume':.65,'startsPerSecond':12,'minStartGapMs':25,'pendingExpiryMs':140,'dangerSlotsReservedPerSecond':2,'variantCount':3,'blockSharesHeroImpactKind':True},'eventAudit':model,'rewardAudio':{'newCeremonyClipAdded':False,'requirementOptional':True,'existingPickupCue':'gather clip unchanged; battle passes runId/time/kind/msg stable context with reward:<kind> identity; calls without context keep legacy fallback','rewardScreenAudioEnabled':False,'facts':'show(reward) disables audio; no dedicated new-reward/milestone sound. Task says short ceremonial sounds may be added, so this is an optional omission. Battle pickup cues carry reward log provenance; no optional ceremony clip was added.'},'remainingGaps':[{'id':'chain-foley','kind':'production-description','detail':'tiesuodao uses licensed sword-drawing metal friction as moving-chain-like foley; not an authentic chain recording or historical weapon recording.'},{'id':'listening','kind':'not-performed','detail':'Human phone/speaker/headphone listening and actual native playback belong to separate evidence; this audit does not claim them.'}],'status':'bundle_resources_pass_and_block_fix_compiled' if all([checks['old51BuiltByteIdentical'],checks['new21RegisteredAndBuilt'],block,checks['rewardContextCompiled']]) else 'resources_checked_block_fix_needs_rebuilt_bundle'}
OUT.write_text(json.dumps(result,ensure_ascii=False,indent=2));print(json.dumps({'status':result['status'],'checks':checks,'fingerprint':result['app']['embeddedCodeFingerprint']}))
