#!/usr/bin/env python3
"""Summarize observed native evidence; never synthesize missing passes."""
import pathlib,json,datetime,hashlib,statistics,sys
R=pathlib.Path(__file__).resolve().parents[2];E=R/'evidence/YILU-CAMPAIGN20-20260930';N=E/'native-campaign';D=R/'deliverables/YILU-CAMPAIGN20-20260930'
read=lambda p:json.loads(p.read_text());M=read(E/'bridge-build-manifest.json');fp=M['code_fingerprint'];runs=read(N/'results.json')
samples=[]
for line in (N/'progress.jsonl').read_text().splitlines():
 try:samples.append(json.loads(line))
 except ValueError:pass
design=read(R/'docs/YILU-CAMPAIGN20-20260930/intake/campaign20.design.json');rows=[]
for run in runs:
 c=run['chapter'];spec=design['chapters'][c-1];lo,hi=spec['target_active_seconds'];part=[s for s in samples if s['runId']==run['runId']];counts=[s['counts'] for s in part if s.get('counts')];boss_entry=next((s for s in part if s.get('phase')!='march' and s['screen']=='battle'),None)
 rows.append({'chapter':c,'title':spec['title'],'won':run['won'],'run_id':run['runId'],'simulation_seconds':run['simulationSeconds'],'foreground_seconds':run['foregroundSeconds'],'target_seconds':[lo,hi],'duration_within_target':lo<=run['simulationSeconds']<=hi,'timing':run['timing'],'boss_entry_troops_sampled':boss_entry['troops'] if boss_entry else None,'end_troops':run['troops'],'route_xp':run['routeXP'],'damage_sources':run['damageSources'],'stats':run['stats'],'fps':run['fps'],'render_intervals':run['performance'],'max_visible_enemies_sampled':max([s.get('visible_enemies',0) for s in counts]or[0]),'max_visible_soldiers_sampled':max([s.get('visible_soldiers',0) for s in counts]or[0]),'max_active_projectiles_sampled':max([s.get('active_projectiles',0) for s in counts]or[0]),'build_match':run['build']['code_fingerprint']==fp,'render_errors':run['renderErrors'],'invalid_rects':run['invalidRects'],'missing_art':run['missingArt']})
complete=len(rows)==20 and len({r['chapter'] for r in rows})==20 and all(r['won'] and r['build_match'] for r in rows)
result={'task':'YILU-CAMPAIGN20-20260930','produced_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'build':{k:M[k] for k in ['build_id','code_fingerprint','target','configuration','produced_at']},'capture_type':'simulator','scope':'Single fresh in-memory save, 20 sequential chapters with legal earned loadouts and DEBUG lateral inputs. Not human touch. Sampled counts are not GPU counters or continuous maxima.','status':'passed' if complete else 'in_progress_or_incomplete','completed_count':len(rows),'all_durations_in_target':all(r['duration_within_target'] for r in rows),'zero_render_errors':all(not any(r[k] for k in ['render_errors','invalid_rects','missing_art']) for r in rows),'final_save_summary':{k:runs[-1]['save'].get(k) for k in ['schemaVersion','cleared','weapons','captures','visits','allies','treasures','badges','xp','selectedWeaponId']},'rows':rows,'source_results_sha256':hashlib.sha256((N/'results.json').read_bytes()).hexdigest(),'source_progress_sha256':hashlib.sha256((N/'progress.jsonl').read_bytes()).hexdigest()}
(E/'native-summary.json').write_text(json.dumps(result,ensure_ascii=False,indent=2));D.mkdir(exist_ok=True);lines=['# 二十关原生连续回归','',result['scope'],'',f'状态：{result["status"]}；已完成 {len(rows)}/20。代码指纹 `{fp}`。','', '|关|实测游戏秒|前台秒|目标秒|行军/途中名将/Boss秒|结余兵力|模拟器FPS|','|---|---:|---:|---|---|---:|---:|']
for r in rows:
 t=r['timing'];lines.append(f'|{r["chapter"]:02} {r["title"]}|{r["simulation_seconds"]:.1f}|{r["foreground_seconds"]:.1f}|{r["target_seconds"][0]}–{r["target_seconds"][1]}|{t.get("march",0):.1f} / {t.get("officer",0):.1f} / {t.get("boss",0):.1f}|{r["end_troops"]}|{r["fps"]:.1f}|')
lines+=['','FPS 为开启 DEBUG 诊断、部分区间录屏的模拟器渲染间隔结果，不代表 iPhone 性能。菜单、奖励、转场不计入游戏战斗秒；本次不修改时间尺度。详细兵损来源、采样人数、原始逐关保存和运行事件见 `native-summary.json` 与 `native-campaign/`。'];(D/'逐关实测.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'complete':complete,'chapters':len(rows),'durations_pass':result['all_durations_in_target'],'code_fingerprint':fp}))
