import test from 'node:test';import assert from 'node:assert/strict';
import {createBattle} from '../assets/scripts/formal/battle';import {FormalStore} from '../assets/scripts/formal/store';import {CHAPTERS,WEAPON_DATA,difficultyFor} from '../assets/scripts/formal/data';
import {EncounterDirector,reachableSafety} from '../assets/scripts/formal/EncounterDirector';import {ENEMY_PROFILES,volleyBonus,reductionProduct,enemyArmor} from '../assets/scripts/formal/EnemyProfiles';
function make(chapter=0,extend:any={}){const store=new FormalStore({getItem:()=>null,setItem:()=>{}});return createBattle({chapter,lineup:{...store.loadout(),...extend},seed:71});}
function quiet(b:any){const s=b.state;s.course=[];s.ents=[];s.speed=0;s.volleyT=1e5;s.show=1e5;s.companions=[];return s;}
function ticks(b:any,n:number){for(let i=0;i<n;i++)b.step();}
function shot(s:any,id:number,extra:any={}){s.waves.push({projectileId:id,attackId:'a',subAttackId:id,source:'hero',weaponId:'spear',x:0,x0:0,z:1,z0:1,speed:100,range:10,t:0,hits:new Set(),pierce:1,dmg:10,hw:.2,...extra});}
test('all six new enemy threats have individual fixed HP, damage and meaningful pacing',()=>{assert.equal(Object.keys(ENEMY_PROFILES).length,7);for(const k of ['guard','shield','archer','cavalry','banner','mechanism'])assert.ok(ENEMY_PROFILES[k].hp>=2);assert.equal(ENEMY_PROFILES.shield.hp,7);assert.equal(ENEMY_PROFILES.mechanism.speed,0);assert.equal(difficultyFor(19).minimumTelegraph,1.1);});
test('reachability dilates danger by squad footprint and includes 300ms reaction',()=>{assert.equal(reachableSafety(0,0,.4,[[-.4,.4]],3,.28).safe,false);assert.equal(reachableSafety(0,0,1.6,[[-.2,.2]],3,.28).safe,true);assert.equal(reachableSafety(-.55,0,1.6,[[-1,-.1]],3,.28,[-.68,-.42]).safe,false);});
test('director defers an overlapping attack and a wall-blocked escape, never publishes it',()=>{const d=new EncounterDirector(),base={id:'a',source:'archer',kind:'archer',now:0,warning:1.5,x:0,speed:3,halfWidth:.28,bounds:[-.68,.68] as [number,number],maxThreats:2};assert.ok(d.schedule({...base,bands:[[-1,-.1]]}));assert.equal(d.schedule({...base,id:'b',source:'cavalry',bands:[[.1,1]]}),null);assert.equal(d.active.length,1);assert.equal(d.deferred,1);});
test('gate cap uses initial signed value and duplicate sub-attacks count once',()=>{const b=make(),s=quiet(b);s.ents=[{id:1,type:'gate',x:0,d:2,val:-3,initial:-3,growthCap:6,passed:false}];for(let i=0;i<12;i++){shot(s,i,{subAttackId:0});b.step();}assert.equal(s.ents[0].val,-2);for(let i=1;i<20;i++){shot(s,i,{subAttackId:i});b.step();}assert.equal(s.ents[0].val,3);assert.equal(b.totals.gate,6);});
test('selected owned weapon enters at tier one; illegal selection returns to spear',()=>{const b=make(10,{weapons:['spear','huaji'],startWeaponId:'huaji'});assert.equal(b.state.weapon,'huaji');assert.equal(b.state.tier,1);assert.equal(make(0,{startWeaponId:'jiguannu'}).state.weapon,'spear');assert.ok(b.state.course.some(e=>e.kind==='weapon'&&e.gives==='huaji'));});
test('army damage grows logarithmically after 40 with eight-arrow hard budget',()=>{assert.equal(volleyBonus(40),1);assert.ok(volleyBonus(80)>1);assert.equal(volleyBonus(1e9),1.3);const b=make(),s=quiet(b);s.troops=10000;s.volleyT=0;b.step();assert.equal(s.arrows.length,8);assert.ok(s.arrows.every(a=>a.dmg===1.3));});
test('shield exposure and armor weakening affect one damage factor, never HP twice',()=>{assert.ok(Math.abs(enemyArmor('shield',false,false,false)-.45)<1e-8);assert.equal(enemyArmor('shield',true,false,false),1);assert.equal(enemyArmor('shield',false,true,false),.7);assert.ok(Math.abs(enemyArmor('shield',false,false,true)-.56)<1e-8);assert.equal(reductionProduct([.65,.75,.8]),.5);});
test('shield first approaches real melee reach, locks a warning and exposes recovery',()=>{const b=make(11),s=quiet(b);s.heroX=s.targetX=-.45;s.ents=[{id:1,type:'enemy',enemyKind:'shield',x:-.45,d:12,hp:100,walk:0,dead:0,phase:'approach',pt:0}];b.step();const e=s.ents[0];assert.notEqual(e.phase,'warn');assert.equal(s.damageHistory.length,0);for(let i=0;i<900&&e.phase!=='warn';i++)b.step();assert.equal(e.phase,'warn');const band=[...e.band];b.move(.68);for(let i=0;i<180&&e.phase!=='rec';i++)b.step();assert.deepEqual(e.band,band);assert.equal(s.damageHistory.length,0);assert.ok(s.avoidances>0);assert.equal(e.phase,'rec');const at=s.t;for(let i=0;i<40;i++)b.step();assert.equal(e.phase,'rec');assert.ok(s.t-at>.65);});
test('mechanism book extends actual execution deadline by exactly 200ms',()=>{const deadline=(book:boolean)=>{const b=make(17),s=quiet(b);s.slots.dian.id=book?'xingjunyaolue':null;s.ents=[{id:1,type:'enemy',enemyKind:'mechanism',x:s.heroX,d:12,hp:100,walk:0,dead:0,phase:'idle',pt:9}];b.step();return s.ents[0].telegraph.execute;};assert.ok(Math.abs(deadline(true)-deadline(false)-.2)<1e-8);});
test('Lusu cannot generate soldiers with no casualties',()=>{const b=make(11,{support:'lusu'}),s=quiet(b);ticks(b,900);assert.equal(s.troops,30);assert.equal(s.losses.length,0);});
test('six weapons release actual projectiles and preserve distinct audio identity',()=>{for(const id of ['duanji','tiesuodao','goulianqiang','dundao','yanlinggong','jiguannu']){const b=make(19,{weapons:['spear',id],startWeaponId:id}),s=quiet(b);s.show=0;ticks(b,90);const events=b.drainAudioEvents().filter(e=>e.phase==='release'&&e.source==='hero');assert.ok(events.length,id);assert.ok(events.every(e=>e.weaponId===id),id);if(id==='duanji')assert.ok(events.length>=2);}});
test('milestone20 reward cannot retroactively add opening soldiers before ownership',()=>{assert.equal(make(19).state.troops,30);assert.equal(make(19,{treasures:{dian:null,qi:'jiuzhouyin',ma:null}}).state.troops,38);});
test('boss runtime HP is the chapter authority for every stage',()=>{for(let i=0;i<20;i++){const b=make(i),s=b.state;s.dist=CHAPTERS[i].length+6;s.defeatedOfficerIds=CHAPTERS[i].enemy.filter(x=>x!=='xing'&&x!=='chen'&&x!=='yang');s.course=[];b.step();if(s.boss)assert.equal(s.boss.max,CHAPTERS[i].bossHP);}});
test('same-source simultaneous boss subwaves lose soldiers once; independent sources remain independent',()=>{const run=(same:boolean)=>{const b=make(),s=quiet(b);s.heroX=s.targetX=0;s.boss={person:'jiao',name:'张角',hp:100,max:100,trail:100,phase:'idle',pt:0,band:[-.5,.5],z:17,hit:0,flags:4,flagFx:[],cycleN:0};s.minT=1e5;s.waves=[0,1].map(i=>({boss:true,attackId:same?'charge':'charge'+i,band:[-.5,.5],damage:5,x:0,z:.1,z0:17,speed:-40,t:0,hits:new Set(),range:99}));b.step();return s.troops;};assert.equal(run(true),25);assert.equal(run(false),20);});
test('gate ambush bypasses heavy-hit mirror and defensive weapon, preserving honest damage source',()=>{const b=make(10,{weapons:['spear','dundao'],startWeaponId:'dundao'}),s=quiet(b);s.slots.qi.id='huxinjing';s.ents=[{id:77,type:'gate',x:s.heroX,d:0,val:-10,passed:false}];b.step();assert.equal(s.troops,20);assert.equal(s.damageSources.gate,10);assert.equal(s.mirrorReady,undefined);});
test('Lusu heals only actual recent casualties at 12 second intervals, never a six-second double tick',()=>{const b=make(11,{support:'lusu'}),s=quiet(b);s.support.cd=12;s.ents=[{id:77,type:'gate',x:s.heroX,d:0,val:-5,passed:false}];ticks(b,370);assert.equal(s.troops,25);ticks(b,355);assert.equal(s.troops,28);assert.equal(s.support.uses,1);ticks(b,720);assert.equal(s.troops,28);});
test('same-volley tier3 split projectiles charge a gate only once',()=>{const b=make(),s=quiet(b);s.heroX=s.targetX=0;s.show=0;s.tier=3;s.atkT=.13;s.ents=[{id:1,type:'gate',x:0,d:2,val:-3,initial:-3,growthCap:6,passed:false}];ticks(b,10);assert.equal(s.ents[0].val,-2);});
test('a destroyed alternative weapon waits for same-lane pickup rather than replacing chosen loadout remotely',()=>{const b=make(),s=quiet(b);s.ents=[{id:1,type:'crate',kind:'weapon',gives:'guandao',x:0,d:2,hp:1,max:1,open:0}];shot(s,1);b.step();assert.equal(s.weapon,'spear');assert.equal(s.ents[0].pendingWeapon,true);s.heroX=s.targetX=0;s.ents[0].d=s.dist;b.step();assert.equal(s.weapon,'guandao');});
test('boss phase changes cancel uncommitted warnings while released projectiles remain live',()=>{const b=make(19),s=quiet(b);s.troops=17;s.boss={person:'lukang',name:'陆抗',hp:70,max:100,trail:70,phase:'idle',pt:0,band:[-.5,.5],z:2,hit:0,flags:4,flagFx:[],cycleN:0};s.minT=1e5;const charge={source:'released-arrow',attackId:'released-arrow',sourceEnemyId:89,done:false,x:.65,z:12,origin:{x:.65,z:12},lockedTarget:{x:.65,z:-.3},duration:12,t:0,damage:2,kind:'archer',telegraph:{id:'released-arrow',released:true,bands:[[.5,.8]],created:0,execute:0,end:12}};s.hostileShots=[charge];const e={id:88,type:'enemy',enemyKind:'shield',hp:100,x:.6,d:12,walk:0,dead:0,phase:'warn',pt:0,telegraph:{execute:10,bands:[[.4,.8]]}};s.ents=[e];shot(s,1,{dmg:50});b.step();assert.equal(s.boss.campaignPhase,1);assert.ok(s.hostileShots.includes(charge));assert.equal(e.phase,'idle');assert.equal(e.telegraph,null);assert.equal(charge.done,false);assert.ok(charge.t>0);assert.equal(s.troops,17);});

import {MANIFEST} from '../assets/scripts/formal/manifest';
import {resolveActorPresentation} from '../assets/scripts/formal/ActorPresentation';
const actualCaptured=[...new Set(CHAPTERS.flatMap(c=>c.capture))];

function captureRenderer(){const frames:string[]=[],submissions:any[]=[],noop=()=>{},renderer:any=new Proxy({measure:(s:any,n:number)=>String(s).length*n*.6,measureText:(s:any)=>({width:String(s).length*8}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),frame:(k:string,x:number,y:number,h:number,o:any={})=>{frames.push(k);submissions.push({k,...o});const f=MANIFEST.frames[k];if(!f)return null;const sc=h/(o.refH||f.r[3]);return{x:x-f.r[2]*sc/2,y:y-f.r[3]*sc,w:f.r[2]*sc,h:f.r[3]*sc};}},{get:(o,k)=>k in o?o[k]:noop});return{frames,submissions,renderer};}
test('all new companions display recovery after release without adding another attack',()=>{
 const ids=actualCaptured;assert.equal(ids.length,21);
 for(const id of ids){const {frames,renderer}=captureRenderer(),store=new FormalStore({getItem:()=>null,setItem:()=>{}}),b=createBattle({chapter:19,lineup:{...store.loadout(),companions:[id]},renderer}),s=b.state;s.course=[];s.ents=[];s.speed=0;s.show=1e5;s.volleyT=1e5;const c=s.companions[0];c.pose=.3;c.t=0;c.fired=false;b.render({W:402,H:874,top:62,bottom:34});assert.ok(frames.includes(resolveActorPresentation('ally',id,'wind').frameKey));frames.length=0;c.pose=.19;b.step();assert.equal(c.attackN,1);b.render({W:402,H:874,top:62,bottom:34});assert.ok(frames.includes(resolveActorPresentation('ally',id,'rel').frameKey));frames.length=0;c.pose=.08;b.step();b.render({W:402,H:874,top:62,bottom:34});assert.ok(frames.includes(resolveActorPresentation('ally',id,'rec').frameKey));assert.equal(c.attackN,1);}
});
test('weaponless mounted frames receive exactly two independent held parts and one body',()=>{
 for(const mount of ['jingfan','jueying'])for(const weapon of ['shuanggu','shuangji'])for(const at of [0,.14,.25,.55]){const {frames,submissions,renderer}=captureRenderer(),store=new FormalStore({getItem:()=>null,setItem:()=>{}}),b=createBattle({chapter:19,lineup:{...store.loadout(),weapons:['spear',weapon],startWeaponId:weapon,treasures:{dian:null,qi:null,ma:mount}},renderer}),s=b.state;s.show=0;s.atkT=at;b.render({W:402,H:874,top:62,bottom:34});assert.equal(submissions.filter(f=>f.role==='hero_body').length,1);assert.equal(submissions.filter(f=>f.role==='held_weapon').length,2);assert.ok(submissions.filter(f=>f.role==='held_weapon').every(f=>f.k==='g_part_'+weapon));assert.ok(submissions.filter(f=>f.role==='hero_body').every(f=>f.actorId==='player'));}
});
test('snake hero, companion and support waves execute their real render branches',()=>{
 for(const [weapon,companions,support,source] of [['shemao',[],null,'hero'],['liannu',[],null,'hero'],['spear',['zhang'],null,'companion:zhang'],['spear',[],'zhuge','support:zhuge']] as any[]){
  const {frames,submissions,renderer}=captureRenderer(),store=new FormalStore({getItem:()=>null,setItem:()=>{}}),b=createBattle({chapter:19,lineup:{...store.loadout(),weapons:['spear',weapon],startWeaponId:weapon,companions,support},renderer}),s=b.state;s.course=[];s.ents=[];s.speed=0;s.show=0;s.volleyT=1e5;s.support.cd=0;let seen=false;
  for(let i=0;i<150;i++){b.step();if(s.waves.some(w=>w.snake&&w.source===source))seen=true;b.render({W:402,H:874,top:62,bottom:34});}
  assert.ok(seen,source+' '+weapon);assert.equal(frames.includes('g_snakeTrail'),weapon!=='liannu'&&source!=='support:zhuge',source+' '+weapon+' keeps snake trajectory while crossbow uses bolt visuals');
 }
});
test('all sixteen weapons at three tiers and all new companions render their released attacks',()=>{
 const ids=actualCaptured,store=new FormalStore({getItem:()=>null,setItem:()=>{}});
 assert.equal(Object.keys(WEAPON_DATA).length,16);
 for(const weapon of Object.keys(WEAPON_DATA))for(const tier of [1,2,3]){const {renderer}=captureRenderer(),b=createBattle({chapter:19,lineup:{...store.loadout(),weapons:['spear',weapon],startWeaponId:weapon},renderer}),s=b.state;s.course=[];s.ents=[];s.speed=0;s.show=0;s.tier=tier;let released=false;for(let i=0;i<180;i++){b.step();if(s.waves.some(w=>w.source==='hero'))released=true;if(i%3===0)b.render({W:402,H:874,top:62,bottom:34});}assert.ok(released,weapon+' tier '+tier);}
 for(const id of ids){const {renderer}=captureRenderer(),b=createBattle({chapter:19,lineup:{...store.loadout(),companions:[id]},renderer}),s=b.state;s.course=[];s.ents=[];s.speed=0;s.show=0;for(let i=0;i<180;i++){b.step();if(i%3===0)b.render({W:375,H:667,top:20,bottom:8});}assert.ok(s.companions[0].attackN>=1,id);}
});
test('twenty chapter march and boss attack render domains run without branch exceptions',()=>{
 const store=new FormalStore({getItem:()=>null,setItem:()=>{}});let rendered=0;
 for(let chapter=0;chapter<20;chapter++){
  const {renderer}=captureRenderer(),b=createBattle({chapter,lineup:{...store.loadout(),companions:['zhang','zhao'],support:'zhuge'},renderer,seed:7919}),s=b.state;
  for(let i=0;i<1200&&!s.ended;i++){b.step();if(i%10===0){b.render({W:402,H:874,top:62,bottom:34});rendered++;}}
  // Explicit boss rendering fixture, not a simulated first-clear or difficulty result.
  s.course=[];s.ents=[];s.ended=false;delete s.routed;s.troops=30;s.dist=s.courseLen+6;s.defeatedOfficerIds=CHAPTERS[chapter].enemy.slice();b.step();assert.ok(s.boss,'boss fixture '+chapter);
  let bossWave=false;for(let i=0;i<600&&!s.ended;i++){b.step();if(s.waves.some(w=>w.boss)||s.hostileShots.some(w=>String(w.sourceEnemyId).startsWith('boss:')))bossWave=true;if(i%5===0){b.render({W:375,H:667,top:20,bottom:8});rendered++;}}assert.ok(bossWave,'boss attack '+chapter);
 }
 assert.ok(rendered>=4000,'march/boss rendered frames '+rendered);
});

test('camera keeps new mounted hero and both companions inside both phone widths without moving collision state',()=>{
 const store=new FormalStore({getItem:()=>null,setItem:()=>{}});
 for(const W of [375,402])for(const mount of ['jingfan','jueying'])for(const edge of [-.68,.68])for(const at of [0,.14,.25,.55]){
  const {renderer}=captureRenderer(),rects:any[]=[];renderer.frame=(k:string,x:number,y:number,h:number,o:any={})=>{const f=MANIFEST.frames[k];if(!f)return null;const sc=h/(o.refH||f.r[3]),w=f.r[2]*sc,hh=f.r[3]*sc,r={k,role:o.role,actorId:o.actorId,x:x-(o.grip?o.grip[0]:o.center?.5:f.a[0])*w,y:y-hh,w,h:hh};rects.push(r);return r;};
  const b=createBattle({chapter:19,lineup:{...store.loadout(),companions:['zhanghe','ganning'],treasures:{dian:null,qi:null,ma:mount}},renderer}),s=b.state;s.heroX=s.targetX=edge;s.show=0;s.atkT=at;s.companions.forEach(c=>c.pose=.15);b.render({W,H:W===375?667:874,top:W===375?20:62,bottom:34});
  const bodies=rects.filter(r=>['hero_body','companion_body'].includes(r.role));assert.equal(bodies.length,3);for(const r of bodies)assert.ok(r.x>=8-1e-6&&r.x+r.w<=W-8+1e-6,JSON.stringify({W,mount,edge,at,...r}));const hero=bodies.find(r=>r.role==='hero_body');for(const r of bodies.filter(r=>r.role==='companion_body'))assert.ok(r.y+r.h<hero.y||r.x+r.w<hero.x||r.x>hero.x+hero.w,'companion legs under mounted hero '+JSON.stringify({r,hero}));assert.equal(s.heroX,edge);assert.equal(s.targetX,edge);
 }
});
