import test from 'node:test';import assert from 'node:assert/strict';
import {FormalStore,FORMAL_KEY,RULES_VERSION} from '../assets/scripts/formal/store';
import {CHAPTERS,requiredOfficers,MILESTONES,WEAPON_DATA} from '../assets/scripts/formal/data';
const memory=()=>{const m=new Map<string,string>();return{m,getItem:(k:string)=>m.get(k)??null,setItem:(k:string,v:string)=>{m.set(k,v);}};};
const win=(s:FormalStore,i:number,id='w'+i)=>s.settle({id,chapter:i,won:true,troops:50,treasures:[],defeatedBossId:CHAPTERS[i].boss,defeatedOfficerIds:requiredOfficers(i)});
function old(n:number){const m=memory(),d={schemaVersion:2,cleared:CHAPTERS.slice(0,n).map(c=>c.id),claimed:CHAPTERS.slice(0,n).map(c=>'old:'+c.id),xp:137,slots:{dian:'taiping',qi:'yuxi',ma:'chitu'},weapons:['spear','guding'],weaponLevels:{spear:3,guding:2},captures:['lubu'],companions:['lubu'],visits:['hua'],support:'hua',allies:['yuan'],treasures:['taiping','yuxi','chitu'],best:{c01:200},ruleBests:{old:{c01:200}},unknown:{nested:['keep']},legacy:{exact:'bytes'}};m.setItem(FORMAL_KEY,JSON.stringify(d));return{m,d,raw:m.getItem(FORMAL_KEY)!};}
test('old 8/10 progress migrates with exact original backup and only milestone delta',()=>{for(const n of [8,10]){const {m,d,raw}=old(n),s=new FormalStore(m);assert.equal(s.completed,n);assert.equal(s.unlocked(n),true);assert.equal(s.data.schemaVersion,3);assert.equal(s.data.xp,137+n/2*60);assert.equal(m.getItem(FORMAL_KEY+'-campaign20-original'),raw);for(const key of ['weapons','weaponLevels','companions','support','treasures','slots','legacy','unknown','ruleBests'] as const)assert.deepEqual(s.data[key],d[key]);assert.equal(s.data.selectedWeaponId,'spear');assert.equal(s.data.pendingRewardPresentation?.backfilled,n/2);for(let i=0;i<10;i++){const r=new FormalStore(m);assert.equal(r.data.xp,s.data.xp);assert.equal(r.data.badges.length,n/2);}assert.equal(s.data.historicalHonors.includes('王'),n===10);}});
test('20 legitimate wins total 1930, tenth opens 11, duplicate run/reloads never grant twice',()=>{const m=memory();let s=new FormalStore(m);for(let i=0;i<CHAPTERS.length;i++){assert.ok(win(s,i));const xp=s.data.xp;for(let j=0;j<10;j++){s=new FormalStore(m);assert.equal(win(s,i),false);assert.equal(s.data.xp,xp);}assert.ok(s.data.pendingRewardPresentation);assert.ok(s.acknowledgePresentation());if(i===9){assert.equal(s.completed,10);assert.equal(s.unlocked(10),true);assert.equal(s.unlocked(20),false);}}assert.equal(s.completed,20);assert.equal(s.data.xp,1930);assert.equal(s.data.badges.length,10);assert.equal(s.data.weapons.length,16);assert.equal(s.data.treasures.length,18);assert.equal(s.data.captures.length+s.data.visits.length+s.data.allies.length,40);assert.equal(s.setReplayOrder('elite'),true);});
test('write failure cannot use migrated record and retry grants exact backfill once',()=>{const {m,raw}=old(10);let fail=true;const io={getItem:m.getItem,setItem:(k:string,v:string)=>{if(fail&&k===FORMAL_KEY)throw Error('disk full');m.setItem(k,v);}};const s=new FormalStore(io);assert.equal(m.getItem(FORMAL_KEY),raw);assert.equal(s.data.xp,137);assert.equal(s.data.schemaVersion,2);assert.ok(s.notice);assert.equal(win(s,10),false);fail=false;assert.equal(s.retry(),true);assert.equal(s.data.xp,437);assert.equal(s.data.schemaVersion,3);assert.equal(new FormalStore(io).data.xp,437);});
test('reward persisted before animation survives crash and skip is presentation only',()=>{const m=memory(),s=new FormalStore(m);win(s,0);const pending=JSON.parse(JSON.stringify(s.data.pendingRewardPresentation));assert.ok(pending);let r=new FormalStore(m);assert.deepEqual(r.data.pendingRewardPresentation,pending);assert.equal(r.data.xp,30);assert.equal(win(r,0),false);assert.equal(r.acknowledgePresentation(),true);r=new FormalStore(m);assert.equal(r.data.pendingRewardPresentation,null);assert.equal(r.data.xp,30);assert.deepEqual(r.data.treasures,['taiping']);});
test('practice rewards require combat activity, each progress segment pays only once per ruleset',()=>{const m=memory(),s=new FormalStore(m);s.settle({id:'idle',chapter:0,won:false,troops:0,treasures:[],practiceSegments:[1,2,3,4],effectiveHits:0});assert.equal(s.data.xp,0);for(let i=0;i<10;i++)s.settle({id:'lost'+i,chapter:0,won:false,troops:0,treasures:[],practiceSegments:[1,2,3,4,5],effectiveHits:20});assert.equal(s.data.xp,8);assert.equal(s.data.claimed.filter(k=>k.startsWith('practice:'+RULES_VERSION)).length,4);assert.equal(s.data.cleared.length,0);});
test('selected weapon refuses locked IDs and roundtrip preserves level and prior collections',()=>{const m=memory(),s=new FormalStore(m);assert.equal(s.selectWeapon('duanji'),false);win(s,0);win(s,1);assert.equal(s.selectWeapon('guding'),true);const r=new FormalStore(m);assert.equal(r.loadout().startWeaponId,'guding');assert.equal(r.data.weaponLevels.guding,1);r.data.selectedWeaponId='invalid';assert.equal(r.loadout().startWeaponId,'spear');});
test('corrupt record protected without clean fallback',()=>{const m=memory();m.setItem(FORMAL_KEY,'bad json');const s=new FormalStore(m);assert.equal(s.retry(),false);assert.equal(m.getItem(FORMAL_KEY),'bad json');});
test('partial original-backup write is retained and repaired into a separately verified backup',()=>{const {m,raw}=old(2);let fail=true;const io={getItem:m.getItem,setItem:(k:string,v:string)=>m.setItem(k,fail&&k.endsWith('-campaign20-original')?v.slice(0,19):v)};const s=new FormalStore(io);assert.ok(s.notice);assert.equal(m.getItem(FORMAL_KEY),raw);fail=false;assert.ok(s.retry());assert.equal(m.getItem(FORMAL_KEY+'-campaign20-original'),raw.slice(0,19));assert.equal(m.getItem(String(s.data.migrationBackupKey)),raw);assert.equal(s.data.xp,197);});
