// Explicit legacy-v051 fixture: static gate timing, elite-direct tiers, and old Boss cadence are historical contracts.
// Shipping horde-v06 behavior is tested in horde-v06.test.ts and the 24-run model matrix.
import {test} from 'node:test';import assert from 'node:assert/strict';
import {Journey,STEP,Level} from '../assets/scripts/core/model';import {LEGACY_LEVELS as LEVELS} from '../assets/scripts/core/levels';import {Growth,GROWTH_KEY} from '../assets/scripts/core/growth';import {Book,KEY,defaults} from '../assets/scripts/core/save';import {formation} from '../assets/scripts/VisualConfig';import {CAST,WEAPONS,POOL_LIMITS} from '../assets/scripts/core/weapons';
const level=(v:Partial<Level>={}):Level=>({...LEVELS[0],start:1,duration:100,rows:[],obstacles:[],eliteIds:[],...v});
const foe=(id:number,at:number,hp=100,kind:any='fighter')=>({id,at,x:0,width:.12,kind,hp,loss:1});
function ticks(j:Journey,n:number){const events=[];for(let i=0;i<n;i++){j.advance(STEP);events.push(...j.drainFeedback());}return events;}
const db=()=>{const map=new Map<string,string>();return{map,getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v);}};};
test('near and swept wave share unique attack ledger, tier three hits at most two',()=>{const j=new Journey(level({obstacles:[foe(1,.9),foe(2,1.5),foe(3,1.51)]}));j.tier=3;const e=ticks(j,20).filter(e=>e.attackId===1&&(e.kind==='meleeHit'||e.kind==='waveHit'));assert.deepEqual(e.map(e=>e.targetId),[1,2]);assert.equal(new Set(e.map(e=>e.targetId)).size,e.length);assert.deepEqual(j.obstacles.map(o=>o.hp),[93,93,100]);});
test('rock always blocks; surviving wood blocks; killed wood only passes with spare budget',()=>{for(const kind of ['rock','wood']){const j=new Journey(level({obstacles:[foe(1,1.5,100,kind),foe(2,1.55)]}));j.tier=3;ticks(j,20);assert.equal(j.obstacles[1].hp,100);assert.equal(j.obstacles[0].hp,kind==='rock'?100:93);}const j=new Journey(level({obstacles:[foe(1,1.5,5,'wood'),foe(2,1.55)]}));j.tier=3;ticks(j,20);assert.equal(j.obstacles[0].dead,true);assert.equal(j.obstacles[1].hp,93);});
test('weapon, tier, damage and lane frozen per attack; upgrade cannot retrofit wave',()=>{const j=new Journey(level());ticks(j,1);const a=j.melee!;j.weapon='blade';j.tier=3;j.awakeningRemaining=6;j.move(.8);ticks(j,12);assert.equal(a.weaponId,'spear');assert.equal(a.tier,1);assert.equal(a.damage,5);assert.equal(a.direction,0);assert.equal(j.waves[0].attack,a);});
test('two fixed unique elite kills count once in reverse order, bypass does not upgrade',()=>{const j=new Journey(level({eliteIds:[1,2],obstacles:[foe(2,.9,5),foe(1,1.6,5)]}));const e=ticks(j,70);assert.deepEqual(e.filter(e=>e.kind==='upgrade').map(e=>[e.targetId,e.amount]),[[2,2],[1,3]]);assert.equal(j.tier,3);assert.equal(j.upgradeRewards.size,2);const b=new Journey(level({eliteIds:[1,2],obstacles:[{...foe(1,1,5),x:-.9}]}));b.x=b.target=.9;ticks(b,80);assert.equal(b.tier,1);j.dispose();assert.equal(j.tier,1);});
test('awakening begins on actual hero boss hit, does not retrofit trigger, freezes paused, expires once',()=>{const j=new Journey(level({bossHP:10000}));j.phase='boss';j.bossTicks=60;j.bossDepth=.9;j.tier=3;const e=ticks(j,11);assert.equal(e.find(e=>e.kind==='meleeHit')?.amount,7);assert.equal(j.awakeningUsed,true);assert.equal(j.awakeningRemaining,6);const a=j.melee!;assert.equal(a.damage,7);j.pause();ticks(j,180);assert.equal(j.awakeningRemaining,6);j.resume();ticks(j,26);assert.equal(j.melee?.damage,8.75);ticks(j,365);assert.equal(j.awakeningRemaining,0);assert.equal(j.awakeningUsed,true);assert.ok((j.melee?.damage??7)<=8.75);j.dispose();assert.equal(j.awakeningUsed,false);});
test('N includes companion, bow sources exclude both leaders, one troop stops new ally and bow attacks',()=>{for(const n of [1,2,8,48,256]){const j=new Journey(level({start:n,bossId:'yang_ling'}),{companion:'xing_daorong'});const e=ticks(j,1);assert.equal(j.archerCount,Math.max(n-2,0));assert.equal(j.damage,Math.max(n-2,0)*.2);const units=formation(n,0,j.companionActive);assert.ok(units.length<=48);assert.equal(units.filter(u=>u.hero).length,1);assert.equal(!!j.companionAttack,n>=2);if(n>2)assert.equal(e.find(e=>e.kind==='shot')?.volley?.archerCount,n-2);j.count=1;const later=ticks(j,40);assert.equal(j.companionAttack,null);assert.equal(later.some(e=>e.kind==='shot'),false);assert.equal(later.some(e=>e.kind==='meleeStart'&&e.sourceId!=='hero'),false);}});
test('matching boss stands ally down for that run, selection survives; companion DPS = 20%',()=>{const j=new Journey(level({start:8}),{companion:'xing_daorong'});ticks(j,1);assert.equal(j.companion,null);assert.equal(j.archerCount,7);for(const id of ['xing_daorong','chen_ying','zhao_yun_guest'] as const){const a=new Journey(level({start:8,bossId:'yang_ling'}),{companion:id});ticks(a,1);assert.ok(Math.abs(a.companionAttack!.damage/CAST[id].companionCycle/(5/WEAPONS.spear.cycle)-.2)<1e-9);}});
test('all boss attacks lock direction and hurt only at physical arrival, lateral dodge works',()=>{for(const l of LEVELS)for(const attack of l.bossAttacks){for(const dodge of [false,true]){const j=new Journey(level({...l,start:256,rows:[],obstacles:[],bossHP:100000}));j.phase='boss';j.bossTicks=60;j.bossDepth=.9;j.x=j.target=attack.x??0;(j as any).warn('boss',attack);const w=j.warnings[0],locked=w.x;let sawFlight=false;for(let n=0;n<180&&!w.hit;n++){if(dodge)j.move(locked<=0?.9:-.9);const before=j.count;ticks(j,1);assert.equal(w.x,locked);if(w.stage==='flight'){sawFlight=true;assert.ok(w.projectileZ!>j.z);assert.equal(j.count,before);}if(w.hit){assert.ok(w.projectileZ!<=j.z+1e-8);assert.equal(j.count,dodge?256:256-attack.loss);}}assert.ok(sawFlight);assert.equal(w.hit,true);}}});
test('wave lifetime/cadence has bounded pools without dropping active projectiles; clear on exit',()=>{for(const id of ['xing_daorong','chen_ying','zhao_yun_guest'] as const){const j=new Journey(level({start:2,bossId:'yang_ling'}),{companion:id});ticks(j,1080);assert.ok(j.wavePeak.hero>0&&j.wavePeak.hero<=POOL_LIMITS.hero);assert.ok(j.wavePeak.companion>0&&j.wavePeak.companion<=POOL_LIMITS.companion);j.dispose();assert.equal(j.waves.length,0);}});
test('legacy clears backfill rewards idempotently, selection and unknown save fields survive reload',()=>{const s=db(),base={...defaults(),future:'keep'};base.settings={...base.settings,futureSetting:9} as any;s.setItem(KEY,JSON.stringify(base));const b=new Book(s),g=new Growth(s,b);for(let i=0;i<3;i++){b.win(i,40);g.reconcile();}assert.deepEqual(g.data.unlockedWeapons,['spear','blade']);assert.equal(g.data.unlockedCompanions.length,3);assert.equal(g.data.equippedCompanion,'xing_daorong');g.equipCompanion('chen_ying');g.equipWeapon('blade');g.data.future=42;g.persist();g.reconcile();const re=new Growth(s,new Book(s));assert.equal(re.data.equippedCompanion,'chen_ying');assert.equal(re.data.future,42);assert.equal(re.data.claimedRewards.length,3);assert.equal(JSON.parse(s.getItem(KEY)!).future,'keep');assert.equal(JSON.parse(s.getItem(KEY)!).settings.futureSetting,9);s.setItem(GROWTH_KEY,'bad');assert.equal(new Growth(s,b).data.unlockedCompanions.length,3);});
test('storage failure does not prevent current-session rewards or equipment',()=>{const s={getItem:()=>null,setItem:()=>{throw Error('quota')}};const b=new Book(s),g=new Growth(s,b);b.win(0,8);g.reconcile();assert.equal(g.equipWeapon('blade'),false);assert.equal(g.data.equippedWeapon,'blade');assert.ok(g.notice);});
