import {test} from 'node:test';import assert from 'node:assert/strict';
import {Journey,STEP,Level,Obstacle} from '../assets/scripts/core/model';
import {V06_LEVELS as LEVELS,LEGACY_LEVELS} from '../assets/scripts/core/levels';
import {HordeDirector,sweptTarget,formation} from '../assets/scripts/core/horde';
import {Tactics,TACTICS_KEY,ordinaryBudget} from '../assets/scripts/core/tactics';
import {Book,KEY,defaults} from '../assets/scripts/core/save';
import {steer} from '../tools/v06-model-probe';
const fixture=(start=1):Level=>({...LEVELS[0],start,duration:100,horde:{...LEVELS[0].horde!,runDuration:100,warmup:{...LEVELS[0].horde!.warmup,count:0},forks:[],commonWaves:[]}});
const enemy=(id:number,z:number,x=0,hp=3):Obstacle=>({id,at:z,previousZ:z,x,previousX:x,width:.055,depthRadius:.08,hp,maxHp:hp,kind:'fighter',enemyKind:'footman',ordinary:true,speed:.45,loss:1,lastControlTick:-999,poolSlot:id%64,generation:id});
const ticks=(j:Journey,n:number)=>{const events=[];for(let i=0;i<n;i++){j.advance(STEP);events.push(...j.drainFeedback());}return events;};
test('H01 shipping profile spawns actual planned bodies, counts replacements and reuses bounded slots with unique identities',()=>{assert.ok(LEVELS.every(l=>l.profile==='horde-v06'));assert.ok(LEGACY_LEVELS.every(l=>l.profile==='legacy-v051'));const j=new Journey(LEVELS[2]);const seen=new Set<number>(),slots=new Map<number,Set<number>>();let crossbows=0,runners=0;while(j.phase==='run'){steer(j,'hard');j.advance(STEP);j.drainFeedback();for(const o of j.obstacles){if(seen.has(o.id))continue;seen.add(o.id);crossbows+=+(o.enemyKind==='crossbowman');runners+=+(o.enemyKind==='runner');const s=slots.get(o.poolSlot!)??new Set();s.add(o.id);slots.set(o.poolSlot!,s);}assert.ok(j.stageInfo!.active<=64);assert.ok(j.horde!.pending<=32);assert.ok(j.obstacles.filter(o=>o.dead).length<=16);}assert.equal(j.horde!.spawned,j.horde!.planned);assert.equal(seen.size,j.horde!.spawned);assert.equal(j.horde!.spawnSkipped,0);assert.ok(crossbows>=2&&runners>=4);assert.ok([...slots.values()].some(s=>s.size>1));assert.ok(slots.size<=64);assert.equal(j.horde!.spawned,j.horde!.dead+j.horde!.breached);});
test('H01 overload expires only unborn queue, hard cap and six births per tick; no fictional death credit',()=>{const cfg=structuredClone(LEVELS[0].horde!);cfg.warmup.count=64;cfg.commonWaves=[{id:'pressure',at:1,count:40,kind:'footman',formation:'wide',spawnDepth:6.5}];cfg.forks=[];const os:Obstacle[]=[],h=new HordeDirector(cfg,os);h.before(1,0,1,os);assert.equal(h.spawned,64);assert.equal(h.pending,32);assert.equal(h.spawnSkipped,8);h.before(1,0,75,os);assert.equal(h.pending,0);assert.equal(h.spawnSkipped,40);assert.equal(h.kills,0);assert.equal(h.dead,0);});
test('H02 relative arrow collision hits approaching fast bodies and rejects rounded capsule corners',()=>{const j=new Journey(fixture());const o=enemy(7,1.08,0,10);o.speed=12;j.obstacles=[o];j.arrows=[{x:0,z:.85,damage:2}];j.fireClock=1;ticks(j,1);assert.equal(o.hp,8);assert.ok(o.at<1);const miss={...enemy(8,1),previousZ:1};assert.equal(sweptTarget(.154,1.079,.154,1.079,miss,.10),null);assert.notEqual(sweptTarget(0,.9,0,1.1,miss),null);});
test('H03 route commits once at x zero to right, remains full width, creates chosen-only waves and independent gate',()=>{const j=new Journey(LEVELS[0]);j.z=3.99;j.x=j.target=0;ticks(j,1);const choice=j.horde!.choices[0];assert.equal(choice.side,'right');assert.equal(choice.route,'hard');j.move(-.91);ticks(j,90);assert.ok(j.x<-.9);assert.equal(j.horde!.choices.length,1);assert.ok(j.obstacles.filter(o=>o.routeId?.includes('fork')).every(o=>o.routeId!.endsWith(':hard')));assert.equal(j.rows.length,1);assert.equal(j.usedRows.size,0);assert.ok(j.rows[0].at-4>=2);});
test('H04 exit reward once, paused replay cannot duplicate, zero cannot resurrect, cap remains256',()=>{const j=new Journey(LEVELS[0]);j.horde!.before(4,-.5,1,j.obstacles);assert.equal(j.horde!.exits(13.99,true).length,0);const reward=j.horde!.exits(14,true);assert.equal(reward[0].amount,8);j.pause();j.resume();assert.equal(j.horde!.exits(14,true).length,0);const k=new Journey(LEVELS[0]);k.horde!.before(4,-.5,1,k.obstacles);k.hurt(999,'fixture');assert.equal(k.horde!.exits(14,k.count>0).length,0);assert.equal(k.count,0);const m=new Journey(LEVELS[0]);m.horde!.before(4,-.5,1,m.obstacles);m.count=256;m.obstacles=[];m.z=13.999;const full=ticks(m,1);assert.equal(m.count,256);assert.equal(full.find(e=>e.kind==='gather')?.amount,0);const collision=new Journey(LEVELS[0]);collision.horde!.before(4,-.5,1,collision.obstacles);collision.count=1;collision.z=13.999;collision.fireClock=1;collision.obstacles=[enemy(9,14,0,100)];collision.rows.push({id:777,at:14,left:{kind:'add',value:12},right:{kind:'add',value:12}});const last=ticks(collision,1);assert.equal(collision.phase,'lost');assert.equal(collision.count,0);assert.equal(last.filter(e=>e.kind==='gather').length,0);assert.equal(collision.horde!.choices[0].rewarded,false);});
test('H05 spear and blade hit real multiple targets with shared near/wave ledger and independent special budgets',()=>{for(const weapon of ['spear','blade'] as const){const j=new Journey(fixture(),{weapon,tactic:'guanzhen'});j.obstacles=Array.from({length:8},(_,i)=>enemy(i+1,1.3+i*.22,weapon==='blade'?(i%2)*.14:0));const e=ticks(j,34).filter(e=>e.attackId===1&&(e.kind==='meleeHit'||e.kind==='waveHit'));assert.ok(e.length>=4,weapon+' multi target');assert.equal(new Set(e.map(e=>e.targetId)).size,e.length);assert.ok(e.length<=ordinaryBudget(weapon,1,'guanzhen'));}
 const j=new Journey(fixture());const a=(j as any).newAttack('hero');const wood={...enemy(5,1.5),kind:'wood',enemyKind:undefined,ordinary:false,hp:100} as Obstacle;j.obstacles=[wood];a.specialBudget=0;assert.equal((j as any).attackHit(a,{id:5,z:1.5,kind:'wood'},false),true);assert.equal(wood.hp,100);assert.equal(a.spent,true);
});
test('H05 nearest rock stops moving wave before farther enemy independent of obstacle array order',()=>{const j=new Journey(fixture());const rear=enemy(1,1.8,0,10),rock={id:9,at:1.5,x:0,width:.2,hp:100,kind:'rock',loss:8} as Obstacle;j.obstacles=[rear,rock];ticks(j,25);assert.equal(rear.hp,10);assert.equal(j.horde!.kills,0);});
test('H06 29/79 real deaths upgrade once, old wave tier/damage frozen, elite direct upgrade disabled and retries reset',()=>{for(const initial of [29,79]){const j=new Journey(fixture());j.horde!.kills=initial;j.tier=initial===29?1:2;j.obstacles=[enemy(1,1.3),enemy(2,1.5)];const e=ticks(j,28),a=e.filter(e=>e.attackId===1&&(e.kind==='meleeHit'||e.kind==='waveHit'));assert.equal(j.horde!.kills,initial+2);assert.deepEqual(e.filter(e=>e.kind==='upgrade').map(e=>e.amount),[initial===29?2:3]);assert.equal(j.melee!.tier,initial===29?1:2);assert.equal(j.melee!.damage,initial===29?5:6);assert.equal(a.length,2);(j as any).rewardKill(1);assert.equal(j.horde!.kills,initial+2);}const j=new Journey(fixture());j.level.eliteIds=[1];j.obstacles=[enemy(1,1.3)];ticks(j,25);assert.equal(j.tier,1);assert.equal(new Journey(LEVELS[0]).horde!.kills,0);});
test('H06 all three actual damage sources share one death exit, objects and breached enemies give no kill',()=>{const j=new Journey(fixture(8));const o=enemy(1,.48,0,.5);j.obstacles=[o];const events=ticks(j,1);assert.equal(j.horde!.kills,1);assert.equal(events.filter(e=>e.kind==='break').length,1);assert.equal(j.damageTotals.archer,.5);const k=new Journey(fixture(2),{companion:'chen_ying'});const target=enemy(3,.8,0,.5);k.obstacles=[target];const attack=(k as any).newAttack('chen_ying');(k as any).attackHit(attack,{id:3,z:.8,kind:'fighter'},true);(k as any).rewardKill(3);assert.equal(k.horde!.kills,1);assert.equal(k.damageTotals.companions.chen_ying.melee,.5);});
test('H07 guanzhen changes ordinary budget only; zhenjun hero-only cooldown does not move Boss or strengthen damage',()=>{const j=new Journey(fixture(),{tactic:'zhenjun'});const o=enemy(1,1,0,100);j.obstacles=[o];const a=(j as any).newAttack('hero');(j as any).attackHit(a,{id:1,z:1,kind:'fighter'},false);assert.equal(o.at,1.18);assert.equal(o.slowUntil,12);const hp=o.hp;(j as any).attackHit(a,{id:1,z:1,kind:'fighter'},true);assert.equal(o.hp,hp);j.simulationTick=36;const a2=(j as any).newAttack('hero');(j as any).attackHit(a2,{id:1,z:1.18,kind:'fighter'},false);assert.equal(o.at,1.18);assert.equal(o.slowUntil,12);j.simulationTick=55;const a3=(j as any).newAttack('hero');(j as any).attackHit(a3,{id:1,z:1.18,kind:'fighter'},false);assert.ok(Math.abs(o.at-1.36)<1e-12);assert.equal(o.slowUntil,67);
 const k=new Journey(fixture(2),{tactic:'zhenjun',companion:'chen_ying'}),e=enemy(2,1,0,100);k.obstacles=[e];const ally=(k as any).newAttack('chen_ying');(k as any).attackHit(ally,{id:2,z:1,kind:'fighter'},true);assert.equal(e.at,1);const bow=new Journey(fixture(8),{tactic:'zhenjun'}),body=enemy(5,.46,0,100);bow.obstacles=[body];ticks(bow,1);assert.equal(body.lastControlTick,-999);assert.ok(body.hp<100);assert.ok(body.at<.46);assert.equal(bow.z,STEP);for(const tactic of ['guanzhen','zhenjun'] as const){const b=new Journey(fixture(),{tactic}),attack=(b as any).newAttack('hero');assert.equal(attack.damage,5);assert.equal(attack.specialBudget,1);const before=b.bossHP;(b as any).attackHit(attack,{id:'boss',z:.75,kind:'boss'},false);(b as any).attackHit(attack,{id:'boss',z:.75,kind:'boss'},true);assert.equal(before-b.bossHP,5);}
});
test('H08 collision rolling12tick cap2, each enemy once, breach is not kill and N1 still fails',()=>{for(const count of [1,10]){const j=new Journey(fixture(count));j.fireClock=1;j.obstacles=Array.from({length:6},(_,i)=>enemy(i+1,.001,0,100));ticks(j,1);assert.equal(j.count,Math.max(0,count-2));assert.equal(j.horde!.kills,0);if(count===1)assert.equal(j.phase,'lost');else{assert.equal(j.horde!.breached,6);const before=j.count;ticks(j,5);assert.equal(j.count,before);}}const h=new HordeDirector(fixture().horde!,[]);assert.equal(h.collisionLoss(1,1),1);assert.equal(h.collisionLoss(2,1),1);assert.equal(h.collisionLoss(12,1),0);assert.equal(h.collisionLoss(13,1),1);});
test('H10 isolated tactic key persists selection, corrupt tactic leaves old campaign saves intact and run freezes choice',()=>{const db=new Map<string,string>(),storage={getItem:(k:string)=>db.get(k)??null,setItem:(k:string,v:string)=>{db.set(k,v);}};const saved=defaults();saved.cleared['trial-01']=true;saved.best['trial-01']=99;db.set(KEY,JSON.stringify(saved));const t=new Tactics(storage);t.equip('zhenjun');const j=new Journey(LEVELS[0],{tactic:t.data.equipped});t.equip('guanzhen');assert.equal(j.runTactic,'zhenjun');assert.equal(new Tactics(storage).data.equipped,'guanzhen');db.set(TACTICS_KEY,'{"schemaVersion":1,"equipped":"unknown"}');const corrupt=new Tactics(storage);assert.equal(corrupt.data.equipped,'guanzhen');assert.ok(corrupt.notice);assert.deepEqual(new Book(storage).data,saved);});

test('H01 same-tick mass deaths keep only16 corpses without erasing kill accounting',()=>{const j=new Journey(fixture());j.obstacles=Array.from({length:32},(_,i)=>enemy(i+1,1.5,0,1));const victims=j.obstacles.slice();for(const o of victims){const attack=(j as any).newAttack('hero');(j as any).attackHit(attack,{id:o.id,z:o.at,kind:'fighter'},false);assert.ok(j.obstacles.filter(o=>o.dead).length<=16);}assert.equal(j.horde!.kills,32);assert.equal(j.horde!.dead,32);assert.equal(j.drainFeedback().filter(e=>e.kind==='break').length,32);});
