import test from 'node:test';import assert from 'node:assert/strict';
import {FormalStore,FORMAL_KEY,RULES_VERSION} from '../assets/scripts/formal/store';
import {createBattle} from '../assets/scripts/formal/battle';
import {CHAPTERS,PACING,marchSpeed,TREASURES} from '../assets/scripts/formal/data';
import {steer} from '../tools/ios-steer';
import {combatReviewTarget} from '../assets/scripts/formal/CombatReviewPolicy';
import {configureLegalLoadout} from '../tools/r3-combat/legal-loadout';
const memory=()=>{const d=new Map<string,string>();return{d,getItem:(k:string)=>d.get(k)??null,setItem:(k:string,v:string)=>{d.set(k,v);}}};
const fresh=()=>new FormalStore(memory());
test('empty blade swings cannot freeze world, attack clock or road',()=>{const b=createBattle({chapter:0,lineup:fresh().loadout()}),s=b.state;s.course=[];s.weapon='guandao';s.volleyT=999;for(let i=0;i<120;i++)b.step();assert.ok(Math.abs(s.t-2)<1e-9);assert.ok(Math.abs(s.dist-2*marchSpeed(0))<1e-8);assert.equal(s.hitStop,0);assert.equal(s.shake,0);});
test('impact records actual clamped damage and projectile provenance; no hit after spent',()=>{const b=createBattle({chapter:0,lineup:fresh().loadout()}),s=b.state;s.course=[];s.speed=0;s.show=100;s.volleyT=100;s.ents=[{id:5,type:'enemy',x:0,d:2,hp:1,walk:0,dead:0},{id:6,type:'enemy',x:0,d:3,hp:5,walk:0,dead:0}];s.waves=[{source:'hero',projectileId:77,attackId:'hero:1',x:0,x0:0,z:1,z0:1,speed:160,range:50,t:0,hits:new Set(),pierce:1,dmg:9,hw:.2}];b.step();const hits=b.ledger.filter(r=>r.kind==='damage');assert.equal(hits.length,1);assert.equal(hits[0].amount,1);assert.equal(hits[0].projectileId,77);assert.equal(hits[0].target,5);assert.equal(s.ents[1].hp,5);});
test('mounted movement changes lateral speed only',()=>{const a=createBattle({chapter:0,lineup:fresh().loadout()}),load=fresh().loadout();load.treasures.ma='chitu';const b=createBattle({chapter:0,lineup:load});a.move(.82);b.move(.82);for(let i=0;i<20;i++){a.step();b.step();}assert.equal(a.state.dist,b.state.dist);assert.equal(a.state.atkT,b.state.atkT);assert.ok(b.state.heroX>a.state.heroX);});
test('stationary named-officer encounter cannot inflate a gate',()=>{const b=createBattle({chapter:3,lineup:fresh().loadout()}),s=b.state;s.course=[];s.show=100;s.volleyT=100;s.ents=[{id:1,type:'officer',person:'xu',x:0,d:12,hp:100,max:100,phase:'idle',pt:0,walk:0,dead:0},{id:2,type:'gate',x:0,d:3,val:10,passed:false}];s.waves=[{source:'hero',x:0,x0:0,z:2,z0:2,speed:100,range:50,t:0,hits:new Set(),pierce:1,dmg:9,hw:.2}];b.step();assert.equal(s.encounterStop,true);assert.equal(s.ents[1].val,10);});
test('a gate outside its effective window and a fixed +1 gate cannot consume a wave hit',()=>{for(const obstructingGate of [{id:1,type:'gate',x:0,d:20,val:5,passed:false},{id:1,type:'gate',x:0,d:3,val:1,fixed:true,passed:false}]){const b=createBattle({chapter:0,lineup:fresh().loadout()}),s=b.state;s.course=[];s.speed=0;s.show=100;s.volleyT=100;const target={id:2,type:'enemy',x:0,d:obstructingGate.d+1,hp:5,walk:0,dead:0};s.ents=[obstructingGate,target];s.waves=[{source:'hero',projectileId:100,attackId:'hero:1',x:0,x0:0,z:obstructingGate.d-1,z0:obstructingGate.d-1,speed:180,range:50,t:0,hits:new Set(),pierce:1,dmg:3,hw:.2}];b.step();assert.equal(obstructingGate.val,obstructingGate.fixed?1:5);assert.ok(target.hp<5);assert.equal(b.ledger.filter(r=>r.kind==='gate').length,0);}});
test('new chest treasures enter the collection on victory but not defeat',()=>{const store=fresh();const run={id:'treasure-win',chapter:0,won:true,troops:30,treasures:['qingnang'],defeatedBossId:'jiao',defeatedOfficerIds:[]};assert.equal(store.settle(run),true);assert.ok(store.data.treasures.includes('qingnang'));assert.equal(store.settle({...run,id:'treasure-loss',won:false,treasures:['yuxi']}),true);assert.equal(store.data.treasures.includes('yuxi'),false);});
test('outcome is immutable while the ending animation continues',()=>{const b=createBattle({chapter:0,lineup:fresh().loadout()}),s=b.state;s.ended=true;s.boss={phase:'yield',pt:0,flagFx:[]};s.seal={t:0};const before=b.snapshot();for(let i=0;i<60;i++)b.step();assert.ok(s.boss.pt>.99);assert.equal(s.t,before.t);assert.equal(s.troops,before.troops);assert.equal(b.totals.damage,0);});
test('failed staged save preserves prior bytes, retries once, separates new-rule best',()=>{const m=memory();m.setItem(FORMAL_KEY,JSON.stringify({schemaVersion:3,cleared:[],slots:{dian:null,qi:null,ma:null},xp:0,best:{c01:999},future:{keep:true}}));const original=m.getItem(FORMAL_KEY);let fail=true;const store=new FormalStore({...m,setItem:(k,v)=>{if(k===FORMAL_KEY&&fail)throw Error('disk full');m.setItem(k,v);}});const run={id:'ios-result',chapter:0,won:true,troops:42,treasures:[],defeatedBossId:'jiao',defeatedOfficerIds:[]};assert.equal(store.settle(run),false);assert.equal(m.getItem(FORMAL_KEY),original);assert.equal(m.getItem(FORMAL_KEY+'-previous'),original);assert.equal(store.settle(run),false);assert.equal(store.data.xp,30);fail=false;assert.equal(store.retry(),true);const reload=new FormalStore(m);assert.deepEqual(reload.data.future,{keep:true});assert.equal(reload.data.best.c01,999);assert.equal((reload.data.ruleBests as any)[RULES_VERSION].c01,42);});
test('all twenty legal reference loadouts clear and meet authored chapter timing targets with real warnings, model only',()=>{
 // Each chapter has a static legal reference, independent of player power at runtime.
 // Use only earlier chapter rewards and their earned XP; do not grant the current chapter's equipment.
 const timingDeviations:any[]=[];
 for(let chapter=0;chapter<CHAPTERS.length;chapter++){
  const store=fresh();for(let i=0;i<chapter;i++)assert.equal(store.settle({id:'timing-prior-'+i,chapter:i,won:true,troops:40,treasures:[],defeatedBossId:CHAPTERS[i].boss,defeatedOfficerIds:CHAPTERS[i].enemy}),true);
  configureLegalLoadout(store);assert.ok(store.data.weapons.includes(store.data.selectedWeaponId));
  const b=createBattle({chapter,lineup:store.loadout(),seed:7919}),[minimum,maximum]=CHAPTERS[chapter].targetSeconds!;
  for(let tick=0;tick<300*60&&!b.state.ended;tick++){if(tick%6===0)b.move(combatReviewTarget(b.snapshot(),'normal'));b.step();b.drainAudioEvents();}
  const s=b.state,label='chapter '+(chapter+1);assert.equal(s.ended&&s.troops>0,true,label+' should clear with prior rewards only');
  // R3 Bosses have distinct authored sequences. Measure real target deviations instead of pretending every weapon/route shares the old 25–45s window.
  assert.ok(s.timing.boss>0&&s.timing.boss<180,label+' finite actual Boss encounter');
  assert.ok(Math.abs(s.t-(s.timing.march+s.timing.officer+s.timing.boss))<.05,label+' timing must account for every active tick');
  console.log(JSON.stringify({chapter:chapter+1,weapon:store.data.selectedWeaponId,level:store.data.weaponLevels[store.data.selectedWeaponId],seconds:s.t,timing:s.timing,target:[minimum,maximum],targetMet:s.t>=minimum&&s.t<=maximum}));
  if(s.t<minimum||s.t>maximum)timingDeviations.push({chapter:chapter+1,seconds:s.t,target:[minimum,maximum]});
  assert.ok(s.timing.march>=PACING.marchSeconds[chapter]-.1,label+' march prematurely skipped');
  assert.equal(store.settle({id:'natural-model-'+chapter,chapter,won:true,troops:s.troops,treasures:s.runGot,defeatedBossId:s.defeatedBossId,defeatedOfficerIds:s.defeatedOfficerIds}),true,label+' must legitimately settle');
 }
 // A successful clear is separate from the unchanged authored pacing requirement.
 // Keep unmet timing goals red rather than turning their assertions into logging.
 assert.deepEqual(timingDeviations,[],'authored chapter timing goals remain required');
});
test('fixed-step simulation stays identical under 30, 60 and 120 Hz render schedules',()=>{const snapshots=[];for(const hz of [30,60,120]){const b=createBattle({chapter:0,lineup:fresh().loadout()});let acc=0,tick=0;for(let frame=0;frame<hz*20;frame++){acc+=1/hz;while(acc+1e-10>=1/60){if(tick%6===0)b.move(steer(b.snapshot()));b.step();tick++;acc-=1/60;}}snapshots.push(b.snapshot());}assert.deepEqual(snapshots[0],snapshots[1]);assert.deepEqual(snapshots[1],snapshots[2]);});
test('companion identity selects an actual distinct weapon waveform and hit provenance',()=>{const keys=new Set();for(const id of ['guan','huang','liao','jiang']){const load=fresh().loadout();load.companions=[id];const b=createBattle({chapter:0,lineup:load});b.state.course=[];b.state.show=999;b.state.volleyT=999;for(let i=0;i<90;i++)b.step();const w=b.state.waves.find(w=>w.source==='companion:'+id);assert.ok(w,id);assert.match(w.attackId,new RegExp('^companion:'+id+':'));keys.add(w.k);}assert.equal(keys.size,4);});
test('volley damage labels aggregate actual values without merging the hit ledger',()=>{const b=createBattle({chapter:0,lineup:fresh().loadout()}),s=b.state;s.course=[];s.dist=s.courseLen+6;b.step();s.ents=[];s.waves=[];s.show=999;s.volleyT=999;s.boss.phase='rec';s.boss.hp=100;s.fx=[];s.arrows=[1,2].map(id=>({projectileId:id,source:'troop',attackId:'volley:1',sx:0,sz:0,tx:0,tz:s.boss.z,t:0,dur:.001,arms:'bow',dmg:1.5,splash:0,target:'boss'}));b.step();const hits=b.ledger.filter(e=>e.kind==='damage');assert.equal(hits.length,2);const labels=s.fx.filter(f=>f.k==='crit');assert.equal(labels.length,1);assert.ok(Math.abs(labels[0].v-hits.reduce((n,h)=>n+h.amount,0))<1e-9);});
