import {test} from 'node:test';import assert from 'node:assert/strict';
import {Journey,STEP,BOSS_TARGET,Level} from '../assets/scripts/core/model';
import {Journey as V03} from './fixtures/v03-model';
import {Journey as S1} from './fixtures/s1-model';
import {LEVELS} from '../assets/scripts/core/levels';
import {lossLabel,bossFootprint,Effects} from '../assets/scripts/Presentation';
// S1 fixture is byte-for-byte git show 184f974:assets/scripts/core/model.ts.
const state=(g:Journey|S1)=>({phase:g.phase,count:g.count,x:g.x,target:g.target,z:g.z,elapsed:g.elapsed,bossHP:g.bossHP,bossClock:g.bossClock,bossReady:g.bossReady,bossIndex:g.bossIndex,arrows:g.arrows.map(({x,z,damage})=>({x,z,damage})),warnings:g.warnings,obstacles:g.obstacles,usedRows:[...g.usedRows],cause:g.cause,fireClock:g.fireClock,accumulator:g.accumulator});
function input(g:S1,mode:string){if(g.phase==='boss'){if(mode==='failure')return g.bossWarning?.x??.8;const w=g.bossWarning;return w&&!w.hit&&Math.abs(w.x)<=w.width?(w.x<=0?.78:-.78):0;}const r=g.level.rows.find(r=>!g.usedRows.has(r.id)&&r.at-g.z<=7);let x=0;if(r){x=r.left.kind==='double'?(g.count>=r.right.value?-.5:.5):(r.left.value>=g.count?-.5:.5);const guard=g.obstacles.find(o=>o.rowId===r.id&&!o.dead);if(mode==='late'&&guard&&r.at-g.z>1.2)x=guard.side==='left'?.5:-.5;}const o=g.obstacles.find(o=>!o.dead&&!o.resolved&&o.rowId===undefined&&o.at-g.z<1&&o.at>g.z&&Math.abs(o.x-x)<=o.width);if(o)x=o.x<=0?.8:-.8;const w=g.warnings.find(w=>!w.hit&&Math.abs(x-w.x)<=w.width);if(w)x=w.x<=0?.8:-.8;return mode==='failure'?.8:x;}
// v04 intentionally changes damage and boss depth. The archived v03/S1 fixtures
// remain historical; check presentation non-interference against a clean v04 run.
for(const level of LEVELS)for(const mode of ['best','late','failure'])test(`v04 presentation is read-only: ${level.id}/${mode}`,()=>{const a=new Journey(level),b=new Journey(level),fx=new Effects();let compared=0;while(!a.finished&&compared<60*400){const x=input(a as any,mode);a.move(x);b.move(x);a.advance(STEP);b.advance(STEP);const expected=a.drainFeedback(),events=b.drainFeedback();fx.accept(events,b.elapsed);fx.advance(b.elapsed);assert.deepEqual(events,expected);assert.deepEqual(state(b),state(a),`tick ${compared}`);assert.deepEqual(b.melee,a.melee);assert.equal(b.bossDepth,a.bossDepth);compared++;}assert.ok(a.finished);});
test('S2 rock loss is data-driven, including actual loss when insufficient troops',()=>{assert.equal(lossLabel({kind:'rock',loss:17}),'山石 · 碰撞 −17');assert.equal(lossLabel({kind:'rock',loss:2}),'山石 · 碰撞 −2');const g=new Journey(LEVELS[0]);g.hurt(17,'撞上山石');assert.equal(g.drainFeedback()[0].amount,8);});
test('S2 shared boss target and hit events at center/edges/outside',()=>{assert.equal(BOSS_TARGET.halfWidth,.42);assert.equal(bossFootprint(),161.616);assert.ok(Object.isFrozen(BOSS_TARGET));for(const x of [0,-.41,.41,-.43,.43]){const g=new Journey({...LEVELS[0],duration:0,rows:[],obstacles:[]});g.advance(STEP);g.x=x;g.target=x;g.arrows=[{id:77,x,z:3.99,damage:2}];g.fireClock=1;const hp=g.bossHP;g.advance(STEP);const hit=g.drainFeedback().find(e=>e.kind==='hit');assert.equal(hp-g.bossHP,Math.abs(x)<=.42?2:0);if(hit){assert.equal(hit.projectileId,77);assert.equal(hit.targetId,'boss');assert.equal(hit.worldZ,g.z+g.bossDepth);assert.equal(hit.x,x);assert.ok(Object.isFrozen(hit));}}});
test('S2 event metadata identifies arrow, target and tick without driving gameplay',()=>{const g=new Journey({...LEVELS[0],rows:[],duration:20,obstacles:[{id:99,at:1,x:0,width:.2,hp:1,kind:'wood',loss:8}]});const all=[];for(let i=0;i<30;i++){g.advance(STEP);all.push(...g.drainFeedback());}const shot=all.find(e=>e.kind==='shot')!,hit=all.find(e=>e.kind==='hit')!,broken=all.find(e=>e.kind==='break')!;assert.equal(hit.projectileId,shot.projectileId);assert.equal(hit.targetId,99);assert.equal(hit.worldZ,1);assert.equal(hit.simulationTick,broken.simulationTick);assert.ok(g.obstacles[0].dead);const fx=new Effects();for(let i=0;i<100;i++)fx.accept(all,0);assert.ok(fx.items.length<=64);fx.advance(1);assert.equal(fx.items.length,0);fx.clear();assert.equal(fx.lastShot,-10);});
