import {armySlots} from '../assets/scripts/formal/presentation';
import test from 'node:test';import assert from 'node:assert/strict';import {createBattle} from '../assets/scripts/formal/battle';import {FormalStore} from '../assets/scripts/formal/store';import {CHAPTERS,BOSS_PATTERNS,routeFor} from '../assets/scripts/formal/data';import {EncounterDirector} from '../assets/scripts/formal/EncounterDirector';
function make(kind?:string,extra:any={}){const store=new FormalStore({getItem:()=>null,setItem:()=>{}}),b=createBattle({chapter:15,lineup:{...store.loadout(),companions:[],support:null},seed:71,diagnostic:true,noFriendlyFire:true,...extra}),s=b.state;if(kind){s.course=[{d:62,type:'squad',x:s.heroX+.23,n:1,enemyKind:kind}];s.ci=0;}return b;}
function ticks(b:any,n:number){for(let i=0;i<n&&!b.state.ended;i++)b.step();}
test('seven enemies traverse normal route prefetch instead of elite z>40 removal',()=>{for(const kind of ['light','guard','shield','archer','cavalry','banner','mechanism']){const b=make(kind);ticks(b,2400);const life=b.snapshot().enemyLifecycle[0];assert.ok(life,kind);for(const stage of ['planned','spawned','visible','acquired','warn','release','impact'])assert.ok(life.events.some(e=>e.stage===stage),kind+' '+stage);assert.ok(life.events[1].z>40);for(const e of life.events.filter(e=>e.stage==='despawnReason'))assert.ok(['passed-rear-boundary','death-animation-complete'].includes(e.reason));}});
test('melee never applies damage from z18 and contact release does not kill itself',()=>{for(const kind of ['light','guard','shield','banner']){const b=make(kind),s=b.state;s.course=[{d:18,type:'squad',x:s.heroX+.23,n:1,enemyKind:kind}];s.ci=0;ticks(b,30);assert.equal(s.damageHistory.length,0);ticks(b,600);const life=b.snapshot().enemyLifecycle[0];assert.ok(life.events.some(e=>e.stage==='release'));assert.ok(!life.events.some(e=>e.stage==='death'));}});
test('released arrows retain source origin and immutable aim when archer dies',()=>{const b=make('archer'),s=b.state;for(let i=0;i<1400&&!s.hostileShots.length;i++)b.step();assert.ok(s.hostileShots.length);const shot=s.hostileShots[0],origin={...shot.origin},locked={...shot.lockedTarget},e=s.ents.find(e=>e.id===shot.sourceEnemyId);assert.equal(origin.x,e.x);e.hp=0;e.dead=.01;b.move(.68);ticks(b,10);assert.deepEqual(shot.lockedTarget,locked);assert.ok(shot.t>0);assert.ok(b.snapshot().telegraphs.some(t=>t.id===shot.attackId));});
test('firing source killed before release cancels its uncommitted warning',()=>{const b=make('archer'),s=b.state;for(let i=0;i<1400&&!s.ents.some(e=>e.phase==='warn');i++)b.step();const e=s.ents.find(e=>e.phase==='warn');assert.ok(e);e.hp=0;e.dead=.01;ticks(b,120);assert.equal(s.hostileShots.length,0);assert.ok(!b.snapshot().telegraphs.some(t=>t.source==='enemy:'+e.id));});
test('crowded wave reservation never consumes heads without spawn accounting',()=>{const b=make('guard'),s=b.state;s.course=[{d:62,type:'squad',x:0,n:100,enemyKind:'guard'}];s.ci=0;ticks(b,3);const q=b.snapshot();assert.equal(q.waveAccounting[0].planned,100);assert.equal(q.waveAccounting[0].spawned+q.pendingSquads[0].remaining,100);assert.equal(q.waveAccounting[0].deferredReason,'active-enemy-budget');assert.ok(q.entities.length<=56);});
test('threat director holds released attack budget until last impact',()=>{const d=new EncounterDirector(),t=d.schedule({id:'a',source:'archer',kind:'archer',now:0,warning:1.2,bands:[[-.1,.1]],x:0,speed:3,halfWidth:.2,bounds:[-.68,.68],maxThreats:1,duration:2});assert.ok(t);t.released=true;d.cancel('archer');d.prune(2);assert.equal(d.active.length,1);d.prune(3.3);assert.equal(d.active.length,0);});
test('every chapter after two has ordinary archers and every boss has explicit sequence',()=>{for(let i=0;i<20;i++){const p=BOSS_PATTERNS[CHAPTERS[i].boss];assert.ok(p?.sequence.length,CHAPTERS[i].id);if(i>=2)assert.ok(routeFor(i,['spear'],[]).some(e=>e.enemyKind==='archer'),CHAPTERS[i].id);}});
test('boss complete absorption has no hit/shake feedback',()=>{const b=make(),s=b.state;s.course=[];s.ents=[];s.speed=0;s.slots.qi.id='huxinjing';s.boss={person:'jiao',name:'张角',hp:100,max:100,trail:100,phase:'idle',pt:0,band:[-.5,.5],z:17,hit:0,flags:4,flagFx:[],cycleN:0};s.minT=1e5;s.heroX=s.targetX=0;s.waves=[{boss:true,attackId:'absorbed',band:[-.5,.5],damage:2,x:0,z:.1,z0:17,speed:-40,t:0,hits:new Set(),range:99}];b.step();assert.equal(Math.abs(s.damageHistory[0].actual),0);assert.equal(s.troops,30);assert.equal(s.stats.hitTaken,0);assert.equal(s.redFlash,0);assert.equal(s.shake,0);assert.ok(!b.drainAudioEvents().some(e=>e.phase==='hurt'));});
test('chapter20 phase change preserves released ordinary arrow and its budget',()=>{const b=make(undefined,{chapter:19}),s=b.state;s.course=[];s.ents=[];s.speed=0;s.boss={person:'lukang',name:'陆抗',hp:70,max:100,trail:70,phase:'idle',pt:0,band:[-.5,.5],z:2,hit:0,flags:4,flagFx:[],cycleN:0};s.minT=1e5;const t={id:'released',source:'enemy:88',kind:'archer',created:0,execute:0,end:2,bands:[[-.1,.1]],wasThreatened:true,released:true};const arrow={source:'released',attackId:'released',subAttackId:0,sourceEnemyId:88,kind:'archer',x:0,z:10,origin:{x:0,z:10},lockedTarget:{x:0,z:-.3},duration:1,t:0,damage:2,telegraph:t,done:false};s.hostileShots=[arrow];s.waves=[{projectileId:1,attackId:'hero:test',source:'hero',weaponId:'spear',x:0,x0:0,z:1,z0:1,speed:100,range:10,t:0,hits:new Set(),pierce:1,dmg:50,hw:.2}];b.step();assert.equal(s.boss.campaignPhase,1);assert.ok(s.hostileShots.includes(arrow));assert.ok(arrow.t>0);});
test('arrow crossing a full team within one tick is swept once',()=>{const b=make(),s=b.state;s.course=[];s.ents=[];s.speed=0;s.heroX=s.targetX=0;const t={id:'fast',source:'enemy:1',kind:'archer',created:0,execute:0,end:1,bands:[[-.1,.1]],wasThreatened:true,released:true};s.hostileShots=[{source:'fast',attackId:'fast',subAttackId:0,sourceEnemyId:1,kind:'archer',x:0,z:10,origin:{x:0,z:10},lockedTarget:{x:0,z:-3},duration:.001,t:0,damage:2,telegraph:t,done:false}];b.step();assert.equal(s.troops,27);ticks(b,20);assert.equal(s.troops,27);assert.equal(s.damageHistory.length,1);});

test('officer full absorption does not flash red',()=>{const store=new FormalStore({getItem:()=>null,setItem:()=>{}}),b=make(undefined,{chapter:0,lineup:{...store.loadout(),weapons:['spear','dundao'],startWeaponId:'dundao'}}),s=b.state;s.course=[];s.speed=0;s.slots.qi.id='huxinjing';s.ents=[{id:77,type:'officer',person:'xu',x:s.heroX,d:12,hp:100,max:100,walk:0,dead:0,phase:'warn',pt:0,band:[-.6,-.3],telegraph:{id:'officer:block',execute:0,bands:[[-.6,-.3]]}}];b.step();assert.equal(Math.abs(s.damageHistory[0].actual),0);assert.equal(s.troops,30);assert.equal(s.redFlash,0);assert.ok(!b.drainAudioEvents().some(e=>e.phase==='hurt'));});
test('actual army and companion foot envelopes cover 1/50/150/300 troops at both edges and both current/next wall sides',()=>{
 for(const troops of [1,50,150,300])for(const x of [-.68,0,.68])for(const side of [-1,0,1])for(const future of [false,true]){
  const b=make(),s=b.state;s.course=[];s.troops=troops;s.heroX=s.targetX=x;s.companions=[{id:'lubu',dx:.34},{id:'machao',dx:-.34}];s.ents=side?[{id:90,type:'wall',x:0,d:future?5:0,len:20,side}]:[];
  const q=b.snapshot(),env=future?q.teamEnvelopeFuture:q.teamEnvelope;if(side&&future)assert.ok(env.future.length>0);for(const foot of [...env.current,...env.future])assert.ok(Math.abs(foot.x-q.x)+env.bodyRadius<=env.halfWidth+1e-10,JSON.stringify({troops,x,side,future,foot,env}));
  if(side&&!future){const expected=armySlots(troops,x,side);assert.deepEqual(q.teamFeet.filter(p=>p.role==='soldier').map(({x,z,row})=>({x,z,row})),expected);}
 }
});
test('scheduled warning covers upcoming wall feet through flight deadline and keeps released arrows committed',()=>{
 const b=make('archer'),s=b.state;s.troops=1;s.heroX=s.targetX=-.45;s.course=[];s.speed=5;s.ents=[{id:91,type:'wall',d:8,len:20,side:1},{id:92,type:'enemy',enemyKind:'archer',x:-.4,d:20,hp:100,phase:'idle',pt:10,walk:0,dead:0,visibleAt:.001}];
 b.step();const t=b.snapshot().telegraphs[0];if(t){assert.ok(t.footprint.future.length>0);for(const p of [...t.footprint.current,...t.footprint.future])assert.ok(Math.abs(p.x-t.footprint.centre)+t.footprint.bodyRadius<=t.footprint.halfWidth+1e-10);assert.ok(t.end>t.execute+.3);}
 else assert.ok(b.snapshot().director.deferred>0,'unsafe wall layout must defer instead of promising an unsafe warning');
});

import {formationFeet,formationSafety,footAtRisk} from '../assets/scripts/formal/CombatFootprint';
test('trajectory risk uses actual threatened feet; 300 rear troops cannot suppress a readable arrow',()=>{
 const r:any={shape:'segment',bands:[[-.13,.13]],zMin:-.66,zMax:20.36,width:.09,origin:{x:0,z:20},target:{x:0,z:-.3},wallSides:[0]};
 for(const n of [1,50,150,300])for(const sides of [[0],[-1],[1],[0,-1],[0,1]]){
  const risk={...r,wallSides:sides},proof=formationSafety(0,0,1.2,3,[-.68,.68],n,2,[risk]);assert.ok(proof.safe,JSON.stringify({n,sides}));
  for(const [lo,hi] of proof.intervals)for(const x of [lo,(lo+hi)/2,hi])for(const side of sides)assert.ok(formationFeet(n,2,x,side).every(p=>!footAtRisk(p,risk)),JSON.stringify({n,sides,x}));
  assert.ok(formationFeet(n,2,0).filter(p=>p.role==='soldier').every(p=>!footAtRisk(p,risk)),'arrow ends ahead of rear ranks');
 }
 const b=make(),s=b.state;s.course=[];s.speed=0;s.troops=300;s.companions=[{id:'lubu'},{id:'machao'}];s.ents=[{id:301,type:'enemy',enemyKind:'archer',x:0,d:20,hp:100,phase:'idle',pt:10,walk:0,dead:0,visibleAt:.001}];for(let i=0;i<200&&!s.hostileShots.length;i++)b.step();assert.ok(b.snapshot().enemyLifecycle[0].events.some(e=>e.stage==='release'));assert.equal(s.hostileShots[0]?.telegraph.riskFootprint.shape,'segment');
});
test('near-rear melee risk includes every army foot its depth can actually reach',()=>{
 for(const n of [1,50,150,300])for(const side of [-1,0,1]){const feet=formationFeet(n,2,.45,side),risk:any={shape:'depth-band',bands:[[.3,.6]],zMin:-2.3,zMax:0,width:.11,wallSides:[side]},proof=formationSafety(.45,0,1.2,3,[-.68,.68],n,2,[risk]);for(const [l,r] of proof.intervals)for(const x of [l,(l+r)/2,r])assert.ok(formationFeet(n,2,x,side).every(p=>!footAtRisk(p,risk)));assert.ok(feet.some(p=>p.role==='soldier'&&p.z>=risk.zMin));}
});
test('Boss wave sweeps real companion depth once and never inflicts phantom rear-band damage',()=>{
 const b=make(),s=b.state;s.course=[];s.ents=[];s.speed=0;s.troops=300;s.heroX=s.targetX=-.68;s.companions=[{id:'zhao',dx:0}];s.boss={person:'jiao',name:'张角',hp:100,max:100,trail:100,phase:'rec',pt:0,band:[-.5,-.35],z:17,hit:0,flags:4,flagFx:[],cycleN:0};s.minT=1e5;s.waves=[{boss:true,attackId:'companion',band:[-.5,-.35],damage:2,x:-.42,z:4.5,z0:17,speed:-40,t:0,hits:new Set(),range:99}];ticks(b,5);assert.equal(s.damageHistory.length,1);ticks(b,20);assert.equal(s.damageHistory.length,1);
 s.waves=[{boss:true,attackId:'rear-phantom',band:[.4,.6],damage:2,x:.5,z:.1,z0:17,speed:-40,t:0,hits:new Set(),range:99}];b.step();assert.equal(s.damageHistory.length,1,'rear army x cannot hit after beam ends before army z');
});
test('entering Boss preserves released arrow budget and queues six guards under sprite cap',()=>{
 const b=make('archer'),s=b.state;s.course=[];s.courseLen=1;s.dist=10000;s.speed=0;s.defeatedOfficerIds=CHAPTERS[15].officers||[];
 // Required officers use the actual authored IDs, without erasing committed ordinary projectiles.
 s.defeatedOfficerIds=[...CHAPTERS[15].enemy];
 s.ents=Array.from({length:56},(_,i)=>({id:500+i,type:'enemy',enemyKind:'guard',x:0,d:s.dist+50,hp:100,dead:0,phase:'approach',walk:0}));
 // Acquire a real warning first through the regular director, then transition at the end of the course.
 s.state='general';s.ents[0]={id:500,type:'enemy',enemyKind:'archer',x:s.heroX,d:s.dist+20,hp:100,dead:0,phase:'idle',pt:10,walk:0,visibleAt:.001};for(let i=0;i<200&&!s.hostileShots.length;i++)b.step();assert.ok(s.hostileShots.length);const arrow=s.hostileShots[0];s.state='run';b.step();assert.ok(s.boss);assert.ok(s.hostileShots.includes(arrow));assert.ok(b.snapshot().telegraphs.some(t=>t.id===arrow.attackId&&t.released));assert.ok(s.ents.filter(e=>e.type==='enemy'&&!e.dead).length<=56);assert.equal(s.pendingBossGuards.length,6);assert.ok(b.snapshot().waveAccounting.some(w=>w.waveId.includes(':opening')&&w.planned===6&&w.spawned===0));
 s.ents[1].dead=.01;ticks(b,1);assert.equal(s.pendingBossGuards.length,5);assert.ok(s.ents.filter(e=>e.type==='enemy'&&!e.dead).length<=56);
});

 test('charging cavalry snapshot remains serializable without exposing the entity/charge cycle',()=>{const b=createBattle({chapter:15,lineup:new FormalStore({getItem:()=>null,setItem:()=>{}}).loadout(),seed:71}),s=b.state;const e:any={id:991,type:'enemy',enemyKind:'cavalry',x:0,d:8,hp:4,walk:0,dead:0},shot:any={attackId:'cavalry:991',subAttackId:0,x:0,z:8,origin:{x:0,z:8},lockedTarget:{x:0,z:-.3},entity:e,done:false};e.charge=shot;s.ents=[e];s.hostileShots=[shot];assert.doesNotThrow(()=>JSON.stringify(b.snapshot()));assert.equal(b.snapshot().entities[0].charge.attackId,'cavalry:991');assert.equal(e.charge.entity,e,'live charge ownership is unchanged');});
