import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Journey,Level,STEP} from '../assets/scripts/core/model';
import {LEVELS,V07_LEVELS} from '../assets/scripts/core/levels';
import {runnerFormation,sweptRect,RunnerObject,Enemy,Shot} from '../assets/scripts/core/runner';
import {RUNNER_RULES} from '../assets/scripts/core/runnerConfig';
import {Book,KEY,defaults} from '../assets/scripts/core/save';
import {Growth} from '../assets/scripts/core/growth';
import {runnerSteer} from '../tools/v09-model-policy';
const fixture=(objects:RunnerObject[]=[],count=1)=>new Journey({...LEVELS[0],duration:100,start:count,runner:{...LEVELS[0].runner!,routeEnd:100,startCount:count,objects,enemyWaves:[],objective:{kind:'clearEnemies',plannedEnemyCount:0}}});
const gate=(id='gate',at=3,x=0,value=-5,halfWidth=.18):RunnerObject=>({id,kind:'mutableGate',at,x,value,halfWidth,damagePerPoint:2,maxPositive:64});
const crate=(id='crate',at=3,x=0,hp=60):RunnerObject=>({id,kind:'rewardCrate',at,x,hp,halfWidth:.18,reward:{kind:'troops',count:3}});
const tick=(j:Journey,n=1)=>{for(let i=0;i<n&&!j.finished;i++){j.advance(STEP);j.drainFeedback();}};
const enemy=(id='enemy',x=0,z=3,hp=10):Enemy=>({id,numericId:200,slot:0,x,at:z,previousX:x,previousZ:z,hp,maxHp:hp,speed:0,halfWidth:.06,depth:.08,large:false,dead:false,lastHit:-100,attackClock:.8,contacting:false});
const shot=(x:number,z:number,damage=1,stage=0):Shot=>({id:500,x,z,previousZ:z,damage,stage,speed:9,range:8,splash:stage===2?.16:0,spent:false,origin:Object.freeze({x,z,damage,stage,owner:0,tick:0,direction:0,role:'hero'})});

test('V2 01 signed damage thresholds carry fractions through -5, zero and +3',()=>{const j=fixture([gate()]),r=j.runner!,t=r.targets[0];for(let i=0;i<15;i++)r.hitTarget(t,1);assert.equal(t.value,2);assert.equal(t.progress,1);r.hitTarget(t,1);assert.equal(t.value,3);assert.equal(t.resolved,false);assert.equal(r.stats.converted,1);assert.equal(j.count,1);});
test('V2 02 60 HP is exactly 3 troops, unopened crate grants nothing and cannot repeat',()=>{const j=fixture([crate()]),r=j.runner!,t=r.targets[0];r.hitTarget(t,59);assert.equal(j.count,1);r.hitTarget(t,1);assert.equal(j.count,4);r.hitTarget(t,100);assert.equal(j.count,4);assert.equal(r.kills,0);const missed=fixture([crate('miss',.01,.8)]);tick(missed,30);assert.equal(missed.count,1);assert.equal(missed.runner!.stats.missed,1);});
test('V2 03 weighted emitters preserve the budget at 1, 7, 48 and 256; special units count once',()=>{for(const count of [1,7,48,256])for(const companion of [false,true]){const members=runnerFormation(count,.9,0,companion);assert.equal(members.length,Math.min(48,count));assert.equal(members.reduce((n,m)=>n+m.weight,0),count);assert.equal(members[0].weight,1);assert.ok(members.every(m=>Math.abs(m.x)<=1.16));}});
test('V2 04 emitted arrows retain launch positions, owners, damage and stage through movement/upgrades',()=>{const j=fixture([],7);tick(j);const s=j.runner!.shots.map(s=>({...s}));assert.equal(s.length,7);assert.ok(new Set(s.map(s=>s.x)).size>1);const origin=s[0].origin;j.runner!.stage=2;j.move(.9);tick(j,4);const same=j.runner!.shots.find(t=>t.id===s[0].id)!;assert.equal(same.x,s[0].x);assert.equal(same.stage,0);assert.equal(same.damage,1);assert.equal(same.origin,origin);assert.ok(Object.isFrozen(origin));});
test('V2 05 different emitters hit independent columns; nearest crate consumes a shot before rear enemy',()=>{const j=fixture([crate('left',.2,-.2,1),crate('right',.2,.2,1)]),r=j.runner!;r.shots=[shot(-.2,.1),{...shot(.2,.1),id:501}];r.enemies=[enemy('rear',-.2,.35,8)];tick(j);assert.equal(r.stats.crates,2);assert.equal(r.enemies[0].hp,8);assert.equal(j.count,7);});
test('V2 06 true feet union can touch a negative gate outside center; independent doors settle once',()=>{const j=fixture([gate('edge',-.64,.17,-2,.06)],7);j.runner!.targets[0].damagePerPoint=1000;tick(j);assert.equal(j.count,5);assert.equal(j.runner!.lastDamage?.sourceId,'edge');tick(j,3);assert.equal(j.count,5);const both=fixture([gate('a',-.64,-.17,1,.025),gate('b',-.64,.17,2,.025)],7);tick(both);assert.equal(both.count,10);assert.equal(both.runner!.stats.gatesTaken,2);});
test('V2 07 TOI precedes IDs; zero ends the step and new members cannot retroactively collide',()=>{const j=fixture([gate('a-death',.01,0,-99),gate('b-revive',.01,0,12)]);tick(j);assert.equal(j.phase,'lost');assert.equal(j.count,0);assert.equal(j.runner!.targets[1].triggered,false);const grow=fixture([gate('grow',.01,0,6,.03),gate('edge',-.64,.17,-4,.02)]);tick(grow);assert.equal(grow.count,7);assert.equal(grow.runner!.targets[1].triggered,false);tick(grow);assert.equal(grow.count,3);});
test('V2 08 swept round feet do not collide through empty AABB corner; crossing cannot tunnel',()=>{assert.equal(sweptRect(0,0,0,0,.03,.1,.03,.1,.025),null);assert.ok(sweptRect(-1,0,1,0,-.02,.02,-.02,.02,.025)!==null);});
test('V2 09 chain creates 6 independent tokens ahead; crossing only three grants three and misses never replay',()=>{const t=crate();t.kind='chainCrate';t.hp=1;t.reward={kind:'chain',count:6,spacing:.5};const j=fixture([t]);j.runner!.hitTarget(j.runner!.targets[0],1);tick(j);const r=j.runner!,tokens=r.targets.filter(t=>t.kind==='token');assert.equal(tokens.length,6);assert.ok(tokens[0].at-j.z>=1.4);for(const t of tokens)r.hitTarget(t,999);assert.ok(tokens.every(t=>t.value===1));while(j.z<4.1)tick(j);assert.equal(r.stats.chainTaken,3);j.x=j.target=.9;tick(j,180);assert.equal(r.stats.chainTaken,3);assert.equal(j.count,4);assert.equal(r.stats.chainGenerated,6);assert.ok(r.stats.missed>=3);});
test('V2 10 troops do not upgrade, absolute equipment only advances; kills/elite/tactics never activate old systems',()=>{const j=fixture([crate()]),r=j.runner!;r.hitTarget(r.targets[0],60);assert.equal(r.stage,0);const equipment=crate('weapon');equipment.reward={kind:'equipment',stage:2};const k=fixture([equipment]);k.runner!.hitTarget(k.runner!.targets[0],60);assert.equal(k.tier,3);k.runner!.enemies=[enemy('elite',0,.18,.1)];k.runner!.kills=79;k.runner!.shots=[shot(0,.1,1)];tick(k);assert.equal(k.runner!.kills,80);assert.equal(k.tier,3);assert.equal(k.awakeningUsed,false);assert.equal(k.melee,null);assert.equal(k.waves.length,0);assert.equal(k.horde,null);assert.equal(k.rows.length,0);});
test('V2 11 blast damages each enemy once, never changes nearby gate or crate',()=>{const j=fixture([gate('near',3.26,.12,-5,.03),crate('off-axis',3.26,-.12)]),r=j.runner!;r.enemies=[enemy('front',0,3.22,10),enemy('nearby',.03,3.24,10)];r.shots=[shot(0,3.1,2.5,2)];(r as any).fireAt.set(0,100);tick(j);assert.equal(r.enemies[0].hp,7.5);assert.equal(r.enemies[1].hp,7.5);assert.equal(r.targets[0].value,-5);assert.equal(r.targets[1].hp,60);});
test('V2 12 forward divider absorbs crossing arrows while lateral player control remains open',()=>{const level={...LEVELS[1],runner:{...LEVELS[1].runner!,startCount:1,enemyWaves:[],objects:[],objective:{kind:'clearEnemies',plannedEnemyCount:0}}} as Level;const j=new Journey(level);j.z=12;j.runner!.shots=[shot(0,13.4,1)];tick(j);assert.equal(j.runner!.stats.blocked,1);j.move(.85);tick(j,45);assert.ok(j.x>.84);assert.equal(j.horde,null);});
test('V2 13 live enemies behind the formation pursue without teleport or breach kill credit',()=>{const j=fixture(),r=j.runner!;r.enemies=[enemy('behind',.8,-1,1000)];tick(j);assert.equal(r.enemies[0].dead,false);assert.ok(r.enemies[0].at>-1&&r.enemies[0].at<=-1+1.2*STEP+1e-9);assert.equal(r.kills,0);assert.equal(j.count,1);});
test('V2 14 field companion replaces appearance once, adds exactly one member and uses one budget',()=>{const t=crate();t.reward={kind:'fieldCompanion',id:'zhao_yun_guest',count:1};const j=fixture([t],5);j.companion='chen_ying';j.runner!.hitTarget(j.runner!.targets[0],60);assert.equal(j.count,6);assert.equal(j.companion,'zhao_yun_guest');assert.equal(j.runner!.members.filter(m=>m.role==='companion').length,1);assert.equal(j.runner!.members.find(m=>m.role==='companion')?.weight,1);assert.equal(j.runner!.members.reduce((n,m)=>n+m.weight,0),6);});
test('V2 15 large enemy and distance are independent; arriving never deletes active combat',()=>{const config={...LEVELS[2].runner!,startCount:3,routeEnd:.1,objects:[],enemyWaves:[],largeEnemy:{...LEVELS[2].runner!.largeEnemy!,spawnAt:0,hp:10000}};const j=new Journey({...LEVELS[2],runner:config});tick(j,20);assert.equal(j.z,.1);assert.equal(j.phase,'run');assert.ok(j.runner!.large);assert.equal(j.runner!.distanceLeft,0);assert.equal(j.runner!.remaining,0);});
test('V2 16 old best/unlocks/settings survive separate new-profile scoring and reload',()=>{const map=new Map<string,string>(),storage={getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>{map.set(k,v);}};const d=defaults();d.best['trial-01']=200;d.settings.music=false;map.set(KEY,JSON.stringify({...d,unknown:{keep:true}}));const b=new Book(storage);b.win(0,17,'runnerVideoV2');b.win(0,8,'runnerVideoV2');const copy=new Book(storage);assert.equal(copy.data.best['trial-01'],200);assert.equal(copy.runnerBest['trial-01'],17);assert.equal(copy.data.settings.music,false);assert.deepEqual(JSON.parse(map.get(KEY)!).unknown,{keep:true});assert.ok(copy.data.cleared['trial-01']);const growth=new Growth(storage,copy);const saved=JSON.stringify(growth.data);growth.reconcile();assert.equal(JSON.stringify(growth.data),saved);});
test('V2 17 profile starts 1/1/3, old levels unchanged; equipment and reload are explicit',()=>{assert.deepEqual(LEVELS.map(l=>l.start),[1,1,3]);assert.deepEqual(V07_LEVELS.map(l=>l.start),[8,12,16]);assert.ok(LEVELS.every(l=>l.profile==='runnerVideoV2'&&!l.horde&&!l.assault&&!l.rows.length));assert.equal(RUNNER_RULES.equipment.length,3);const j=fixture([],8);tick(j,20);j.pause();const z=j.z;tick(j,30);assert.equal(j.z,z);j.resume();tick(j);assert.ok(j.z>z);j.dispose();assert.equal(j.runner!.shots.length,0);assert.equal(j.runner!.targets.length,0);});
test('V2 18 new object pressure is bounded over 22 seconds; three clean retries reset state',()=>{const j=fixture([],256);tick(j,22*60);assert.ok(j.runner!.stats.peakShots<=512);assert.equal(j.runner!.stats.deferredShots,0);assert.ok(j.runner!.members.length<=48);for(let n=0;n<3;n++){const retry=new Journey(LEVELS[1]);tick(retry,60);retry.dispose();assert.equal(retry.runner!.shots.length,0);assert.equal(new Journey(LEVELS[1]).runner!.stats.shots,0);}});
test('V2 19 first-level legal input progresses from one member without hidden melee or injected damage',()=>{const j=new Journey(LEVELS[0]);for(let i=0;i<60*100&&!j.finished;i++){j.move(runnerSteer(j));tick(j);}assert.equal(j.phase,'won');assert.equal(j.runner!.remaining,0);assert.equal(j.runner!.spawned,50);assert.ok(j.runner!.stats.converted>=1);assert.ok(j.runner!.stats.equipment>=1);assert.equal(j.damageTotals.hero.melee,0);assert.equal(j.awakeningUsed,false);});

test('V2 20 actual projectile death names the ranged source and retains the precise loss ledger',()=>{const j=fixture(),r=j.runner!,e=enemy('large:yang_ling',0,4,1000);e.large=true;e.castId='yang_ling';r.enemies=[e];j.warnings=[{id:1,source:200,weaponId:'spear',profile:'runner-arrow',x:0,width:.1,loss:1,remaining:.01,duration:1,flight:.1,impact:.1,stage:'flight',hit:false,originX:0,originZ:4,projectileZ:.2}];tick(j);assert.equal(j.phase,'lost');assert.match(j.cause,/杨龄的飞矛/);assert.equal(r.lastDamage?.type,'enemyProjectile');assert.equal(r.lastDamage?.countBefore,1);assert.equal(r.lastDamage?.countAfter,0);});


test('v081 leaders have a dedicated rank; feet and frozen muzzle origins stay aligned',()=>{
 const j=fixture([],24);j.companion='chen_ying';const r=j.runner!,before=r.members;tick(j);
 const leaders=r.members.filter(m=>m.role!=='soldier'),soldiers=r.members.filter(m=>m.role==='soldier');
 assert.equal(leaders.length,2);assert.ok(Math.abs(leaders[0].x-leaders[1].x)>=.29);
 assert.ok(Math.max(...soldiers.map(m=>m.z))<=Math.min(...leaders.map(m=>m.z))-.64);
 for(const s of r.shots){const member=r.members.find(m=>m.id===s.origin.owner)!;assert.ok(Math.abs(s.origin.x-(member.x-(member.role==='soldier'?.064:0)))<1e-8);assert.ok(Math.abs(s.origin.z-member.z-.05)<1e-8);}
 assert.equal(before.reduce((n,m)=>n+m.weight,0),24);
});
test('v09 bounded approach preserves enemies and actual damage identifies one attacker and victim',()=>{
 const j=fixture([],8),r=j.runner!;r.enemies=Array.from({length:6},(_,i)=>({...enemy('front'+i,0,.10,10000),numericId:200+i,slot:i,attackClock:0}));
 tick(j);assert.equal(r.enemies.length,6);assert.equal(r.kills,0);assert.equal(j.count,7);assert.equal(r.lastContact?.enemyId,'front0');assert.equal(r.lastContact?.memberId,0);
 assert.ok(r.enemies.every(e=>Math.abs(e.at-.10)<=1.2*STEP+1e-9&&Math.abs(e.x)<=.45*STEP+1e-9));assert.equal(r.ledger.filter(e=>e.type==='enemyContact').length,1);
 tick(j,10);assert.equal(j.count,7);assert.ok(r.enemies.every(e=>!e.dead));
});

test('v081 enemies approach the accessible front rank, not unreachable rear-member lanes',()=>{
 const j=fixture([],18);j.companion='zhao_yun_guest';const r=j.runner!;
 r.enemies=Array.from({length:8},(_,i)=>({...enemy('approach'+i,(i%4-1.5)*.22,.3+Math.floor(i/4)*.3,10000),numericId:300+i,slot:i}));
 tick(j,180);assert.ok(j.count<18);assert.ok(r.lastContact);assert.ok(r.members.some(m=>m.role!=='soldier'&&m.id===r.lastContact!.memberId));assert.equal(r.kills,0);assert.equal(r.enemies.length,8);
});
