import {createBattle} from '../../assets/scripts/formal/battle';import {FormalStore} from '../../assets/scripts/formal/store';import {CHAPTERS,TREASURES} from '../../assets/scripts/formal/data';import {combatReviewTarget} from '../../assets/scripts/formal/CombatReviewPolicy';import {writeFileSync} from 'node:fs';
function fixture(chapter:number,high:boolean){const s=new FormalStore({getItem:()=>null,setItem:()=>{}});for(let i=0;i<chapter;i++){const c=CHAPTERS[i];s.data.cleared.push(c.id);s.data.captures.push(...c.capture);s.data.visits.push(...c.visit);s.data.allies.push(...c.allies);if(c.weapon)s.data.weapons.push(c.weapon);if(c.treasure)s.data.treasures.push(c.treasure);}const w=s.data.weapons.includes('guandao')?'guandao':s.data.weapons.includes('shuangji')?'shuangji':'spear';s.data.selectedWeaponId=w;const earned=CHAPTERS.slice(0,chapter).reduce((n,c,i)=>n+(c.firstClearXP||30)+(i%2?60:0),0);s.data.weaponLevels[w]=high?(earned>=180?3:earned>=60?2:1):1;s.data.companions=['zhao','zhang','lubu','machao'].filter(id=>s.data.captures.includes(id)).slice(-2);s.data.support=s.data.visits.includes('hua')?'hua':s.data.visits.includes('zhuge')?'zhuge':null;for(const slot of ['dian','qi','ma'])s.data.slots[slot]=s.data.treasures.find(t=>TREASURES[t].slot===slot)||null;return s.loadout();}
import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';
const logicFiles=['assets/scripts/formal/battle.ts','assets/scripts/formal/data.ts','assets/scripts/formal/EnemyProfiles.ts','assets/scripts/formal/EncounterDirector.ts','assets/scripts/formal/CombatTuning.ts','assets/scripts/formal/CombatReviewPolicy.ts'];
function fingerprint(){const h=createHash('sha256');for(const f of logicFiles)h.update(f).update(readFileSync(f));return h.digest('hex');}
const before=fingerprint(),rows=[];
for(const chapter of [10,15,19])for(const seed of [71])for(const high of [false,true])for(const policy of ['stationary','positive','normal'] as const){
 const lineup=fixture(chapter,high),b=createBattle({chapter,lineup,seed});let bossTroops=null,maxLive=0;
 for(let i=0;i<18000&&!b.state.ended;i++){if(i%6===0){const t=combatReviewTarget(b.snapshot(),policy);if(t!==null)b.move(t);}b.step();if(b.state.boss&&bossTroops===null)bossTroops=b.state.troops;maxLive=Math.max(maxLive,b.state.ents.filter(e=>e.type==='enemy'&&!e.dead).length);}
 const s=b.snapshot();rows.push({chapter:chapter+1,seed,loadoutKind:high?'higher-owned-level':'level1',lineup,policy,phase:s.phase,t:s.t,troops:s.troops,bossTroops,timing:s.timing,maxLive,damage:s.damageSources,grossLoss:s.damageHistory.reduce((n,e)=>n+e.actual,0),saved:s.stats.supportSaved,reinforcements:b.ledger.filter(e=>e.kind==='troops'&&e.amount>0).reduce((n,e)=>n+e.amount,0),spawned:s.waveAccounting.reduce((n,e)=>n+e.spawned,0),planned:s.waveAccounting.reduce((n,e)=>n+e.planned,0),cancelled:s.waveAccounting.reduce((n,e)=>n+(e.cancelled||0),0),pending:s.pendingSquads,release:s.enemyLifecycle.flatMap(e=>e.events).filter(e=>e.stage==='release').length,deferred:s.director.deferred});
 if(rows.length%48===0)console.log('completed',rows.length);
}
const after=fingerprint();writeFileSync('evidence/R3-COMBAT-PATCH-20261002/combat/footprint-regression18.json',JSON.stringify({scope:'18 affected candidate runs after actual team-foot envelope fix; automated visible-information policies, not human win probability',reactionSeconds:.30,logicFiles,combatSourceHashBefore:before,combatSourceHashAfter:after,sourceUnchanged:before===after,rows},null,2));console.log('done',rows.length,before===after);
