import {chromium} from 'playwright';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
export const E='evidence/R3-COMBAT-PATCH-20261002/menu';fs.mkdirSync(E,{recursive:true});
export async function open(name,width=375,height=667,record=false){const started=Date.now(),beforeVideos=new Set(fs.existsSync(E+'/video-raw')?fs.readdirSync(E+'/video-raw'):[]);const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding']});const c=await b.newContext({viewport:{width,height},deviceScaleFactor:2,isMobile:true,hasTouch:true,...(record?{recordVideo:{dir:E+'/video-raw',size:{width,height}}}:{})});const p=await c.newPage(),cd=await c.newCDPSession(p),errors=[];p.on('pageerror',e=>errors.push(e.message));
 let lastSkin='';const snap=()=>p.evaluate(()=>globalThis.__YLCG__.snapshot());const goto=async(fixture,skin='full')=>{if(lastSkin===skin&&await p.evaluate(()=>globalThis.__YLCG__?.reviewCommand('ui-fixture','home'))){await p.evaluate(f=>__YLCG__.reviewCommand('ui-fixture',f),fixture);await p.waitForTimeout(120);return;}lastSkin=skin;await p.goto(`http://127.0.0.1:${process.env.YILU_PORT||43215}/?yilu-review=UI:${fixture}&ui-skin=${skin}`);await p.waitForFunction(()=>globalThis.__YLCG__&&__YLCG__.snapshot().screen!=='loading',{},{timeout:60000});await p.waitForTimeout(1600);};
 const tap=async id=>{const s=await snap(),h=s.buttons.find(x=>x.id===id);if(!h)throw Error('Missing button '+id+' on '+s.screen);await p.touchscreen.tap(h.x+h.w/2,h.y+h.h/2);await p.waitForTimeout(170);};
 const command=(cmd,value)=>p.evaluate(({cmd,value})=>__YLCG__.reviewCommand(cmd,value),{cmd,value});
 const swipe=async(dx,dy)=>{const start={x:width*.5,y:height*.70,id:41},end={x:start.x+dx,y:Math.max(160,Math.min(height-80,start.y+dy)),id:41};await cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});for(let i=1;i<=8;i++){await cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+(end.x-start.x)*i/8,y:start.y+(end.y-start.y)*i/8,id:41}]});await p.waitForTimeout(18);}await cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(100);};
 const capture=async(name)=>{const dir=E+'/pixels';fs.mkdirSync(dir,{recursive:true});const file=dir+'/'+name+'.png';await p.screenshot({path:file});const state=await snap();fs.writeFileSync(dir+'/'+name+'.json',JSON.stringify({_bridge_media:true,capture_type:'browser',scope:'actual Cocos WebGL isolated memory-store; system touch input, not physical device',produced_at:new Date().toISOString(),build:state.build,source_sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),state},null,2));return state;};
 return {b,c,p,cd,width,height,errors,snap,goto,tap,command,swipe,capture,close:async()=>{const v=p.video(),bound=async(promise,ms)=>Promise.race([promise.catch(()=>null),new Promise(r=>setTimeout(()=>r(null),ms))]);await bound(p.close(),3500);await bound(c.close(),3500);let file=v?await bound(v.path(),2000):null;if(v&&!file){const candidates=fs.readdirSync(E+'/video-raw').filter(n=>n.endsWith('.webm')&&!beforeVideos.has(n)).map(n=>({file:path.resolve(E+'/video-raw',n),born:fs.statSync(E+'/video-raw/'+n).birthtimeMs})).filter(n=>n.born>=started-1500).sort((a,b)=>a.born-b.born);file=candidates[0]?.file||null;}await bound(b.close(),3500);return file;}};
}
