from pathlib import Path
from PIL import Image,ImageDraw
import json,hashlib,subprocess
E=Path('evidence/R3-COMBAT-PATCH-20261002/menu');P=E/'pixels';O=E/'boards';O.mkdir(exist_ok=True)
pairs=[('home-'+str(w)+'x'+str(h),'before-home-'+str(w)+'x'+str(h),'after-home-'+str(w)+'x'+str(h))for w,h in[(375,667),(402,874),(430,932)]]+[('lineup','before-lineup-402x874','after-lineup-402x874')]+[('c16-'+pose,'before-c16-lubu-machao-'+pose,'after-c16-lubu-machao-'+pose)for pose in ['run','wind','rel','rec']]
rows=[]
for label,b,a in pairs:
 old=json.loads((P/(b+'.json')).read_text());new=json.loads((P/(a+'.json')).read_text());assert old['state']['screen']!='render-error' and new['state']['screen']!='render-error';assert not new['state']['renderErrors'];oldsave=old['state']['save'];newsave=new['state']['save'];protected=['cleared','captures','visits','allies','weapons','treasures','weaponLevels','selectedWeaponId','slots','companions','support','mainTactic','claimed','xp'];diff=[k for k in protected if oldsave.get(k)!=newsave.get(k)];assert not diff,(label,diff)
 imgs=[Image.open(P/(n+'.png')).convert('RGB')for n in [b,a]];size=imgs[0].size;assert imgs[1].size==size;board=Image.new('RGB',(size[0]*2,size[1]+80),'#101D2B');d=ImageDraw.Draw(board)
 for i,(im,meta,side)in enumerate(zip(imgs,[old,new],['BEFORE ACTUAL COCOS','AFTER ACTUAL COCOS'])):
  board.paste(im,(i*size[0],80));d.text((12+i*size[0],12),label+' '+side,fill='#F1D9A0');d.text((12+i*size[0],36),'FP '+meta['build']['code_fingerprint'][:24],fill='white')
 file=O/(label+'.jpg');board.save(file,quality=92);rows.append({'label':label,'before':str(P/(b+'.png')),'after':str(P/(a+'.png')),'board':str(file),'protectedModelStateEqual':True,'beforeBuild':old['build'],'afterBuild':new['build'],'sha256':hashlib.sha256(file.read_bytes()).hexdigest(),'scope':'Actual same-size controlled Cocos screenshots; artwork not edited; not physical iPhone or natural continuous battle.'})
(E/'same-state-boards.json').write_text(json.dumps({'rows':rows},ensure_ascii=False,indent=2))
r=json.loads((E/'menu-runtime.json').read_text());video_row=next(x for x in r['rows']if x['name']=='actual-menu-operations');v=video_row['video'];builds=[x['build'] for x in r['results'] if x.get('build')];assert len({b['code_fingerprint'] for b in builds})==1,'mixed menu-runtime builds';video_build=video_row.get('build',builds[0]);assert video_build['code_fingerprint']==builds[0]['code_fingerprint'];out=E/'menu-operations-original-speed.mp4';subprocess.run(['ffmpeg','-y','-i',v,'-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart',str(out)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
meta={'_bridge_media':True,'build':video_build,'capture_type':'browser','speed':'original','audio':'none; menu-only operation evidence, not audible verification','scope':'Actual Cocos WebGL, logical375x667 and system touches. Explicit fixture changes between cases, no physical finger control. No time acceleration.','source_sha256':hashlib.sha256(out.read_bytes()).hexdigest(),'scriptHash':r['scriptHash']};out.with_suffix('.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2));print(len(rows),'boards; video',out)
