// Execute the actual TS diagnostic class with platform adapters, including Release-disabled behavior.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),ts=require('../../../node_modules/typescript');
const source=fs.readFileSync('assets/scripts/formal/BridgeDiagnostics.ts','utf8');
const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
function make(debug,fail=false){let writes=[];const context={exports:{},require(id){if(id==='cc/env')return{DEBUG:debug};if(id==='cc')return{sys:{isNative:true},native:{fileUtils:{getWritablePath(){return '/diagnostics/';},writeStringToFile(text,path){if(fail)throw Error('disk unavailable');writes.push({text,path});}}}};if(id==='./BridgeBuild')return{BRIDGE_BUILD:{build_id:'test-build',code_fingerprint:'a'.repeat(64)}};throw Error(id);},Date,Math};vm.runInNewContext(code,context);return{d:new context.exports.BridgeDiagnostics(),writes};}
const viewport={width:390,height:844,safe:{top:47,bottom:810}};
const release=make(false);release.d.event('level_start');for(let i=0;i<600;i++)release.d.sample(1/60,'battle',0,{},viewport);release.d.close();assert.equal(release.writes.length,0);
const debug=make(true);debug.d.event('level_start',{chapter:0});for(let i=0;i<600;i++)debug.d.sample(1/60,'battle',0,{logical_troops:180,visible_friendly:43},viewport);debug.d.close();assert.ok(debug.writes.length>=9&&debug.writes.length<=11);const events=debug.writes.at(-1).text.trim().split('\n').map(JSON.parse);assert.ok(events.some(e=>e.event==='startup'));assert.ok(events.some(e=>e.event==='shutdown'));const intervals=events.filter(e=>e.event==='interval');assert.ok(intervals.every(e=>e.counts.logical_troops===180&&e.counts.visible_friendly===43));assert.ok(intervals.every(e=>e.missing.gpu_ms==='unavailable'));assert.ok(intervals.every(e=>e.interval.sample_count>=60));
const failed=make(true,true);for(let i=0;i<300;i++)failed.d.sample(1/60,'battle',0,{},viewport);assert.equal(failed.writes.length,0);
console.log(JSON.stringify({passed:true,release_writes:release.writes.length,debug_writes:debug.writes.length,interval_events:intervals.length,io_failure_nonfatal:true,scope:'actual TypeScript class with cc adapters; physical Release binary not executed'}));
