import { Node, Graphics, Color, Label, UITransform, Layers } from 'cc';
import { Journey, BOSS_TARGET, clamp } from './core/model';
import { project, formation } from './VisualConfig';
import { lossLabel, bossFootprint, Effects } from './Presentation';
import { HeroRig, Pose } from './HeroRig';
const C={ink:'#203b43',blue:'#3c6573',cream:'#f3ead5',red:'#a84835',gold:'#c89349',road:'#d8c8a6',grass:'#a4ad91'};
export type Preview={count:number;x:number;time:number;pose:Pose;rank:boolean;debug:boolean};
/** S2-A candidate hero + S1 placeholders. Ground anchors determine occlusion. */
export class BattleView {
 private g!:Graphics;private layer!:Node;private order=0;private labels=new Map<string,Node>();private layers=new Map<string,Node>();private rigs=new Map<string,HeroRig>();
 readonly effects=new Effects();debug=false;
 constructor(private root:Node){}
 private use(id:string){let n=this.layers.get(id);if(!n){n=new Node(id);n.layer=Layers.Enum.UI_2D;this.root.addChild(n);n.addComponent(UITransform);n.addComponent(Graphics);this.layers.set(id,n);}n.active=true;n.setSiblingIndex(this.order++);this.layer=n;this.g=n.getComponent(Graphics)!;this.g.clear();return n;}
 private begin(){this.order=0;for(const n of this.layers.values())n.active=false;for(const n of this.labels.values())n.active=false;for(const r of this.rigs.values())r.node.active=false;}
 private color(c:string){return new Color().fromHEX(c);}
 private rect(x:number,y:number,w:number,h:number,c:string){this.g.fillColor=this.color(c);this.g.rect(x,y,w,h);this.g.fill();}
 private ellipse(x:number,y:number,w:number,h:number,c:string){this.g.fillColor=this.color(c);this.g.ellipse(x,y,w,h);this.g.fill();}
 private line(x:number,y:number,x2:number,y2:number,c:string,w=3){this.g.strokeColor=this.color(c);this.g.lineWidth=w;this.g.moveTo(x,y);this.g.lineTo(x2,y2);this.g.stroke();}
 private text(id:string,t:string,x:number,y:number,size=24,color=C.ink,w=300){let n=this.labels.get(id);if(!n){n=new Node(id);n.layer=Layers.Enum.UI_2D;n.addComponent(UITransform);n.addComponent(Label);this.labels.set(id,n);}if(n.parent!==this.layer)this.layer.addChild(n);n.active=true;n.setPosition(x,y);n.setScale(1,1,1);n.getComponent(UITransform)!.setContentSize(w,Math.max(65,size*1.35));const l=n.getComponent(Label)!;l.fontSize=size;l.lineHeight=size*1.3;l.horizontalAlign=Label.HorizontalAlign.CENTER;l.verticalAlign=Label.VerticalAlign.CENTER;l.overflow=Label.Overflow.NONE;l.string=t;l.color=this.color(color);return n;}
 private actor(x:number,y:number,w:number,h:number,role:'friend'|'enemy'|'boss',time:number,charge=false){const body=role==='friend'?C.blue:C.red;this.ellipse(x,y,w*.43,h*.08,'#6b705c');const stride=Math.sin(time*9+x)*h*.035;this.line(x-w*.13,y+h*.28,x-w*.2,y+5+stride,C.ink,w*.16);this.line(x+w*.13,y+h*.28,x+w*.2,y+5-stride,C.ink,w*.16);this.rect(x-w*.28,y+h*.23,w*.56,h*.4,body);this.rect(x-w*.29,y+h*.28,w*.58,h*.06,C.gold);this.ellipse(x,y+h*.78,w*.24,h*.14,'#d5ac7c');this.ellipse(x,y+h*.86,w*.26,h*.08,C.ink);this.ellipse(x,y+h*.97,w*.09,h*.04,C.ink);const arm=charge?h*.8:h*.51;this.line(x-w*.28,y+h*.58,x-w*.55,y+arm,body,w*.14);this.line(x+w*.27,y+h*.59,x+w*.52,y+h*.52,body,w*.14);if(role==='boss'){this.line(x-w*.55,y+arm-h*.13,x-w*.55,y+arm+h*.45,C.ink,4);}else this.line(x-w*.57,y+h*.3,x-w*.57,y+h*.9,C.gold,3);}
 private hero(id:string,x:number,y:number,h:number,t:number,pose:Pose,rank:boolean,age=10){this.ellipse(x,y,h*.25,h*.065,'#787d67');if(!HeroRig.ready)return;let r=this.rigs.get(id);if(!r){r=new HeroRig(this.layer);this.rigs.set(id,r);}else if(r.node.parent!==this.layer)this.layer.addChild(r.node);r.render(x,y,h,t,pose,rank,age);}
 private ground(z:number){this.use('ground');this.rect(-360,-1800,720,3600,C.grass);const g=this.g;g.fillColor=this.color(C.road);g.moveTo(-480,-1664);g.lineTo(480,-1664);g.lineTo(30,1216);g.lineTo(-30,1216);g.close();g.fill();this.line(-320,-640,-120,640,'#89947c',5);this.line(320,-640,120,640,'#89947c',5);for(let i=0;i<12;i++){const p=project(i%2?1.15:-1.15,i*.82-z%.82);this.ellipse(p.x,p.y,35*p.s,13*p.s,'#818d71');this.rect(p.x-4*p.s,p.y,8*p.s,60*p.s,'#857155');this.ellipse(p.x,p.y+57*p.s,31*p.s,43*p.s,'#70886e');}for(let i=0;i<14;i++){const p=project(Math.sin(i*19)*.8,i*.55-z%.55);this.line(p.x-8,p.y,p.x+11,p.y+2,'#c4b38e',2);}}
 render(j:Journey|null,rank=false){this.begin();this.ground(j?.z||0);if(!j){this.use('hero-home');this.hero('home',0,-75,180,0,'idle',rank);return;}
  this.effects.advance(j.elapsed);this.use('danger-ground');
  for(const w of j.warnings){const x=w.x*260,width=w.width*520;this.g.fillColor=new Color(163,62,38,w.stage==='impact'?160:38);this.g.rect(x-width/2,-550,width,870);this.g.fill();this.line(x-width/2,-550,x-width/2,320,C.red,3);this.line(x+width/2,-550,x+width/2,320,C.red,3);for(let y=-550;y<320;y+=45)this.line(x-width/2,y,x+width/2,y+15,'#b7714d',1);}
  const jobs:{y:number;id:string;draw:()=>void}[]=[];
  for(const r of j.level.rows){const d=r.at-j.z;if(j.usedRows.has(r.id)||d<0||d>7)continue;const p=project(0,d);jobs.push({id:'gate'+r.id,y:p.y,draw:()=>{for(const side of [-1,1]){const x=side*130*p.s,op=side<0?r.left:r.right,selected=(j.x<0?-1:1)===side;this.rect(x-128*p.s,p.y-4*p.s,256*p.s,8*p.s,selected?C.gold:'#8c9379');for(const edge of [-1,1])this.rect(x+edge*122*p.s-3,p.y,6,104*p.s,'#716044');this.rect(x-118*p.s,p.y+54*p.s,236*p.s,58*p.s,selected?C.ink:'#75857a');if(op.kind==='double')this.line(x-114*p.s,p.y+114*p.s,x+114*p.s,p.y+114*p.s,C.gold,5);this.text(`g${r.id}${side}`,op.kind==='add'?`+${op.value}`:'×2',x,p.y+81*p.s,44,C.cream,230);}}});}
  for(const o of j.obstacles){const d=o.at-j.z;if(o.dead||o.resolved||d<0||d>7)continue;const p=project(o.x,d);jobs.push({id:'obstacle'+o.id,y:p.y,draw:()=>{if(o.kind==='wood'){const w=(o.rowId!==undefined?260:o.width*520)*p.s;this.rect(p.x-w/2,p.y,w,43*p.s,'#906a43');for(let i=0;i<7;i++)this.line(p.x-w/2+i*w/6,p.y,p.x-w/2+i*w/6,p.y+43*p.s,'#5f4b37',3);this.line(p.x-w/2,p.y+4*p.s,p.x+w/2,p.y+35*p.s,C.gold,4);}else if(o.kind==='rock'){this.ellipse(p.x,p.y+20*p.s,o.width*260*p.s,34*p.s,'#7c8179');this.line(p.x-25*p.s,p.y+30*p.s,p.x+8*p.s,p.y+47*p.s,'#adb1a3',5);}else{this.g.strokeColor=this.color(C.red);this.g.lineWidth=3;this.g.ellipse(p.x,p.y,o.width*260*p.s,10*p.s);this.g.stroke();this.actor(p.x,p.y,52*p.s,74*p.s,'enemy',j.elapsed);}
  this.text('loss'+o.id,lossLabel(o),p.x,p.y-23,24,C.red,320);if(o.kind!=='rock'){const max=j.level.obstacles.find(a=>a.id===o.id)!.hp;this.rect(p.x-42*p.s,p.y+(o.kind==='wood'?45:78)*p.s,84*p.s,6,'#7e7b68');this.rect(p.x-42*p.s,p.y+(o.kind==='wood'?45:78)*p.s,84*p.s*o.hp/max,6,C.red);}if(this.debug){const hw=(o.side?.length? .5:o.width)*260*p.s;this.line(p.x-hw,p.y,p.x+hw,p.y,'#00d5d5',3);}}});}
  if(j.phase==='boss'||j.z>j.level.duration-4){const d=BOSS_TARGET.depth+(j.phase==='boss'?0:j.level.duration-j.z),p=project(0,d),width=bossFootprint(d);jobs.push({id:'boss',y:p.y,draw:()=>{ // Visible shield shares the complete logical hit width, not an invisible halo.
   this.actor(0,p.y,width,210*p.s,'boss',j.elapsed,!!j.bossWarning&&j.bossWarning.stage==='charge');this.rect(-width/2,p.y+36*p.s,width,84*p.s,C.red);this.line(-width/2,p.y+37*p.s,width/2,p.y+37*p.s,C.gold,4);this.line(0,p.y+40*p.s,0,p.y+115*p.s,C.gold,4);this.text('boss',j.level.bossName,0,p.y+222*p.s,27);this.rect(-130,p.y+183*p.s,260,10,'#8c8d7b');this.rect(-130,p.y+183*p.s,260*j.bossHP/j.level.bossHP,10,C.red);this.text('bosshp',`${Math.ceil(j.bossHP)} / ${j.level.bossHP}`,0,p.y+156*p.s,20);if(this.debug){this.line(-width/2,p.y,width/2,p.y,'#00d5d5',3);for(const x of [-width/2,width/2])this.line(x,p.y,x,p.y+120*p.s,'#00d5d5',2);}}});}
  const team=formation(j.visibleCount,j.x);
  if(team.length){const u=team[0];jobs.push({id:'team-hero',y:u.y,draw:()=>this.hero('battle',u.x,u.y,94,j.elapsed,'walk',rank,j.elapsed-this.effects.lastShot)});}
  // All followers have ground anchors behind/below the hero. No live world object
  // can occur there (depth < 0 is culled), so their contiguous depth band batches safely.
  if(team.length>1)jobs.push({id:'team-followers',y:team[1].y,draw:()=>{for(let i=1;i<team.length;i++){const u=team[i];this.actor(u.x,u.y,42,56,'friend',j.elapsed+i*.16);}}});
  jobs.sort((a,b)=>b.y-a.y||a.id.localeCompare(b.id));for(const job of jobs){this.use(job.id);job.draw();}
  this.use('projectiles');for(const a of j.arrows){const p=project(a.x,a.z-j.z),traces=a.damage<4?1:a.damage<12?3:5;for(let k=0;k<traces;k++){const x=p.x+(k-(traces-1)/2)*2;this.line(x,p.y-13,x,p.y+10,C.ink,2);this.line(x-3,p.y+5,x,p.y+10,C.gold,2);}if(this.debug)this.ellipse(p.x,p.y,3,3,'#00d5d5');}
  this.use('effects');this.g.strokeColor=this.color(C.cream);this.g.lineWidth=2;this.g.ellipse(j.x*260,-270,11,5);this.g.stroke();for(const f of this.effects.items){const p=project(f.event.x,(f.event.worldZ??j.z)-j.z),age=(j.elapsed-f.born)/f.life,n=f.event.kind==='break'?6:3;for(let i=0;i<n;i++){const a=i*Math.PI*2/n,x=p.x+Math.cos(a)*age*30,y=p.y+48+Math.sin(a)*age*24-age*age*20;this.rect(x,y,4*(1-age)+1,4*(1-age)+1,f.event.kind==='hurt'?C.red:C.gold);}}
  this.use('warning-label');for(const w of j.warnings){this.text('warn'+w.source,`${w.stage==='charge'?'蓄力':w.stage==='flight'?'已投出':'落点'} · 命中 −${w.loss}`,0,405,26,C.red,500);if(w.stage==='flight'){const q=clamp(w.remaining/w.flight,0,1);this.line(w.x*260,-270+q*430,w.x*260,-230+q*430,C.ink,5);}}
 }
 preview(p:Preview){this.begin();this.ground(p.pose==='walk'||p.pose==='shoot'?p.time:0);this.use('preview-main');this.hero('preview-large',0,30,270,p.time,p.pose,p.rank,10);const units=formation(p.count,p.x);this.use('preview-team');for(let i=0;i<units.length;i++){const u=units[i];this.hero('fixture'+i,u.x,u.y,u.hero?94:67,p.time,p.pose,p.rank&&u.hero);if(p.debug)this.line(u.x-33,u.y,u.x+33,u.y,'#00d5d5',1);}this.use('fixture-caption');this.text('fixture-caption',`真实兵力 ${p.count} · 展示 ${units.length}（含主角）`,0,-515,24);}
 portrait(rank:boolean){this.begin();this.use('portrait');this.hero('portrait',0,0,102,1.5,'promote',rank);}
 clear(){this.effects.clear();}
 get poolSize(){return this.labels.size+this.layers.size;}
 get diagnostics(){return {effects:this.effects.items.length,peakEffects:this.effects.peak,rigs:this.rigs.size,ready:HeroRig.ready,depthOrder:Array.from(this.layers.values()).filter(n=>n.active).sort((a,b)=>a.getSiblingIndex()-b.getSiblingIndex()).map(n=>n.name),bounds:Array.from(this.rigs.entries()).filter(([,r])=>r.node.activeInHierarchy).map(([id,r])=>({id,...r.bounds()}))};}
}
