import {BattleNotice} from './core/battleNotices';
import { _decorator, Component, Node, Label, UITransform, Color, Layers, view, ResolutionPolicy, Graphics, input, Input, EventTouch, Vec3, profiler } from 'cc';
import { CAMPAIGN } from './core/campaignData';
import {CAST,WEAPONS,CompanionId,PlayerWeapon,companionFor} from './core/weapons';
import { TransitionId } from './core/campaign';
import { Journey } from './core/model';
import { LEVELS, PLAYABLE_LEVELS } from './core/levels';
import { Platform } from './Platform';
import { Pose } from './HeroRig';
import { BattleView } from './BattleView';
import { ArtSprites } from './ArtSprites';
import { canStart, nextUnfinished, rankStage } from './core/progression';
const { ccclass } = _decorator;
type Screen='home'|'chapters'|'battle'|'pause'|'result'|'settings'|'preview'|'transition'|'camp'|'meeting'|'loadout';
type Hit={id:string;x:number;y:number;w:number;h:number;run:()=>void};
const INK='#263c43',PAPER='#f8edcf',MUTE='#737762',RED='#a34e37';
@ccclass('Game')
export class Game extends Component {
 private platform!:Platform;private screen:Screen='home';private level=0;private world!:Node;private ui!:Node;private battle!:BattleView;
 private hits:Hit[]=[];private journey:Journey|null=null;private dragging=false;private touchId=-1;private lastDrag=0;private pointerStart=0;private touchButton:Hit|null=null;
 private returnScreen:Screen='home';private loaded=false;private message='';private messageTime=0;private tutorialUntil=5;private dragged=false;
 private transitionId:TransitionId='rally';private transitionAge=0;private campPaused=false;private transitionDone=false;private flagDrag:{x:number;y:number}|undefined;private flagTouch=false;
 private notices=new BattleNotice();private newUnlocks:string[]=[];private combatStats={meleeHits:0,meleeDamage:0,waveHits:0,companionHits:0,upgrades:0,awakenings:0,volleys:0,lastMelee:null as any};private firstVictory=false;private finishAge=0;private promotionTime=0;private promotionView:BattleView|null=null;
 private frameTimes:number[]=[];private wallFrames=0;private fps=60;private fpsElapsed=0;
 private previewState={count:8,x:0,time:0,pose:'idle' as Pose,rank:false,debug:false};private previewPaused=false;
 private touchStart=(e:EventTouch)=>{if(this.touchId!==-1)return;this.touchId=e.getID()??-1;const p=this.local(e);this.down(p.x,p.y);};
 private touchMove=(e:EventTouch)=>{if(e.getID()!==this.touchId)return;const p=this.local(e);if(this.flagTouch){this.flagDrag={x:p.x,y:p.y};return;}if(this.dragging&&this.journey){this.journey.move(this.journey.target+(p.x-this.lastDrag)/260);if(Math.abs(p.x-this.lastDrag)>2&&!this.dragged){this.dragged=true;this.tutorialUntil=Math.min(this.tutorialUntil,this.journey.elapsed+2);}this.lastDrag=p.x;}};
 private touchEnd=(e:EventTouch)=>{if(e.getID()!==this.touchId)return;const p=this.local(e),b=this.touchButton,flag=this.flagTouch;this.touchCancel();if(flag){if(Math.abs(p.x)<150&&Math.abs(p.y+170)<130)this.completeTransition();return;}if(b&&Math.abs(p.x-b.x)<=b.w/2&&Math.abs(p.y-b.y)<=b.h/2&&Math.abs(p.x-this.pointerStart)<40)b.run();};
 private touchCancel=()=>{this.dragging=false;this.flagTouch=false;this.flagDrag=undefined;this.touchId=-1;this.touchButton=null;this.journey?.cancelMove();};
 async start(){view.setDesignResolutionSize(720,1280,ResolutionPolicy.FIXED_WIDTH);this.world=this.make('World',this.node);this.ui=this.make('Interface',this.node);this.battle=new BattleView(this.world);this.battle.debug=typeof location!=='undefined'&&typeof URLSearchParams!=='undefined'&&new URLSearchParams(location.search).get('debug')==='hitboxes';this.platform=new Platform(this.node,()=>{this.touchCancel();if(this.screen==='battle')this.pause();if(['transition','camp','meeting','loadout'].indexOf(this.screen)>=0){this.campPaused=true;this.button('resume-camp','继续',0,()=>{this.campPaused=false;this.show(this.screen);this.platform.syncAudio();},0,510,true);this.hits=this.hits.filter(h=>h.id==='resume-camp');}if(this.screen==='preview'){this.previewPaused=true;this.setText('preview-pause','继续动作');}});input.on(Input.EventType.TOUCH_START,this.touchStart);input.on(Input.EventType.TOUCH_MOVE,this.touchMove);input.on(Input.EventType.TOUCH_END,this.touchEnd);input.on(Input.EventType.TOUCH_CANCEL,this.touchCancel);profiler.hideStats();(globalThis as any).__YLCG__={snapshot:()=>this.snapshot()};await this.loadAssets();}
 private async loadAssets(){this.loaded=false;this.hits=[];for(const n of [...this.ui.children]){n.removeFromParent();n.destroy();}this.text('loading','正在整队…',0,0,32);try{await Promise.all([this.platform.load(),ArtSprites.load()]);this.loaded=true;this.show(typeof location!=='undefined'&&typeof URLSearchParams!=='undefined'&&new URLSearchParams(location.search).get('preview')==='character'?'preview':'home');}catch{this.loaded=true;this.setText('loading','资源加载失败，请重试');this.button('retry-assets','重新加载',-120,()=>{void this.loadAssets();},0,510,true);}}
 private local(e:EventTouch){const p=e.getUILocation();return this.node.getComponent(UITransform)!.convertToNodeSpaceAR(new Vec3(p.x,p.y,0));}
 private down(x:number,y:number){if(!this.loaded)return;this.platform.syncAudio(this.screen!=='pause'&&!(this.screen==='preview'&&this.previewPaused));this.touchButton=this.hits.find(b=>Math.abs(x-b.x)<=b.w/2&&Math.abs(y-b.y)<=b.h/2)||null;this.pointerStart=x;if(this.screen==='transition'&&!this.transitionDone&&x<-125&&y>-215&&y<70){this.flagTouch=true;this.flagDrag={x,y};this.touchButton=null;return;}if(!this.touchButton&&this.screen==='battle'){this.dragging=true;this.lastDrag=x;}}
 private make(name:string,parent:Node){const n=new Node(name);n.layer=Layers.Enum.UI_2D;parent.addChild(n);n.addComponent(UITransform);return n;}
 private text(id:string,value:string,x:number,y:number,size=26,color=INK,w=620,h=80){const n=this.make(id,this.ui);n.setPosition(x,y);n.getComponent(UITransform)!.setContentSize(w,h);const l=n.addComponent(Label);l.string=value;l.fontSize=size;l.lineHeight=size*1.4;l.color=new Color().fromHEX(color);l.horizontalAlign=Label.HorizontalAlign.CENTER;l.verticalAlign=Label.VerticalAlign.CENTER;l.overflow=Label.Overflow.SHRINK;return n;}
 private panel(x:number,y:number,w:number,h:number,color=PAPER){const n=this.make('panel',this.ui);n.setPosition(x,y);const g=n.addComponent(Graphics);g.fillColor=new Color().fromHEX(color);g.roundRect(-w/2,-h/2,w,h,5);g.fill();g.strokeColor=new Color().fromHEX('#bd9b5c');g.lineWidth=2;g.roundRect(-w/2+6,-h/2+6,w-12,h-12,3);g.stroke();}
 private button(id:string,title:string,y:number,run:()=>void,x=0,w=510,primary=false){this.panel(x,y,w,74,primary?INK:PAPER);this.text(id,title,x,y,27,primary?PAPER:INK,w-20,68);this.hits.push({id,x,y,w,h:88,run});}
 private show(screen:Screen){this.screen=screen;this.promotionView=null;this.promotionTime=0;this.touchCancel();for(const n of [...this.ui.children]){n.removeFromParent();n.destroy();}this.hits=[];const l=LEVELS[this.level],b=this.platform.book,edge=Math.max(0,(view.getVisibleSize().height-1280)/2);
  if(screen!=='battle'&&screen!=='pause'&&screen!=='settings'&&screen!=='preview')this.battle.render(null,rankStage(b),0,this.platform.growth.data.equippedWeapon);
  if(screen==='home'){
   this.panel(0,352,620,350);this.text('eyebrow',CAMPAIGN.chapterTitle,0,478,23,MUTE);this.text('title',CAMPAIGN.title,0,390,54);this.text('tagline',CAMPAIGN.tagline,0,302,29);this.text('scope',CAMPAIGN.levels.map(l=>l.title).join(' → '),0,227,23,MUTE);
   const c=this.platform.campaign,pending=c.pending,done=c.data.completed.garrison;
   this.text('rank',CAMPAIGN.rankLabels.join(' → '),0,-120,25);
   this.button('start',pending?CAMPAIGN.home.resumeTransition:done?CAMPAIGN.home.completed:rankStage(b)>0?CAMPAIGN.home.continue:CAMPAIGN.home.newGame,-225,()=>{if(pending)this.openTransition(pending);else if(done)this.show(c.data.seen.zhaoyunMeeting?'camp':'meeting');else{const i=nextUnfinished(b);if(i>=0)this.begin(i);else this.show('chapters');}},0,530,true);
   this.button('chapters',CAMPAIGN.home.replay,-325,()=>this.show('chapters'));if(this.platform.growth.data.unlockedCompanions.length)this.button('loadout','整备队伍',-425,()=>this.show('loadout'),-140,250);this.button('settings',CAMPAIGN.home.settings,-425,()=>{this.returnScreen='home';this.show('settings')},this.platform.growth.data.unlockedCompanions.length?140:0,this.platform.growth.data.unlockedCompanions.length?250:510);this.text('current-rank',`当前身份 · ${CAMPAIGN.rankLabels[rankStage(b)]}`,0,-525,24,MUTE);
  }else if(screen==='preview'){
   this.panel(0,545,640,145);this.text('preview-title','队伍与动作',0,550,34);this.text('preview-info','排布测试 · 主角与正式友军',0,493,21,MUTE);
   (['idle','walk','shoot','promote'] as Pose[]).forEach((pose,i)=>this.button('pose-'+pose,['站立','行走','射箭','晋升'][i],415,()=>{this.previewState.pose=pose;this.previewState.time=0;this.previewPaused=false;this.platform.syncAudio();},-258+i*172,158));
   [1,8,24,48,256].forEach((count,i)=>this.button('count-'+count,String(count),-35,()=>this.previewState.count=count,-280+i*140,125));
   [-.91,0,.91].forEach((x,i)=>this.button('position-'+i,['最左','居中','最右'][i],-130,()=>this.previewState.x=x,-230+i*230,215));
   this.button('preview-pause',this.previewPaused?'继续动作':'暂停动作',-650,()=>{this.previewPaused=!this.previewPaused;this.platform.syncAudio(!this.previewPaused);this.setText('preview-pause',this.previewPaused?'继续动作':'暂停动作');},-165,285);
   this.button('home','返回首页',-650,()=>this.show('home'),165,285);
  }else if(screen==='chapters'){
   this.panel(0,40,660,1020);this.text('title',CAMPAIGN.chapterTitle,0,468,35);
   LEVELS.forEach((v,i)=>{const y=290-i*225;this.text('rank'+i,`${v.rankBefore} → ${v.rankAfter} / 出征 ${v.start} 人`,0,y+70,23,MUTE);if(i<PLAYABLE_LEVELS&&b.unlock(i))this.button('level'+i,v.title+(b.data.cleared[v.id]?'  ✓':''),y,()=>this.begin(i),0,530,true);else this.text('pending'+i,v.title+' · 先通关上一关',0,y,30);this.text('record'+i,b.unlock(i)?(this.platform.growth.data.equippedCompanion===v.bossId?`${v.bossName}本场待命`:`本关最佳：${b.data.best[v.id]} 人`):'通关上一关后解锁',0,y-60,20,MUTE);});this.button('home','返回首页',-490,()=>this.show('home'));
  }else if(screen==='battle'){
   this.panel(0,543+edge,686,136);this.text('level',l.title+' · '+l.scene,-40,576+edge,24,INK,540,46);this.text('count','',-170,523+edge,37,INK,300,60);this.text('progress','',100,523+edge,23,MUTE,210,60);this.panel(0,450+edge,670,48);this.text('weapon-tier','',-235,450+edge,25,INK,170,48);this.text('awakening-status','',-45,450+edge,24,INK,155,48);this.text('companion-status','',165,450+edge,23,INK,285,48);this.button('pause','Ⅱ',555+edge,()=>this.pause(),291,78);this.text('feedback','',0,-590,26,INK,650,60);this.text('tutorial','',0,-548,22,INK,670,55);
  }else if(screen==='pause'){
   this.panel(0,0,620,700);this.text('title','已暂停',0,260,43);this.button('continue','继续',120,()=>{this.journey!.resume();this.show('battle');this.platform.syncAudio()},0,510,true);this.button('restart','重新开始',15,()=>this.begin());this.button('settings','设置',-90,()=>{this.returnScreen='pause';this.show('settings')});this.button('chapters','返回关卡',-195,()=>this.leave());
  }else if(screen==='result'){
   const j=this.journey!,won=j.phase==='won',last=this.level===PLAYABLE_LEVELS-1;this.panel(0,30,648,1120);
   const title=!won?'胜败乃兵家常事':!this.firstVictory?'再次取胜':last?'白石初定':`晋升${l.rankAfter}`;
   this.text('title',title,0,470,43);this.text('ending',won?l.ending:this.level===2&&j.z===j.level.duration?j.cause.replace('弩箭','羽箭'):j.cause,0,364,25,INK,560,100);
   this.text('identity',won?(this.firstVictory?`${l.rankBefore} → ${l.rankAfter} · ${b.notice?'本次战绩已记录':'进度已保存'}`:`当前身份：${CAMPAIGN.rankLabels[rankStage(b)]} · ${b.notice?'本次战绩已记录':'战绩已保存'}`):`当前身份：${CAMPAIGN.rankLabels[rankStage(b)]} · 本关免费重开`,0,277,25);
   if(won){const portrait=this.make('promotion-hero',this.ui);portrait.setPosition(0,-5);this.promotionView=new BattleView(portrait);this.promotionView.portrait(rankStage(b),0,this.level,this.platform.growth.data.equippedWeapon);}
   if(won&&this.newUnlocks.length)this.text('new-unlocks','获得：'+this.newUnlocks.join(' · '),0,-204,21,INK,610,40);
   this.text('stats',`剩余兵力：${j.count}  /  最佳：${b.data.best[l.id]} 人\n用时：${j.elapsed.toFixed(1)} 秒`,0,-133,24,MUTE,570,95);
   if(won&&!this.platform.campaign.data.completed[CAMPAIGN.levels[this.level].transitionId])this.button('transition',CAMPAIGN.transitions[this.level].primaryAction,-260,()=>this.openTransition(CAMPAIGN.levels[this.level].transitionId),0,530,true);
   else if(won&&!last)this.button('next','下一关：'+LEVELS[this.level+1].title,-260,()=>this.begin(this.level+1),0,530,true);
   else if(won)this.button('replay-map','重玩关卡',-260,()=>this.leave(),0,530,true);
   this.button('restart',won?'再战本关':'重新开始',won?-363:-285,()=>this.begin(),0,530,!won);this.button('chapters','返回关卡',-465,()=>this.leave());
  }else if(screen==='transition'){
   const t=CAMPAIGN.transitions.find(t=>t.id===this.transitionId)!;
   this.panel(0,365,648,370);this.text('title',t.title,0,490,43);this.text('context',t.context,0,375,27,INK,560,110);this.text('instruction',this.transitionDone?t.resultText:t.instruction,0,266,25);
   this.loadout(140);this.text('formation',this.level<2?`先锋 ${t.nextStartCount} 人 · 其余弟兄留守`:'白石驻防',0,-485,25);
   this.button('complete-transition',t.primaryAction,-570,()=>this.completeTransition(),0,550,true);
   this.hits.push({id:'flag-target',x:0,y:-170,w:260,h:240,run:()=>this.completeTransition()});
  }else if(screen==='loadout'){this.panel(0,380,648,230);this.text('title','行军整备',0,440,43);this.text('context','选好兵器与同袍，再踏征途。',0,350,26);this.loadout(170);this.button('home','返回出征',-555,()=>this.show('home'),0,530,true);
  }else if(screen==='camp'){
   this.panel(0,390,648,255);this.text('title',CAMPAIGN.camp.title,0,447,45);this.text('status',CAMPAIGN.camp.status,0,352,27);
   this.loadout(170);this.button('chapters',CAMPAIGN.home.replay,-520,()=>this.show('chapters'),0,530,true);this.button('settings','设置',-620,()=>{this.returnScreen='camp';this.show('settings')});
  }else if(screen==='meeting'){
   const e=CAMPAIGN.encounters[0];this.panel(0,370,648,360);this.text('title',e.name,0,483,43);this.text('dialogue',e.lines.map(l=>l.speaker+'：'+l.line).join('\n\n'),0,348,27,INK,552,245);
   this.text('ending','与赵云并肩一战',0,-425,32);this.button('return-camp',e.primaryAction,-560,()=>{this.platform.campaign.meet();this.show('camp');},0,550,true);
  }else if(screen==='settings'){
   this.panel(0,0,640,820);this.text('title','设置',0,300,44);(['sfx','vibration'] as const).forEach((k,i)=>this.button(k,`${['动作音效','轻触震动'][i]}：${b.data.settings[k]?'开':'关'}`,140-i*110,()=>{b.data.settings[k]=!b.data.settings[k];b.persist();this.platform.syncAudio(this.returnScreen!=='pause');if(k==='sfx'&&b.data.settings.sfx)this.platform.sound('hit');this.show('settings')}));this.text('music-credit','历史音乐素材许可：Shenyang — Kevin MacLeod\nCC BY 4.0 · creativecommons.org/licenses/by/4.0/\n本版仅播放战斗音效',0,-212,18,MUTE,580,120);this.button('return','返回',-320,()=>this.show(this.returnScreen));
  }
  if(b.notice||this.platform.campaign.notice||this.platform.growth.notice)this.text('notice',b.notice||this.platform.campaign.notice||this.platform.growth.notice,0,-626-edge,18,RED,690,30);
 }
 private loadout(y:number){const g=this.platform.growth;g.data.unlockedWeapons.forEach((id,i)=>this.button('weapon-'+id,(g.data.equippedWeapon===id?'✓ ':'')+WEAPONS[id].label,y,()=>{g.equipWeapon(id);this.show(this.screen);},-140+i*280,250));g.data.unlockedCompanions.forEach((id,i)=>this.button('companion-'+id,(g.data.equippedCompanion===id?'✓ ':'')+CAST[id].name,y-100,()=>{g.equipCompanion(id);this.show(this.screen);},-200+i*200,186));}
 private openTransition(id:TransitionId){this.transitionId=id;this.level=CAMPAIGN.transitions.findIndex(t=>t.id===id);this.transitionAge=0;this.transitionDone=false;this.journey?.dispose();this.show('transition');}
 private completeTransition(){if(this.transitionDone||!this.platform.campaign.complete(this.transitionId))return;this.transitionDone=true;this.transitionAge=0;this.platform.sound('gather');this.show('transition');}
 private begin(index=this.level){if(!canStart(this.platform.book,index,ArtSprites.ready)){this.message='本关尚未解锁或资源未就绪';return;}this.level=index;this.combatStats={meleeHits:0,meleeDamage:0,waveHits:0,companionHits:0,upgrades:0,awakenings:0,volleys:0,lastMelee:null};this.firstVictory=false;this.newUnlocks=[];this.notices.clear();this.finishAge=0;this.platform.stopEffects();this.battle.clear();this.journey?.dispose();this.journey=new Journey(LEVELS[this.level],{appearance:rankStage(this.platform.book),weapon:this.platform.growth.data.equippedWeapon,companion:this.platform.growth.data.equippedCompanion});this.message=this.platform.growth.data.equippedCompanion&&!this.journey.companion?`${CAST[this.platform.growth.data.equippedCompanion].name}本场待命`:`本次出征：${this.journey.count}人`;this.messageTime=3;this.tutorialUntil=5;this.dragged=false;this.frameTimes=[];this.show('battle');this.platform.syncAudio();}
 private leave(){this.battle.clear();this.journey?.dispose();this.platform.syncAudio(false);this.show('chapters');}
 private pause(){if(!this.journey)return;this.journey.pause();this.platform.syncAudio(false);this.show('pause');}
 private setText(id:string,t:string){const l=this.ui.getChildByName(id)?.getComponent(Label);if(l)l.string=t;}
 update(dt:number){if(!this.loaded)return;this.wallFrames++;this.fpsElapsed+=dt;if(this.fpsElapsed>=1){this.fps=this.wallFrames/this.fpsElapsed;this.wallFrames=0;this.fpsElapsed=0;}
  if(this.screen==='transition'||this.screen==='camp'||this.screen==='meeting'||this.screen==='loadout'){
   if(!this.platform.hidden&&!this.campPaused)this.transitionAge+=dt;
   const stage=this.screen==='transition'?this.level:this.screen==='loadout'?Math.max(0,Math.min(2,rankStage(this.platform.book)-1)):2;
   this.battle.camp(stage,this.screen!=='transition'||this.transitionDone,this.transitionAge,this.flagDrag,this.screen==='meeting',this.platform.growth.data.equippedWeapon);
   if(this.screen==='transition'&&this.transitionDone&&this.transitionAge>=1.2&&!this.platform.hidden&&!this.campPaused){if(this.level<2)this.begin(this.level+1);else this.show(this.platform.campaign.data.seen.zhaoyunMeeting?'camp':'meeting');}
  }
  if(this.screen==='result'&&this.promotionView&&!this.platform.hidden){this.promotionTime+=dt;this.promotionView.portrait(rankStage(this.platform.book),this.firstVictory?this.promotionTime:2,this.level,this.platform.growth.data.equippedWeapon);}
  if(this.screen==='preview'){if(!this.previewPaused&&!this.platform.hidden)this.previewState.time+=dt;this.battle.preview(this.previewState);}
  if(this.screen==='battle'&&this.journey){const j=this.journey;this.frameTimes.push(dt);if(this.frameTimes.length>7200)this.frameTimes.shift();j.advance(dt);const events=j.drainFeedback();this.battle.effects.accept(events,j.elapsed);this.battle.volleys.accept(events);let hit=false;for(const e of events){if(e.kind==='shot'){this.combatStats.volleys++;continue;}if(e.kind==='meleeHit'){this.combatStats.meleeHits++;this.combatStats.meleeDamage+=e.amount;this.combatStats.lastMelee=e;}if(e.kind==='waveHit'){this.combatStats.waveHits++;}if((e.kind==='waveHit'||e.kind==='meleeHit')&&e.sourceId!=='hero')this.combatStats.companionHits++;if(e.kind==='upgrade'){this.combatStats.upgrades++;this.notices.push(`击败精锐 · ${WEAPONS[j.weapon].label}${['一','二','三'][e.amount-1]}阶`,1.2,2);this.platform.sound('gather');continue;}if(e.kind==='awaken'){this.combatStats.awakenings++;this.notices.push('破阵觉醒 · 6秒',1.2,2);this.platform.sound('gather');continue;}if(e.kind==='hit'||e.kind==='meleeHit'||e.kind==='waveHit'){hit=true;continue;}if(e.kind.startsWith('melee'))continue;this.platform.sound(e.kind==='warn'?(this.level===2?'break':this.level===1?'hit':'warn'):e.kind);if(e.kind==='warn')this.notices.push('当心'+WEAPONS[e.weaponId??j.bossWarning?.weaponId??'bow'].label,1,3);if(e.kind==='gather'){this.notices.push(`增兵 +${e.amount}`,1,1);}if(e.kind==='hurt'){this.notices.push(`损失 ${e.amount} 人`,1.5,3);this.platform.vibrate();}}
   if(hit)this.platform.sound('hit');this.battle.render(j,rankStage(this.platform.book),this.finishAge);this.setText('count',`兵力 ${j.count}`);this.setText('weapon-tier',`${j.weapon==='blade'?'刀':'枪'} · ${['Ⅰ','Ⅱ','Ⅲ'][j.tier-1]}`);this.setText('awakening-status',j.awakeningRemaining>0?'破阵觉醒':'');this.setText('companion-status',j.companionActive?CAST[j.companion!].name+'随军':'');this.setText('progress',j.phase==='boss'?j.level.bossName:`行路 ${Math.floor(j.z/j.level.duration*100)}%`);this.messageTime=Math.max(0,this.messageTime-dt);this.setText('feedback',this.notices.advance(dt)||(this.messageTime>0?this.message:''));this.setText('tutorial',j.elapsed<3?CAMPAIGN.levels[this.level].opening.map(l=>l.speaker+'：'+l.line).join('  '):j.elapsed<this.tutorialUntil+3?CAMPAIGN.tutorials.move:'');
   if(j.finished){if(this.finishAge===0){this.platform.stopEffects();if(j.phase==='won'){this.firstVictory=!this.platform.book.data.cleared[j.level.id];this.platform.book.win(this.level,j.count);const oldWeapons=[...this.platform.growth.data.unlockedWeapons],oldCompanions=[...this.platform.growth.data.unlockedCompanions];this.platform.growth.reconcile();this.newUnlocks=[...this.platform.growth.data.unlockedWeapons.filter(id=>oldWeapons.indexOf(id)<0).map(id=>WEAPONS[id].label),...this.platform.growth.data.unlockedCompanions.filter(id=>oldCompanions.indexOf(id)<0).map(id=>CAST[id].name+(id==='zhao_yun_guest'?'同行助阵':'随军'))];}}this.finishAge+=dt;if(j.phase==='won'&&this.finishAge<.7)return;this.battle.clear();if(j.phase==='won')this.platform.sound('gather');this.show('result');}
  }
 }
 private snapshot(){const j=this.journey;let nodes=0;const walk=(n:Node)=>{nodes++;n.children.forEach(walk)};walk(this.node);return JSON.parse(JSON.stringify({version:'v051-rc1',combatStats:this.combatStats,resourcesReady:ArtSprites.ready,appearance:rankStage(this.platform.book),firstVictory:this.firstVictory,engine:'Cocos Creator 3.8.8',screen:this.screen,level:this.level,texts:this.ui.children.filter(n=>n.getComponent(Label)).map(n=>({id:n.name,text:n.getComponent(Label)!.string})),buttons:this.hits.map(({id,x,y,w,h})=>({id,x,y,w,h})),save:this.platform.book.data,campaign:this.platform.campaign.data,growth:this.platform.growth.data,transition:{id:this.transitionId,done:this.transitionDone,age:this.transitionAge},rank:CAMPAIGN.rankLabels[rankStage(this.platform.book)],notice:this.platform.book.notice,nodes,pool:this.battle.poolSize,presentation:this.battle.diagnostics,audio:this.platform.audioState,preview:this.screen==='preview'?{...this.previewState,paused:this.previewPaused}:null,fps:this.fps,meanFPS:this.frameTimes.length/this.frameTimes.reduce((a,b)=>a+b,0),journey:j?{phase:j.phase,paused:j.paused,count:j.count,x:j.x,target:j.target,z:j.z,elapsed:j.elapsed,duration:j.level.duration,damage:j.damage,damageTotals:j.damageTotals,heroGeometry:j.heroGeometry,companionGeometry:j.companionGeometry,visible:j.visibleCount,bossHP:j.bossHP,bossDepth:j.bossDepth,melee:j.melee,weapon:j.weapon,tier:j.tier,awakeningUsed:j.awakeningUsed,awakeningRemaining:j.awakeningRemaining,upgradeRewards:Array.from(j.upgradeRewards),waves:j.waves,wavePeak:j.wavePeak,companion:j.companion,companionActive:j.companionActive,companionAttack:j.companionAttack,archerCount:j.archerCount,bossWarning:j.bossWarning,warnings:j.warnings,cause:j.cause,arrows:j.arrows.length,rows:j.level.rows.filter(r=>!j.usedRows.has(r.id)),obstacles:j.obstacles.filter(o=>!o.dead&&!o.resolved),usedRows:Array.from(j.usedRows)}:null}));}
 onDestroy(){this.journey?.dispose();this.platform?.destroy();input.off(Input.EventType.TOUCH_START,this.touchStart);input.off(Input.EventType.TOUCH_MOVE,this.touchMove);input.off(Input.EventType.TOUCH_END,this.touchEnd);input.off(Input.EventType.TOUCH_CANCEL,this.touchCancel);delete(globalThis as any).__YLCG__;}
}
