import {open,E} from './browser.mjs';import fs from 'node:fs';import assert from 'node:assert/strict';
const t=await open('interactions',process.argv[2]?360:375,process.argv[2]?640:667),rows=[];
const saveKey=s=>JSON.stringify(s.save),note=async(name)=>{const s=await t.capture('check-'+name);rows.push({name,screen:s.screen,scroll:s.ui.scroll,build:s.build,data:s.save,details:{viewport:s.ui.viewport,layers:s.ui.layers,texts:s.ui.texts}});return s;};
async function reverseDrag(hit){const x=hit.x+hit.w/2,y=hit.y+hit.h/2;await t.cd.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:7}]});for(const dy of [-14,0])await t.cd.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+dy,id:7}]});await t.cd.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await t.p.waitForTimeout(160);}
try{
 await t.goto('prepare:weapons');let s=await t.snap();const before=saveKey(s);await reverseDrag(s.buttons.find(x=>x.id==='select-spear'));assert.equal(saveKey(await t.snap()),before);await note('Q03-reverse-drag');
 await t.command('scroll',120);s=await t.snap();const pos=s.ui.scroll;const detail=s.buttons.find(x=>x.id.startsWith('detail-'));await t.tap(detail.id);await note('Q07-detail');await t.tap('back');assert.equal((await t.snap()).ui.scroll,pos);await note('Q07-return');
 await t.tap('tab-treasures');await t.command('scroll',70);const treasurePos=(await t.snap()).ui.scroll;await t.tap('tab-weapons');assert.equal((await t.snap()).ui.scroll,pos);await t.tap('tab-treasures');assert.equal((await t.snap()).ui.scroll,treasurePos);await note('Q07-tabs');
 await t.goto('collection:people');await t.tap('next-page');await t.tap('filter-seen');s=await t.snap();const count=s.buttons.filter(b=>b.id.startsWith('person-')).length;assert.ok(count>0);const card=s.buttons.find(b=>b.id.startsWith('person-'));await t.tap(card.id);await t.tap('back');assert.equal((await t.snap()).ui.filter,'seen');await note('Q07-collection-return');
 await t.goto('prepare:weapons');await t.command('long-content',Array.from({length:70},(_,i)=>`第${i+1}行 · 完整经历、共鸣与军功说明保留`).join('\n'));s=await t.snap();assert.ok(s.ui.items[0].bounds.h>s.ui.viewport.bottom-s.ui.viewport.top);await t.command('scroll',8);assert.ok((await t.snap()).ui.items.length);await note('Q02-tall-8');await t.command('scroll',99999);await note('Q02-tall-end');
 for(const fixture of ['prepare:weapons','person:zhao','item:liannu','milestone:9','result']){await t.goto(fixture);await t.p.waitForTimeout(1200);s=await t.snap();for(const delta of [1,7,40]){await t.command('scroll',delta);await note('Q01-'+fixture.replace(':','-')+'-'+delta);}await t.command('scroll',99999);await note('Q01-'+fixture.replace(':','-')+'-end');await t.command('scroll',-99999);assert.equal((await t.snap()).ui.scroll,0);}
 await t.goto('milestone:9');await t.p.waitForTimeout(1500);await t.command('scroll',130);s=await t.snap();const reward=JSON.stringify(s.reward),xp=s.save.xp,rpos=s.ui.scroll;await t.tap('reward-primary');await t.tap('back');s=await t.snap();assert.equal(s.ui.scroll,rpos);assert.equal(JSON.stringify(s.reward),reward);assert.equal(s.save.xp,xp);await note('Q12-reward-return');await t.tap('reward-done');assert.equal((await t.snap()).save.xp,xp);assert.equal((await t.snap()).reward,null);
 await t.goto('map');s=await t.snap();const map=s.map.scroll;await t.tap('map-detail');assert.equal((await t.snap()).map.scroll,map);await note('Q13-map-expanded');await t.tap('map-detail');assert.equal((await t.snap()).map.scroll,map);
 await t.goto('result');s=await note('Q13-replay-context');assert.equal(s.chapter,10);assert.equal(s.save.cleared.length,13);assert.ok(s.ui.texts.some(t=>t.text.includes('全局')));await t.tap('next');await t.tap('prepare-next');assert.equal((await t.snap()).chapter,11);
 await t.goto('settings');s=await t.snap();const old=s.ui.reducedMotion;await t.tap('motion');assert.equal((await t.snap()).ui.reducedMotion,!old);await t.goto('settings');assert.equal((await t.snap()).ui.reducedMotion,!old);await t.command('settings-failure');await t.tap('motion');s=await note('Q14-setting-failure');assert.equal(s.ui.reducedMotion,!old);assert.ok(s.ui.texts.some(t=>t.text.includes('保存失败')));
 // The same Cocos MenuLayers are repeatedly entered through genuine buttons, not reconstructed.
 await t.goto('home');for(let i=0;i<3;i++){await t.tap('start');await t.tap('view-lineup');await t.tap('back');await t.tap('back');}let pools=(await t.snap()).ui.layers.layers.map(p=>p.created);for(let i=0;i<20;i++){await t.tap('start');await t.tap('view-lineup');await t.tap('back');await t.tap('back');}assert.deepEqual((await t.snap()).ui.layers.layers.map(p=>p.created),pools);await note('Q06-pool-20');
 for(const stage of ['icon','label','viewport']){await t.goto('prepare:weapons');s=await t.snap();const original=saveKey(s);await t.command('menu-fault',stage);s=await note('Q06-fault-'+stage);assert.equal(s.screen,'render-error');assert.ok(s.ui.layers.layers.every(p=>p.active===0&&p.submissions===0));assert.equal(s.ui.layers.maskActive,false);assert.deepEqual(s.buttons.map(b=>b.id),['retry-render','safe-home']);assert.equal(saveKey(s),original);await t.tap('retry-render');await t.p.waitForFunction(()=>__YLCG__.snapshot().screen==='prepare');assert.equal(saveKey(await t.snap()),original);await note('Q06-retry-'+stage);}
 assert.deepEqual(t.errors,[]);
}finally{fs.writeFileSync(E+'/interaction-checks.json',JSON.stringify({rows,pageErrors:t.errors,scope:'Actual Cocos WebGL with Chromium touch/CDP; memory-only fixtures and isolated setting writes; not native device'},null,2));await t.close();}
