import {open,E} from './browser.mjs';import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const cases=[['U01','home'],['U01-new','new'],['U01-complete','complete'],['U02','map'],['U03','prepare:weapons'],['U03-support','prepare:support'],['U03-treasures','prepare:treasures'],['U04','collection:people'],['U04-weapons','collection:weapons'],['U05','person:zhao'],['U05-long','person:zhuge'],['U05-unknown','person:lukang'],['U06','item:liannu'],['U06-treasure','item:yuxi'],['U07','result'],['U08','reward:0'],['U09-upper','milestone:9'],['U09-final','milestone:19'],['U10','defeat'],['U11','pause'],['U12','settings'],['U13-migration','migration'],['U13-save','save-error'],['U13-resource','error']];
const acceptanceFiles=['tools/ui-polish-r2/pages.mjs','tools/ui-polish-r2/browser.mjs','assets/scripts/formal/FormalGame.ts'];const acceptanceFingerprint=crypto.createHash('sha256').update(acceptanceFiles.map(p=>p+':'+crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')).join('\n')+JSON.stringify(cases)).digest('hex');
const prior=fs.existsSync(E+'/page-matrix.json')?JSON.parse(fs.readFileSync(E+'/page-matrix.json')).results:[];const results=[],expected=JSON.parse(fs.readFileSync(E+'/web-manifest.json')).code_fingerprint;
const sizes=process.argv[2]?[process.argv[2].split('x').map(Number)]:[[375,667],[402,874],[360,640],[430,932]];for(const [width,height] of sizes){
 const t=await open('matrix',width,height);try{for(const [id,fixture] of cases){await t.goto(fixture);await t.p.waitForTimeout(/reward|milestone|migration/.test(fixture)?1100:60);
  for(const safe of [false,...(['U02','U03','U04','U05-long','U06','U09-upper','U09-final','U12'].includes(id)?[true]:[])]){
   const kept=prior.find(r=>r.id===id&&r.width===width&&r.height===height&&((r.safeInsets!=='platform default')===safe)&&r.build.code_fingerprint===expected&&r.acceptanceFingerprint===acceptanceFingerprint&&r.fixture===fixture&&r.failures.length===0);if(kept){results.push(kept);continue;}if(safe)await t.command('safe-insets',{top:44,bottom:34});let s=await t.capture(`${id}-${width}x${height}${safe?'-safe44-34':''}`);
   const failures=[];if(fixture.startsWith('person:')){const id=fixture.split(':')[1];if(!s.person?.valid||s.person.id!==id)failures.push('invalid person coverage '+id);if(id==='zhuge'){if(!s.person.known||s.person.title!=='诸葛亮'||!s.person.profile?.[3]?.includes('隆中'))failures.push('expected known zhuge/title/body');if(!s.ui.texts.some(t=>t.text.includes('诸葛亮')))failures.push('person title not rendered');}}assert.equal(s.build.code_fingerprint,expected);for(const b of s.buttons){if(b.x<-.1||b.y<-.1||b.x+b.w>width+.2||b.y+b.h>height+.2)failures.push('outside '+b.id);if(b.w<48||b.h<48)failures.push('small '+b.id);}
   const overflow=s.ui.texts.filter(t=>{const b=t.bounds,r=t.container;return r&&(b.x<r.x-.3||b.y<r.y-.3||b.x+b.w>r.x+r.w+.3||b.y+b.h>r.y+r.h+.3);});
   if(s.missingArt.length||s.renderErrors.length)failures.push('render errors');if(overflow.length)failures.push(...overflow.map(t=>'text '+t.text));
   const complete=s.ui.items.filter(i=>i.bounds.y>=s.ui.viewport.top&&i.bounds.y+i.bounds.h<=s.ui.viewport.bottom);
   if(id==='U03'&&[375,360].includes(width)&&complete.length<2)failures.push('less than 2 complete choices');
   if(s.ui.maxScroll>0){await t.command('scroll',s.ui.maxScroll);await t.capture(`${id}-bottom-${width}x${height}${safe?'-safe44-34':''}`);await t.command('scroll',-s.ui.maxScroll);}
   results.push({id,fixture,acceptanceFingerprint,person:s.person,width,height,safeInsets:safe?{top:44,bottom:34}:'platform default',screen:s.screen,data_bound:true,failures,overflow,completeChoices:complete.length,build:s.build});console.log(id,width,safe?'safe':'default',failures.length?'FAIL '+failures.join(','):'ok');
  }
 }assert.deepEqual(t.errors,[]);}finally{fs.writeFileSync(E+'/page-matrix-'+width+'x'+height+'.json',JSON.stringify({results,scope:'Actual Cocos WebGL pixels and measured text, isolated memory save; safe44/34 simulated, not native/phone'},null,2));await t.close();}
}
assert.deepEqual(results.flatMap(x=>x.failures),[]);
