"""Deterministic whole-component extraction of generated casualty sprites; no painted pixels."""
from pathlib import Path
from collections import deque
import hashlib,json,uuid,sys
import numpy as np
from PIL import Image,ImageFilter,ImageDraw

P=Path(__file__).resolve().parent
R=P.parents[2]
im=Image.open(P/'source.png').convert('RGBA');pix=np.array(im)
mask=pix[:,:,3]>32;h,w=mask.shape;seen=np.zeros_like(mask);components=[]
for sy,sx in zip(*np.where(mask)):
 if seen[sy,sx]:continue
 q=deque([(int(sx),int(sy))]);seen[sy,sx]=1;xy=[]
 while q:
  x,y=q.popleft();xy.append((x,y))
  for u,v in ((x-1,y),(x+1,y),(x,y-1),(x,y+1)):
   if 0<=u<w and 0<=v<h and mask[v,u] and not seen[v,u]:seen[v,u]=1;q.append((u,v))
 if len(xy)>50:
  a=np.array(xy);components.append({'xy':a,'box':[int(a[:,0].min()),int(a[:,1].min()),int(a[:,0].max()+1),int(a[:,1].max()+1)]})
assert len(components)==16,len(components)
# Four source columns x three rows. Fallen bodies cross nominal cell borders.
# Separate bows and broken mechanism wood are explicitly owned, never discarded
# by a crop or mistaken for the adjacent actor's weapon.
specs=[
 ('enemy_archer_hit',[0],(231,350),285),('enemy_archer_fallen',[3,4],(527,349),285),
 ('enemy_shield_hit',[1],(887,343),283),('enemy_shield_fallen',[2],(1222,332),283),
 ('enemy_guard_hit',[6],(211,707),298),('enemy_guard_fallen',[8],(545,708),298),
 ('enemy_banner_hit',[5],(920,714),250),('enemy_banner_fallen',[7],(1230,706),250),
 ('enemy_mechanism_hit',[10],(195,1029),283),('enemy_mechanism_fallen',[11,13,15],(540,1028),283),
 ('friendly_archer_hit',[9],(867,1038),255),('friendly_archer_fallen',[12,14],(1235,1040),255),
]
atlas=Image.new('RGBA',(1792,1344));frames={};rows=[]
for i,(name,owned,(ax,ay),bh) in enumerate(specs):
 own=np.zeros((h,w),dtype=np.uint8)
 for ci in owned:
  a=components[ci]['xy'];own[a[:,1],a[:,0]]=255
 alpha=np.minimum(np.array(Image.fromarray(own).filter(ImageFilter.MaxFilter(3))),pix[:,:,3])
 actor=Image.fromarray(np.dstack((pix[:,:,:3],alpha)).astype(np.uint8))
 cell=actor.crop((ax-224,ay-416,ax+224,ay+32))
 assert np.count_nonzero(np.array(cell)[:,:,3])==np.count_nonzero(alpha),(name,'actor cropped')
 atlas.alpha_composite(cell,((i%4)*448,(i//4)*448))
 key='bf_'+name
 frames[key]={'s':'bf_special_casualties','r':[(i%4)*448,(i//4)*448,448,448],'a':[.5,32/448],'bh':bh}
 rows.append({'key':key,'sourceAnchor':[ax,ay],'ownedComponents':owned,'componentBounds':[components[j]['box'] for j in owned],'alphaBounds':cell.getbbox(),'refH':bh,'normalization':'fixed standing body reference shared by hit and fallen; fallen is never enlarged to standing crop height'})
out=R/'assets/resources/formal20260927/feel-special-casualties.png';atlas.save(out)
meta=json.loads((out.parent/'feel-enemies.png.meta').read_text());uid=str(uuid.uuid5(uuid.NAMESPACE_URL,'yilu/battle-feel-20261004/special-casualties'))
meta['uuid']=uid;meta['userData']['redirect']=uid+'@6c48a';sub=meta['subMetas']['6c48a'];sub['uuid']=uid+'@6c48a';sub['displayName']=out.stem;sub['userData']['imageUuidOrDatabaseUri']=uid
out.with_suffix('.png.meta').write_text(json.dumps(meta,indent=2)+'\n')
art={'sheets':{'bf_special_casualties':'formal20260927/feel-special-casualties'},'frames':frames}
(P/'frames.json').write_text(json.dumps(art,indent=2)+'\n')
(P/'frame-review.json').write_text(json.dumps({'sourceSha256':hashlib.sha256((P/'source.png').read_bytes()).hexdigest(),'outputSha256':hashlib.sha256(out.read_bytes()).hexdigest(),'frames':rows,'wholeSourceComponents':len(components),'retainedComponents':sum(len(v[1]) for v in specs),'manualPaint':False},indent=2)+'\n')
board=Image.new('RGB',atlas.size,'#414A37');board.paste(atlas,(0,0),atlas);d=ImageDraw.Draw(board)
for i,row in enumerate(rows):
 x,y=i%4*448,i//4*448;d.text((x+6,y+6),row['key'],fill='white');d.line((x+224-8,y+416,x+224+8,y+416),fill='#77D5D7')
board.save(P/'contact.png')
if '--append' in sys.argv:
 module=R/'assets/scripts/formal/BattleFeelEnemyArt.ts';s=module.read_text();marker='// BEGIN SPECIAL CASUALTIES GENERATED BY special-casualties/pack.py'
 s=s.split(marker)[0].rstrip()+'\n'+marker+'\n'
 s+='Object.assign(BATTLE_FEEL_ENEMY_ART.sheets,'+json.dumps(art['sheets'],separators=(',',':'))+');\n'
 s+='Object.assign(BATTLE_FEEL_ENEMY_ART.frames,'+json.dumps(frames,separators=(',',':'))+');\n';module.write_text(s)
print('packed',len(frames),'complete sprites; module appended:', '--append' in sys.argv)
