# -*- coding: utf-8 -*-
from pathlib import Path
import json, datetime, shutil
r=Path(__file__).resolve().parents[1]; task='BATTLE-REWORK-20260925-FIX1'; e=r/'evidence'/task; d=r/'docs'/task; d.mkdir(exist_ok=True)
load=lambda p:json.loads(p.read_text()); save=lambda p,x:p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
f=load(e/'fix-checks-latest.json'); f['dir']=str(Path(f['pages'][0]['png']).parent); n=load(e/'natural-flow.json'); b=load(e/'BUILD_ID.json'); w=load(e/'wechat-package.json'); assert f['passed'] and n['passed']
old=load(r/'docs/BATTLE-REWORK-20260925/REVIEW_RESULTS.json'); report={k:v for k,v in old.items() if k in ['status_enum','checks','reference_comparison']}
report.update(task_id=task,kind='targeted_fix_review',new_build_id=b['runtime'],source_fingerprint=b['gameSource']['sha256'],functional_status='passed',visual_status='passed',physical_device_status='blocked',local_next_step_ready=True,reviewed_at=datetime.datetime.now().astimezone().isoformat(),scope='Local browser visual defect closure; physical-device acceptance remains separate and unverified. No claim of identical original artwork or formulas.')
for c in report['checks']:
 c['evidence_origin']='BATTLE-REWORK-20260925 prior verified result, reused only where source/assets unchanged; FIX1 PRESERVED_CONTRACTS.json and SOURCE_DIFF.json'
 if c['id']=='V11':c.update(status='passed',evidence_origin=task,evidence_type='actual_browser_screenshots_and_geometry',evidence_paths=['fix-checks-latest.json',f['dir'],'battle-showcase.mp4'],observations='通知占用顶部信息卡装备行，到期恢复装备文字；390×844和375×667三个同状态模型一致。接触态8个连续门逐一保留，8个+1侧签有连线指向真实门，标签互不交叠，低门横梁不再纵向堆叠。',limitations='桌面移动视口可读性通过；物理手机触控与文字观感仍待真机。')
 if c['id']=='V12':c.update(status='passed',evidence_origin=task,evidence_paths=['natural-flow.json','final-three-levels.webm','final-three-levels.mp4','battle-showcase.mp4','CLIPS.json'],observations='修复构建仅一次自然三关通过；真实触摸输入、暂停、选装、三次旗帜过渡、会盟、回营和存档重载通过，现场动作音效，未恢复音乐。结尾人数：'+str([x['count'] for x in n['runs']]),limitations='自动策略驱动真实触摸；不是人工手感或实体手机验收。')
 if c['id']=='V13':c.update(status='passed',evidence_origin=task,evidence_paths=['wechat-package.json','ASSET_BUDGET-web-mobile.json','ASSET_BUDGET-wechatgame.json','natural-flow.json','BUILD_ID.json'],observations=f"新Web/微信构建成功。微信本地{w['totalBytes']}字节，预算余量{w['marginBytes']}字节。自然三关p95(ms)："+str([x['frameTiming']['p95'] for x in n['runs']]),limitations='工程本地预算；未上传。桌面录像性能不能当真机性能，未做默认十局长测。')
 if c['id']=='V14':c['evidence_origin']='No physical device evidence';c['observations']='尚无实体手机验证。本轮本地缺陷修复已通过，可以进入手机实测；不将未执行项目改成通过。'
report['reference_comparison']['remaining_gaps']=['参考图的城寨围合密度仍属于风格差异；当前功能映射不采用封闭三跑道。']
save(d/'REVIEW_RESULTS.json',report)
verification=dict(task=task,runtime=b['runtime'],typecheck='passed',relatedTests=dict(passed=71,failed=0,log='related-checks.log'),focusedChecks=dict(passed=f['passed'],count=len(f['checks']),file='fix-checks-latest.json'),natural=dict(passed=n['passed'],runs=[dict(level=x['level'],seconds=x['seconds'],count=x['count']) for x in n['runs']],file='natural-flow.json'),corePreserved=load(e/'PRESERVED_CONTRACTS.json')['passed'],localBuilds='passed',physicalDevice='not performed',uploaded=False)
save(e/'VERIFICATION.json',verification); save(d/'VERIFICATION.json',verification); shutil.copy2(e/'BUILD_ID.json',d/'BUILD_ID.json')
(d/'KNOWN_GAPS.md').write_text('''# 当前边界\n\n上轮V11的通知遮挡、密集连续门可读性缺陷已用修复版真实画面和逐门断言验证通过。核心战场素材齐备。\n\n仍未进行实体手机的触控、安全区/微信胶囊、声音听感、切后台恢复与持续发热/性能验收；V14如实保留待实测，不是继续挂着的已知代码缺陷。浏览器不能代替这些证据。\n\n本轮仅本地Web/微信构建，未上传、选体验版或发布。旧失败记录和上版包保留。本地验收通过不代表逐像素还原参考，未知原版公式依旧为明确工程初值。\n''')
(d/'00_START_WITH_CODEX.md').write_text('''# FIX1修复版入口\n\n版本 `0.9.2-battle20260925.1` / `battle-rework-20260925-fix1`。本包是当前有未提交修改的完整工作区快照，不是Git HEAD副本。继续开发请保护所有既有修改与用户存档。\n\n双击 `启动一路长歌.command`，需要Node18+，预构建试玩无需安装npm或Cocos。开发构建使用Cocos Creator3.8.8。微信分享包AppID置空，仅本地原工程保留原有身份。\n\n改动仅战斗呈现：通知收进顶部装备行，结束恢复；连续+1门低横梁、逐门侧签与连接线，世界标签安全区按实际HUD计算。门真实位置、碰撞、奖励、队形、三关和存档不变，菜单与素材保持。\n\n看同目录 FINAL_REVIEW.md、REVIEW_RESULTS.json 和完整 evidence/BATTLE-REWORK-20260925-FIX1。核验小包包含实际前后PNG和30秒原速MP4；完整包包含全长自然三关MP4与原始WebM。旧任务证据保留在 evidence/BATTLE-REWORK-20260925，早于战斗返工的历史大录像未重复装包。\n\n本地修复项已通过，可进入手机实测。实体手机验收未执行，不能标成通过；未上传或发布。\n''')
(d/'FINAL_REVIEW.md').write_text(f'''# 修复结果\n\n两项实际缺陷已修复：\n- 顶部通知与装备文字共用已保留的信息行，通知到期恢复装备，去掉遮挡战场的横条。\n- 连续门高度从78降到36设计单位，保留52单位真实间距；每道门有独立+1侧签及连线，接触态8/8可见，未减少门数或移动碰撞。\n\n{len(f['checks'])}项定向断言通过：两尺寸、三个同状态的模型逐字段相等，标签矩形不交叠、通知和装备恢复。71项相关测试通过。新构建唯一一次自然三关通过，人数{[x['count'] for x in n['runs']]}，暂停、关间流程、会盟与存档重载通过。素材与核心源码校验不变。\n\n前后截图是明确的同状态夹具；自然录像是实时真实触摸输入，未注入血量、兵员或时间。30秒展示仅从同一次全程录像原速剪出，保留现场SFX，无BGM。\n\n本地可修复项通过，V14实体手机证据待实测，未改为虚假全绿。\n''')
base='/'+f['dir']; eb='/evidence/'+task
pairs=''.join(f'<article><h3>{name}</h3><div class="pair"><figure><img src="{base}/{name}-previous.png"><figcaption>修复前 · 实际画面</figcaption></figure><figure><img src="{base}/390x844-{name}.png"><figcaption>修复后 · 相同模型状态</figcaption></figure></div></article>' for name in ['normal','gates-crates','contact'])
extra=''.join(f'<figure><img src="{base}/{name}.png"><figcaption>{name}</figcaption></figure>' for name in ['390x844-notice','375x667-contact','375x667-notice','375x667-equipment-restored'])
html=f'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>一路长歌 FIX1 修复核验</title><style>body{{margin:24px auto;padding:0 20px;max-width:1100px;background:#152737;color:#f0e7d1;font:16px/1.6 system-ui}}a{{color:#ebc36c}}h1{{font-size:27px}}.badge{{color:#90deb4}}.pair,.extras{{display:flex;gap:18px;flex-wrap:wrap}}figure{{margin:0 0 18px;max-width:390px;flex:1;min-width:220px}}img{{width:100%;height:auto}}video{{width:390px;max-width:100%;background:#000}}iframe{{border:0;width:390px;max-width:100%;height:844px}}article{{border-top:1px solid #50606a;margin-top:24px}}code{{overflow-wrap:anywhere}}</style><h1>战斗返工 · FIX1 已修复</h1><p class="badge">本地修复项通过 · 可以进入手机实测</p><p>通知已移入顶部信息栏；连续门逐门可读。{len(f['checks'])}项定向检查、71项相关检查和一次自然三关通过。实体手机验收仍未执行，不冒充全绿。</p><p><a href="/play/?v=battle-rework-20260925-fix1">打开修复版试玩</a> · <a href="./FINAL_REVIEW.md">结果说明</a> · <a href="./REVIEW_RESULTS.json">逐项核验</a> · <a href="./KNOWN_GAPS.md">待真机项</a></p><p><code>battle-rework-20260925-fix1</code></p><h2>相同状态前后</h2><p>同关卡、装备、模拟tick、队伍和目标。属于可复现夹具截图，三态模型逐字段一致。</p>{pairs}<h2>通知与短屏实拍</h2><div class="extras">{extra}</div><h2>30秒原速片段</h2><video controls playsinline preload="metadata" src="{eb}/battle-showcase.mp4"></video><p>来自下面同一次三关录像，5段×6秒，原速与现场音效，无配乐。</p><h2>完整自然三关</h2><video controls playsinline preload="metadata" src="{eb}/final-three-levels.mp4"></video><p>真实触摸策略操作，包含暂停、选装、旗帜过渡、会盟与回营。</p><h2>直接操作</h2><iframe title="修复版真实Cocos" src="/?v=battle-rework-20260925-fix1" allow="autoplay; fullscreen"></iframe></html>'''
(d/'index.html').write_text(html)
print(json.dumps(verification,ensure_ascii=False))
