import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFileSync,readFileSync} from 'node:fs';import {spawnSync} from 'node:child_process';
 const native=spawnSync(process.execPath,['tools/browser-lifecycle.mjs'],{encoding:'utf8',timeout:60000});console.log(native.stdout);assert.equal(native.status,0,native.stderr);
const context=await chromium.launchPersistentContext('.cache/browser-edge',{executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:false,viewport:{width:390,height:844},hasTouch:true,isMobile:true});
const page=await context.newPage();let checks=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));
const snap=()=>page.evaluate(()=>globalThis.__YLCG__.snapshot());
const boot=async()=>{await page.goto('http://127.0.0.1:43187');await page.bringToFront();await page.waitForFunction(()=>globalThis.__YLCG__,null,{timeout:30000});};
async function position(x,y){const b=await page.locator('canvas').boundingBox();const scale=Math.min(b.width/720,b.height/1280);return{x:b.x+b.width/2+x*scale,y:b.y+b.height/2-y*scale};}
const tap=async id=>{const s=await snap(),b=s.buttons.find(b=>b.id===id);assert.ok(b,`${s.screen}: ${id}`);const p=await position(b.x,b.y);await page.touchscreen.tap(p.x,p.y);await page.waitForTimeout(100)};
try{
 await boot();await page.evaluate(()=>localStorage.setItem('yilu-changge-v1','{broken'));await page.reload();await page.waitForFunction(()=>globalThis.__YLCG__);assert.match((await snap()).notice,/默认/);checks.push('坏档恢复默认并提示');await page.screenshot({path:'evidence/bad-save.png'});
 await tap('settings');await tap('music');await tap('sfx');await tap('vibration');await tap('return');await page.reload();await page.waitForFunction(()=>globalThis.__YLCG__);assert.deepEqual((await snap()).save.settings,{music:false,sfx:false,vibration:false});checks.push('三个设置开关保存并恢复');
 await tap('chapters');await tap('level0');await tap('start');assert.equal((await snap()).screen,'battle');checks.push('手机比例触摸点击跳剧情直接开战');
 const cdp=await context.newCDPSession(page);const p=await position(0,-100),q=await position(200,-100);
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p.x,y:p.y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:q.x,y:q.y,id:1}]});await page.waitForTimeout(500);assert.ok((await snap()).journey.x>.5);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});checks.push('真实单指拖动改变横向位置');
 const life=JSON.parse(readFileSync('evidence/browser-lifecycle.json','utf8'));assert.equal(life.background.hidden,true,'Actual browser page must be hidden');assert.equal(life.background.screen,'pause');assert.ok(life.returnedPaused&&life.explicitContinueRestoresProgress);await page.bringToFront();if((await snap()).screen==='pause')await tap('continue');checks.push('后台自动暂停，返回须点击继续');
 for(let i=0;i<5;i++){await tap('pause');await tap('restart');const s=await snap();assert.equal(s.journey.count,8);assert.equal(s.journey.usedRows.length,0);assert.ok(s.journey.z<1);}checks.push('连续五次免费重开，无叠加门收益');
 await tap('pause');await tap('chapters');await page.evaluate(()=>{const d={cleared:[true,false,false],clues:[true,false,false],best:[23,0,0],settings:{music:false,sfx:false,vibration:false}};localStorage.setItem('yilu-changge-v1',JSON.stringify(d));});await page.reload();await page.waitForFunction(()=>globalThis.__YLCG__);const prior=(await snap()).save;await tap('clues');await tap('return');assert.deepEqual((await snap()).save,prior);checks.push('线索册返回保留已有进度');
 // Inject platform storage failure, preserving the real Book and Game implementations.
 await page.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('test quota failure','QuotaExceededError')};});await page.reload();await page.waitForFunction(()=>globalThis.__YLCG__);await tap('settings');await tap('music');assert.match((await snap()).notice,/仍可游玩/);await tap('return');await tap('chapters');await tap('level0');await tap('start');await page.waitForTimeout(400);assert.ok((await snap()).journey.z>0);checks.push('真实Storage写失败显示提示，仍可开战');
 assert.equal(errors.length,0,errors.join('\n'));console.log(JSON.stringify({checks,errors}));writeFileSync('evidence/browser-edge.json',JSON.stringify({passed:true,checks,errors},null,2));
}catch(e){console.error(e);await page.screenshot({path:'evidence/browser-edge-failure.png'});writeFileSync('evidence/browser-edge.json',JSON.stringify({passed:false,checks,errors,error:String(e)},null,2));process.exitCode=1;}finally{await context.close();}
