import {spawn,spawnSync} from 'node:child_process';
import {mkdirSync,writeFileSync,createWriteStream,readFileSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const platform=process.argv[2]||'web-mobile';
if(!['web-mobile','wechatgame'].includes(platform))throw Error('unsupported platform');
const evidence=process.env.YILU_EVIDENCE_DIR||'evidence/v03';mkdirSync(evidence,{recursive:true});
if(existsSync('art-source/battle-rework20260925/runtime-manifest.json')){const artwork=spawnSync(process.execPath,['tools/battle-rework-assets.mjs','--check'],{stdio:'inherit'});if(artwork.status!==0)throw Error('Battle artwork manifest verification failed');}
if(existsSync('art-source/ui20260925/runtime-manifest.json')){const artwork=spawnSync(process.execPath,['tools/ui20260925-assets.mjs','--check'],{stdio:'inherit'});if(artwork.status!==0)throw Error('Presentation artwork manifest/import verification failed');}
const localWechat=platform==='wechatgame'?JSON.parse(readFileSync('build/wechatgame/project.config.json','utf8')):null;
if(localWechat&&(!/^wx[0-9a-f]{16}$/.test(localWechat.appid)||localWechat.compileType!=='game'))throw Error('A previously verified local mini-game AppID is required; no tourist fallback.');
mkdirSync('.cache',{recursive:true});if(localWechat)writeFileSync('.cache/wechat-before-build.json',JSON.stringify(localWechat,null,2));
const config={name:'一路长歌',platform,buildPath:'project://build',outputName:platform,debug:false,startScene:'752d3aa0-8b82-4e8e-a6d4-c6587c90bcf2',scenes:[{url:'db://assets/scenes/Journey.scene',uuid:'752d3aa0-8b82-4e8e-a6d4-c6587c90bcf2'}],packages:{'web-mobile':{orientation:'portrait'},wechatgame:{appid:localWechat?.appid??'touristappid',orientation:'portrait'}},sourceMaps:false};
const configPath=platform==='wechatgame'?'.cache/build-wechatgame-local.json':`tools/build-${platform}.json`;
writeFileSync(configPath,JSON.stringify(config,null,2));
const bin='/Applications/CocosCreator/Creator/3.8.8/CocosCreator.app/Contents/MacOS/CocosCreator';
const args=['--project',process.cwd(),'--build',`configPath=${resolve(configPath)}`];
console.log(bin,args.join(' '));
mkdirSync('.cache/tmp',{recursive:true});
const log=createWriteStream(`${evidence}/build-${platform}.log`);const p=spawn(bin,args,{stdio:['ignore','pipe','pipe'],env:{...process.env,TMPDIR:resolve('.cache/tmp')}});
const output=d=>{const safe=d.toString().replace(/wx[0-9a-f]{16}/g,'[local-game-appid]');log.write(safe);process.stdout.write(safe);};p.stdout.on('data',output);p.stderr.on('data',output);
p.on('close',code=>{log.end();if(code===36&&platform==='web-mobile'){try{const main=JSON.parse(readFileSync('build/web-mobile/assets/main/config.json','utf8')),internal=JSON.parse(readFileSync('build/web-mobile/assets/internal/config.json','utf8'));if(!Object.keys(main.scenes||{}).length||!internal.uuids?.length)throw Error('Empty scene or engine resource bundle');}catch(e){console.error('Build output validation failed:',String(e));code=34;}}if(code===36&&platform==='wechatgame'){try{const main=JSON.parse(readFileSync('build/wechatgame/assets/main/config.json','utf8')),resources=JSON.parse(readFileSync('build/wechatgame/subpackages/resources/config.json','utf8'));if(!Object.keys(main.scenes||{}).length||!resources.uuids?.length)throw Error('Empty WeChat scene or resource bundle');}catch(e){console.error('Build output validation failed:',String(e));code=34;}const config=JSON.parse(readFileSync('build/wechatgame/project.config.json','utf8'));if(config.appid!==localWechat.appid||config.compileType!=='game'){console.error('Unexpected appid in generated package; do not open/upload.');code=34;}else{writeFileSync('build/wechatgame/project.config.json',JSON.stringify({...localWechat,...config,appid:localWechat.appid,setting:{...config.setting,...localWechat.setting}},null,2));}}if(code===36){const optimized=spawnSync(process.execPath,['tools/v09-assets.mjs',platform],{stdio:'inherit',env:{...process.env,YILU_EVIDENCE_DIR:evidence}});if(optimized.status!==0){console.error('Build resource optimization/verification failed');code=34;}}writeFileSync(`${evidence}/build-${platform}-result.json`,JSON.stringify({platform,exitCode:code,success:code===36,date:new Date().toISOString(),bin,args},null,2));process.exit(code===36?0:1)});
