import fs from 'node:fs';import {createHash} from 'node:crypto';
import {createBattle} from '../assets/scripts/formal/battle';import {FormalStore} from '../assets/scripts/formal/store';import {CHAPTERS,requiredOfficers} from '../assets/scripts/formal/data';import {MANIFEST} from '../assets/scripts/formal/manifest';import {reviewTarget} from '../assets/scripts/formal/NativeReview';import {configureCampaignReference} from '../assets/scripts/formal/CampaignReference';
const noop=()=>{},renderer:any=new Proxy({measure:(s:any,n:number)=>String(s).length*n*.6,measureText:(s:any)=>({width:String(s).length*8}),createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop}),frame:(key:string,x:number,y:number,h:number,o:any={})=>{const f=MANIFEST.frames[key];if(!f)return null;const [sx,sy,sw,sh]=f.r,sc=h/(o.refH||sh),w=sw*sc,hh=sh*sc,cx=o.grip?o.grip[0]*w:o.center?w/2:f.a[0]*w,cy=o.grip?o.grip[1]*hh:o.center?hh/2:hh*(1-f.a[1]);return{x:x-cx,y:y-cy,w,h:hh};}},{get:(o,k)=>k in o?o[k]:noop});

import {labelsOverlap} from '../assets/scripts/formal/presentation';
const results=[];
for(const [W,H,top,bottom] of [[402,874,62,34],[375,667,20,8]])for(const hx of [-.68,0,.68])for(const z of [1,3,6,10]){
 const st=new FormalStore({getItem:()=>null,setItem:()=>{}}),b=createBattle({chapter:19,lineup:st.loadout(),renderer,diagnostic:true,seed:7919}),s=b.state;s.heroX=s.targetX=hx;s.troops=s.troopShown=200;s.dist=0;s.ents=[{id:1,type:'gate',x:-.48,d:z+3,val:-3,passed:false},{id:2,type:'gate',x:0,d:z,val:7,passed:false},{id:3,type:'gate',x:.48,d:z+7,val:4,passed:false},{id:4,type:'crate',kind:'grain',x:-.3,d:z+1,hp:6,max:6,open:0,n:6}];b.render({W,H,top,bottom});const labels=b.diagnostics.labels,crate=labels.find(r=>r.kind==='crate'),blockers=labels.filter(r=>r.kind!=='crate');const collisions=crate?blockers.filter(r=>labelsOverlap(crate,r,4)):[];if(!crate||collisions.length)throw Error(JSON.stringify({W,H,hx,z,labels,collisions}));results.push({W,H,hx,z,labels,collisions:0});
}
fs.writeFileSync('evidence/YILU-CAMPAIGN20-20260930/label-projection-probe.json',JSON.stringify({capture_type:'headless-projection-rectangle-check',notActualGPURender:true,source_sha256:createHash('sha256').update(fs.readFileSync('assets/scripts/formal/battle.ts')).digest('hex'),cases:results.length,results},null,2));console.log(JSON.stringify({cases:results.length,collisions:0}));
