import{spawnSync}from'node:child_process';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';
const root='evidence/v06',cache='.cache/v06-video';mkdirSync(cache,{recursive:true});
const run=args=>{const p=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-y',...args],{stdio:'inherit'});if(p.status)throw Error('ffmpeg failed '+args.join(' '));};
const encode=(input,output,trim=[],filters=[])=>run([...trim,'-i',input,...filters,'-c:v','libx264','-preset','fast','-crf','24','-threads','2','-pix_fmt','yuv420p','-r','30','-c:a','aac','-b:a','128k','-movflags','+faststart',output]);
for(const name of['three-levels-live-audio','compare-spear-guanzhen','compare-blade-zhenjun'])encode(`${root}/${name}.webm`,`${root}/${name}.mp4`);
const delivery=JSON.parse(readFileSync(`${root}/delivery.json`)),supplement=JSON.parse(readFileSync(`${root}/boss-comparison.json`)),zero=delivery.timeline.find(t=>t.type==='recording-start').seconds;
encode(`${root}/three-levels-live-audio.mp4`,`${root}/natural-horde-excerpt.mp4`,['-ss','4','-t','26']);
const parts=[];for(const r of delivery.runs){const output=`${cache}/boss-${r.level}.mp4`;if(supplement.clips.some(c=>c.boss===r.level)){encode(`${root}/boss-isolated-${r.level}.webm`,output,[],['-vf',"drawtext=fontfile=/System/Library/Fonts/Supplemental/Songti.ttc:text='招式对照 · 隔离场景':fontsize=26:fontcolor=0x19363d:x=(w-tw)/2:y=h*0.22:box=1:boxcolor=0xf2ecd9@0.85:boxborderw=6"]);parts.push({level:r.level,source:'isolated supplement',output});}else{const start=delivery.timeline.find(t=>t.type==='boss-start'&&t.level===r.level).seconds-zero,end=delivery.timeline.find(t=>t.type==='victory'&&t.level===r.level).seconds-zero;encode(`${root}/three-levels-live-audio.mp4`,output,['-ss',String(start),'-t',String(end-start)]);parts.push({level:r.level,source:'natural final recording',start,end,output});}}
writeFileSync(`${cache}/concat.txt`,parts.map(p=>`file '${p.output.split('/').pop()}'`).join('\n'));
run(['-f','concat','-safe','0','-i',`${cache}/concat.txt`,'-c','copy','-movflags','+faststart',`${root}/boss-six-moves.mp4`]);
const videos=[];for(const name of['three-levels-live-audio','natural-horde-excerpt','compare-spear-guanzhen','compare-blade-zhenjun','boss-six-moves']){const p=spawnSync('ffprobe',['-v','error','-show_entries','format=duration,size:stream=codec_type,codec_name,width,height,r_frame_rate','-of','json',`${root}/${name}.mp4`],{encoding:'utf8'});if(p.status)throw Error('ffprobe failed');const data=JSON.parse(p.stdout);if(!data.streams.some(s=>s.codec_type==='audio'))throw Error('missing audio');videos.push({file:name+'.mp4',...data});}
writeFileSync(`${root}/video-checks.json`,JSON.stringify({passed:true,speed:'original timestamps; no speed change',liveAudio:delivery.sound,bossParts:parts,videos},null,2));console.log(JSON.stringify(videos.map(v=>({file:v.file,duration:v.format.duration,size:v.format.size}))));
