import{readFileSync,writeFileSync,readdirSync,statSync,existsSync}from'node:fs';import{createHash}from'node:crypto';import{execFileSync}from'node:child_process';import assert from'node:assert/strict';
const root='evidence/v03',json=f=>JSON.parse(readFileSync(root+'/'+f)),sha=f=>createHash('sha256').update(readFileSync(f)).digest('hex');
const verify=json('verification-run.json');assert.equal(verify.passed,true);assert.equal(verify.before,verify.after);for(const file of ['browser-ten-runs.json','browser-edges.json','browser-failures.json','browser-lifecycle.json','sound-pause.json','resource-recovery.json','transition-fixtures.json','preview-isolation.json','launcher-conflict.json','soak-stability.json','package-start.json','review-check.json'])assert.equal(json(file).passed,true,file);
const ten=json('browser-ten-runs.json'),runs=ten.runs,audio=json('audio-capture.json'),probe=json('video-probe.json');assert.equal(runs.length,10);assert.deepEqual([1,2,3].map(i=>runs.filter(r=>r.level===i).length),[4,3,3]);assert.ok(runs.every(r=>r.phase==='won'));assert.equal(audio.capture.audioTracks,1);assert.ok(probe.streams.some(s=>s.codec_type==='audio'));assert.ok(Number(probe.format.duration)>=audio.runs.reduce((n,r)=>n+r.elapsed,0));
const unit=readFileSync(root+'/verify-rules.txt','utf8'),n=Number(unit.match(/# pass (\d+)/)[1]);assert.match(unit,/# fail 0/);assert.match(unit,/# skipped 0/);const samples=runs.flatMap(r=>r.samples),fps=samples.map(s=>s.fps).sort((a,b)=>a-b),range=xs=>[Math.min(...xs),Math.max(...xs)],mb=n=>+(n/1048576).toFixed(2);const stability=json('soak-stability.json'),warm=stability.runs.slice(-3);
const summary={version:'0.3.0-rc1',status:'三关试玩候选，等待用户集中试玩',baseline:'5478427c7ae02037c93f8b8fb75203e3b19a6b14',runtimeFingerprint:verify.after,unitTests:{passed:n,failed:0,skipped:0},browser:{wins:10,distribution:[4,3,3],device:'Apple M5 desktop Chrome',viewports:[[360,800],[390,844],[360,640]],meanFPS:range(runs.map(r=>r.meanFPS)),sampleFPS:{minimum:fps[0],p05:fps[Math.floor(fps.length*.05)],median:fps[Math.floor(fps.length*.5)]},stabilityScope:stability.scope,additionalWarmedVictories:stability.runs.length,endNodes:range(warm.map(r=>r.endNodes)),endPool:range(warm.map(r=>r.endPool)),gpuBuffersMiB:range(warm.map(r=>mb(r.endMetrics.gpuBuffers))),gpuTexturesMiB:range(warm.map(r=>mb(r.endMetrics.gpuTextures))),heapMiB:range(runs.map(r=>mb(r.endMetrics.jsHeap))),peakDrawCalls:Math.max(...samples.map(s=>s.drawCalls)),peakEffects:Math.max(...samples.map(s=>s.effects)),runs:runs.map(({run,level,route,viewport,elapsed,count,meanFPS})=>({run,level,route,viewport,elapsed,count,meanFPS})),errors:ten.errors},video:{file:'three-levels-with-audio.mp4',seconds:Number(probe.format.duration),capture:'actual canvas and live WebAudio; uncut, normal time, no added music',naturalWins:audio.runs},builds:{web:json('build-web-mobile-result.json'),wechat:json('build-wechatgame-result.json')},platform:json('platform-boundary.json')};
summary.displayText=`${n} 项规则与流程测试通过，失败／跳过均为 0。\n真实浏览器 10/10 通关：山道 4 局、营寨 3 局、城门 3 局。\n平均 FPS ${summary.browser.meanFPS.map(x=>x.toFixed(2)).join('–')}；最小一秒采样 ${fps[0].toFixed(2)}。\n补充全部表现预热后的三关实战复验：结算节点 ${summary.browser.endNodes.join('–')}，池 ${summary.browser.endPool.join('–')}，GPU 缓冲 ${summary.browser.gpuBuffersMiB.join('–')} MiB。\n连续有声录像 ${summary.video.seconds.toFixed(2)} 秒，覆盖首页到首城结尾。\n桌面结果；微信真机和用户集中试玩尚待验收。`;
writeFileSync(root+'/SUMMARY.json',JSON.stringify(summary,null,2));
const files=[];function walk(p){for(const n of readdirSync(p).sort()){const f=p+'/'+n;if(statSync(f).isDirectory())walk(f);else if(!f.endsWith('.log')&&!f.endsWith('.webm')&&!f.endsWith('delivery-receipt.json'))files.push({file:f,bytes:statSync(f).size,sha256:sha(f)});}}
for(const p of ['assets','build/web-mobile','build/wechatgame','art-source/v4',root])walk(p);for(const p of ['package.json','package-lock.json','tools/launch.mjs','tools/serve.mjs','启动一路长歌.command'])files.push({file:p,bytes:statSync(p).size,sha256:sha(p)});
writeFileSync(root+'/delivery-receipt.json',JSON.stringify({version:'0.3.0-rc1',generated:new Date().toISOString(),baselineCommit:summary.baseline,runtimeFingerprint:verify.after,note:'Commit SHA is supplied by final Git handoff; receipt avoids self-referential commit hashes. Source and both engine builds are hashed below.',files},null,2));console.log(summary.displayText);
