import {open,out} from './formal-browser.mjs';import {openPage} from '../docs/BATTLE-PREVIEW-20260926/tools/common.mjs';import {mkdirSync,writeFileSync} from 'node:fs';
const dir=out+'/comparison';mkdirSync(dir,{recursive:true});const ref=await openPage(),t=await open('compare-final');await t.tap('start');await t.tap('depart');
await t.p.evaluate(async()=>{const cc=await System.import('cc');function find(n){for(const c of n.components)if(typeof c.snapshot==='function'&&c.battle)return c;for(const ch of n.children){const r=find(ch);if(r)return r;}}globalThis.__fixture=find(cc.director.getScene());__fixture.enabled=false;});
const records=[];const cases=[['normal','normal','spear',2,-.35],['dense','dense','spear',2.2,.4],['general','general','spear',1.75,-.4],['guandao','normal','guandao',1.1,0]];const jobs=process.argv.includes('matrix')?[[360,640],[360,780],[375,667],[390,844],[430,932]].flatMap(([W,H])=>cases.slice(0,3).map(c=>[W,H,...c])):cases.map(c=>[390,844,...c]);
for(const [W,H,base,state,weapon,time,x] of jobs){const name=process.argv.includes('matrix')?W+'x'+H+'-'+base:base;await t.p.setViewportSize({width:W,height:H});await ref.p.evaluate(s=>__preview.setSize(s),W+'×'+H);await t.p.waitForTimeout(70);
 const fixture=await ref.p.evaluate(({state,weapon,time,x})=>{const P=__preview;P.setState(state);P.setCtrl('manual');P.setZones(false);P.setWeapon(weapon,2);P.setX(x);P.advance(time);return{S:JSON.parse(JSON.stringify(P.S,(_,v)=>v instanceof Set?{__set:[...v]}:v)),L:{W:P.L.W,H:P.L.H,top:P.L.safeTop,bottom:P.L.safeBottom},report:__layoutReport()};},{state,weapon,time,x});
 await ref.p.locator('#cv').screenshot({path:dir+'/'+name+'-preview.png'});
 const result=await t.p.evaluate(({S,W,H})=>{S=JSON.parse(JSON.stringify(S),(_,v)=>v&&v.__set?new Set(v.__set):v);const game=__fixture;game.drawMenu();Object.assign(game.battle.state,S);if(S.boss){game.battle.state.boss.person='lubu';game.battle.state.boss.max=100;}game.battle.render({W,H,top:47,bottom:34});game.menu.begin({W,H});game.menu.end();return{phase:game.battle.state.state,t:game.battle.state.t,missing:[...game.paint.missing]};},{...fixture,W,H});
 await t.p.waitForTimeout(100);await t.p.locator('canvas').screenshot({path:dir+'/'+name+'-cocos.png'});records.push({name,state,weapon,time,x,result,sourceLayout:fixture.L});
}
writeFileSync(dir+(process.argv.includes('matrix')?'/matrix.json':'/comparison.json'),JSON.stringify({scope:'Read-only source preview and actual native Cocos rendered from identical deterministic fixture states. Fixture injections only in isolated screenshot harness, NOT natural ten-level verification. Different top OS decoration is intentional. No claim of pixel identity or user visual approval.',records,errors:[...ref.errs,...t.errors]},null,2));await ref.b.close();await t.c.close();
