"""Pack reviewed full-body detail art without replacing collection portraits."""
from pathlib import Path
from PIL import Image
import ast,json,numpy as np,uuid
R=Path(__file__).resolve().parents[1]
node=next(n for n in ast.parse((R/'tools/pr2-art-slice.py').read_text()).body if isinstance(n,ast.FunctionDef) and n.name=='components')
exec(compile(ast.Module(body=[node],type_ignores=[]),'components','exec'))
source=R/'art-source/ios-fix20260928/detail-fullbody-cutout-candidate.png'
im=Image.open(source).convert('RGBA')
parts=[r for r in components(np.array(im)[:,:,3]>24) if r['area']>5000]
parts.sort(key=lambda r:(int((r['box'][1]+r['box'][3])/2)//512,r['box'][0]))
ids=['yuan','hua','diao','guo','xun','sunjian','sunquan','liu','sima']
assert len(parts)==len(ids)
atlas=Image.new('RGBA',(1050,1590));ledger=[]
mp=R/'assets/scripts/formal/manifest.ts';m=json.loads(mp.read_text().split('export const MANIFEST:any=')[1].rstrip(';\n'))
for i,(id,r) in enumerate(zip(ids,parts)):
 box=list(map(int,r['box']));tile=im.crop(tuple(box));x=(i%3)*350+3;y=(i//3)*530+3
 assert tile.width<=344 and tile.height<=524
 atlas.paste(tile,(x,y));key='g_detail_'+id
 m['frames'][key]={'s':'ios_details','r':[x,y,tile.width,tile.height],'a':[.5,0],'bh':tile.height}
 ledger.append({'id':id,'key':key,'source':source.name,'sourceBox':box,'atlasRect':m['frames'][key]['r'],'inspection':'whole body, feet and headgear retained; source gutters alpha zero'})
out=R/'assets/resources/formal20260927/ios-details.png';atlas.save(out)
meta=Path(str(out)+'.meta')
if not meta.exists():
 template=(R/'assets/resources/formal20260927/ios-added.png.meta').read_text();old=json.loads(template)['uuid'];meta.write_text(template.replace(old,str(uuid.uuid4())).replace('ios-added','ios-details'))
m['sheets']['ios_details']='formal20260927/ios-details'
mp.write_text('// Generated by tools/ios-slice-repair.py, ios-add-assets.py, ios-detail-assets.py.\nexport const MANIFEST:any='+json.dumps(m,ensure_ascii=False,separators=(',',':'))+';\n')
(R/'art-source/ios-fix20260928/detail-ledger.json').write_text(json.dumps(ledger,ensure_ascii=False,indent=2))
print({'fullBodyDetailsAdded':len(ledger),'totalFrames':len(m['frames'])})
