"""Reproducible technical sprite extraction; no generated pixels or background paint."""
from pathlib import Path
from PIL import Image
import json, numpy as np
root=Path(__file__).resolve().parents[1]
source=root/'art-source/pr2-fix20260927'
p=root/'assets/scripts/formal/manifest.ts'
m=json.loads(p.read_text().split('export const MANIFEST:any=')[1].rstrip(';\n'))

def components(mask):
    # Scan-line union-find keeps disconnected transparent gutters out of each sprite.
    parent=[];rows=[];previous=[]
    def find(i):
        while parent[i]!=i:parent[i]=parent[parent[i]];i=parent[i]
        return i
    for y,line in enumerate(mask):
        edge=np.diff(np.r_[False,line,False].astype(np.int8));runs=list(zip(np.where(edge==1)[0],np.where(edge==-1)[0]));current=[]
        for x0,x1 in runs:
            ids=[lab for a,b,lab in previous if a<=x1 and b>=x0]
            if ids:
                lab=find(ids[0])
                for other in ids[1:]:parent[find(other)]=lab
            else:lab=len(parent);parent.append(lab)
            current.append((x0,x1,lab));rows.append((y,x0,x1,lab))
        previous=current
    result={}
    for y,x0,x1,lab in rows:
        lab=find(lab);r=result.setdefault(lab,{'area':0,'box':[x0,y,x1,y+1],'runs':[]});r['area']+=x1-x0;r['runs'].append((y,x0,x1));b=r['box'];b[:]=[min(b[0],x0),min(b[1],y),max(b[2],x1),max(b[3],y+1)]
    return sorted(result.values(),key=lambda r:r['area'],reverse=True)

def atlas(name,tiles):
    out=Image.new('RGBA',(2048,2048));x=y=4;rh=0;ledger=[]
    for key,tile,box,ref in tiles:
        if x+tile.width+4>2048:x=4;y+=rh+8;rh=0
        if y+tile.height+4>2048:raise ValueError('atlas overflow')
        out.paste(tile,(x,y));m['frames'][key]={'s':'pr2_'+name,'r':[x,y,tile.width,tile.height],'a':[.5,0],'bh':ref}
        ledger.append({'key':key,'sourceBox':list(map(int,box)),'runtimeRect':[x,y,tile.width,tile.height]});x+=tile.width+8;rh=max(rh,tile.height)
    dest=root/f'assets/resources/formal20260927/pr2-{name}.png';out.crop((0,0,2048,y+rh+4)).save(dest)
    m['sheets']['pr2_'+name]='formal20260927/pr2-'+name
    (source/(name+'-slices.json')).write_text(json.dumps(ledger,indent=2));print(name,len(tiles),dest.stat().st_size)

im=Image.open(source/'officer-actions-source.png').convert('RGBA');tiles=[]
ids=['xu','liao','xiahou','lumeng','luxun','zhao','huang','pang','machao']
for col,pose in enumerate(['Wind','Strike','Rec']):
    left=round(col*im.width/3);right=round((col+1)*im.width/3);a=np.array(im.crop((left,0,right,im.height)))
    # Exclude neighboring boot pixels where source rows overlap in bounding boxes.
    trims={0:[(200,1240,264,1265),(0,1450,181,1470)],1:[(0,1250,156,1272),(0,1440,158,1460)],2:[(0,1250,155,1274)]}
    for x0,y0,x1,y1 in trims.get(col,[]):a[y0:y1,x0:x1,3]=0
    comps=components(a[:,:,3]>24);main=sorted(comps[:9],key=lambda r:r['box'][1]);assert len(main)==9 and min(r['area'] for r in main)>2000
    for id,r in zip(ids,main):
        x0,y0,x1,y1=r['box'];pixels=a[y0:y1,x0:x1].copy();keep=np.zeros(pixels.shape[:2],dtype=bool)
        for yy,xx0,xx1 in r['runs']:keep[yy-y0,xx0-x0:xx1-x0]=True
        pixels[:,:,3]=np.where(keep,pixels[:,:,3],0);tile=Image.fromarray(pixels);ref=m['frames']['g_front_'+id+'Run0']['bh']
        # Match source body height to the original standing frame, not the raised weapon.
        ref=(y1-y0)*.83
        tiles.append(('g_front_'+id+pose,tile,[left+x0,y0,left+x1,y1],ref))
refs={key.removesuffix('Rec'):tile.height*.95 for key,tile,box,ref in tiles if key.endswith('Rec')}
tiles=[(key,tile,box,refs[key.removesuffix('Wind').removesuffix('Strike').removesuffix('Rec')]) for key,tile,box,ref in tiles]
atlas('officers',tiles)
portrait=source/'portraits-source.png'
if portrait.exists():
    im=Image.open(portrait).convert('RGBA');tiles=[]
    for i,id in enumerate(['yuan','hua','diao','guo','xun','sunjian','sunquan','liu','sima']):
        x0=round(i%3*im.width/3);y0=round(i//3*im.height/3);x1=round((i%3+1)*im.width/3);y1=round((i//3+1)*im.height/3)
        tile=im.crop((x0,y0,x1,y1));box=tile.getchannel('A').point(lambda x:255 if x>24 else 0).getbbox();assert box
        tile=tile.crop(box);tiles.append(('g_portrait_'+id,tile,[x0+box[0],y0+box[1],x0+box[2],y0+box[3]],tile.height))
    atlas('portraits',tiles)
p.write_text('// Imported source frame geometry; generated by slicing tools.\nexport const MANIFEST:any='+json.dumps(m,ensure_ascii=False,separators=(',',':'))+';\n')
