/** New presentation art import. Preserve originals; explicitly record runtime scaling/encoding. */
import fs from 'node:fs';import path from 'node:path';import {createHash,randomUUID} from 'node:crypto';import {fileURLToPath} from 'node:url';import sharp from 'sharp';
export const presentationKeys=['home-bg','map-bg','camp-bg','result-bg','hero-home','hero-blade','brand-title','gold-button'];
const resourceRoot='assets/resources/ui20260925',sourceRoot='art-source/ui20260925',manifestPath=`${sourceRoot}/runtime-manifest.json`,evidence='evidence/UI-20260925',docs='docs/UI-20260925';
const hash=b=>createHash('sha256').update(b).digest('hex');
const readManifest=()=>fs.existsSync(manifestPath)?JSON.parse(fs.readFileSync(manifestPath,'utf8')):{schemaVersion:1,assets:[]};
export function presentationRuntimeAssets(){return readManifest().assets.map(a=>a.runtimePath);}
function directoryMeta(folder){if(!fs.existsSync(folder+'.meta'))fs.writeFileSync(folder+'.meta',JSON.stringify({ver:'1.2.0',importer:'directory',imported:true,uuid:randomUUID(),files:[],subMetas:{},userData:{}},null,2)+'\n');}
function imageMeta(file){if(fs.existsSync(file+'.meta'))return;const uuid=randomUUID(),name=path.basename(file,path.extname(file));fs.writeFileSync(file+'.meta',JSON.stringify({ver:'1.0.27',importer:'image',imported:true,uuid,files:['.json',path.extname(file)],subMetas:{'6c48a':{importer:'texture',uuid:uuid+'@6c48a',displayName:name,id:'6c48a',name:'texture',userData:{wrapModeS:'clamp-to-edge',wrapModeT:'clamp-to-edge',minfilter:'linear',magfilter:'linear',mipfilter:'none',anisotropy:0,isUuid:true,imageUuidOrDatabaseUri:uuid,visible:false},ver:'1.0.22',imported:true,files:['.json'],subMetas:{}}},userData:{type:'texture',fixAlphaTransparencyArtifacts:false,hasAlpha:path.extname(file)==='.png',redirect:uuid+'@6c48a'}},null,2)+'\n');}
async function importAsset(key,source,widthArg,replace=false){
 if(!presentationKeys.includes(key))throw Error('Unknown asset key');if(!source||!fs.existsSync(source))throw Error('Source image missing');
 const original=fs.readFileSync(source),metadata=await sharp(original).metadata(),alpha=key==='hero-home'||key==='hero-blade'||key==='brand-title'||key==='gold-button';if(alpha&&!metadata.hasAlpha)throw Error('Hero must be independently generated with real alpha; no background removal shortcut.');
 fs.mkdirSync(resourceRoot,{recursive:true});fs.mkdirSync(sourceRoot,{recursive:true});directoryMeta(resourceRoot);
 const ext=alpha?'.png':'.jpg',runtimePath=`${resourceRoot}/${key}${ext}`,sourcePath=`${sourceRoot}/${key}-original-${hash(original).slice(0,12)}${path.extname(source)||'.png'}`;
 if(fs.existsSync(runtimePath)&&!replace)throw Error(`Runtime art already exists; preserve it and review replacement explicitly: ${runtimePath}`);
 if(!fs.existsSync(sourcePath))fs.copyFileSync(source,sourcePath);
 const width=Number(widthArg)||(key==='gold-button'?400:alpha?540:640);if(width<390||width>1170)throw Error('Review an actual mobile size between390 and1170 pixels');
 let crop=null;let pipeline=sharp(original).rotate();
 if(key==='gold-button'){const decoded=await sharp(original).ensureAlpha().raw().toBuffer({resolveWithObject:true}),{data,info}=decoded;let left=info.width,top=info.height,right=0,bottom=0;
  // Ignore isolated alpha=1 export dust when locating the visible rectangle; retain a 2px filtering guard.
  for(let y=0;y<info.height;y++)for(let x=0;x<info.width;x++)if(data[(y*info.width+x)*4+3]>=2){left=Math.min(left,x);top=Math.min(top,y);right=Math.max(right,x);bottom=Math.max(bottom,y);}
  left=Math.max(0,left-2);top=Math.max(0,top-2);right=Math.min(info.width-1,right+2);bottom=Math.min(info.height-1,bottom+2);crop={left,top,width:right-left+1,height:bottom-top+1,alphaThreshold:2,guard:2};pipeline=pipeline.extract({left,top,width:crop.width,height:crop.height});
 }
 pipeline=pipeline.resize({width,withoutEnlargement:true});const output=alpha?await pipeline.png({compressionLevel:9,adaptiveFiltering:true,palette:key==='hero-home'||key==='hero-blade',colours:256,quality:90,dither:.5}).toBuffer():await pipeline.flatten({background:'#142432'}).jpeg({quality:82,mozjpeg:true,chromaSubsampling:'4:4:4'}).toBuffer();
 const runtime=await sharp(output).metadata(),stats=alpha?await sharp(output).stats():null;
 if(alpha&&stats.isOpaque)throw Error('Hero PNG is opaque; art review must supply true transparent background');
 const previousEntry=readManifest().assets.find(a=>a.assetId===key),previousVersions=previousEntry?.previousVersions||[];
 if(replace&&fs.existsSync(runtimePath)){const previous=fs.readFileSync(runtimePath),backup=`${sourceRoot}/${key}-runtime-before-${hash(previous).slice(0,12)}${ext}`;if(!fs.existsSync(backup))fs.writeFileSync(backup,previous);previousVersions.push({path:backup,sha256:hash(previous),bytes:previous.length});}
 fs.writeFileSync(runtimePath,output);imageMeta(runtimePath);
 const manifest=readManifest(),entry={assetId:key,sourcePath,runtimePath,origin:'User-authorized image generation; inspect source delivery metadata separately',sourceDimensions:[metadata.width,metadata.height],runtimeDimensions:[runtime.width,runtime.height],sourceSha256:hash(original),runtimeSha256:hash(output),bytes:output.length,transparent:alpha,anchor:[.5,.5],sliceInsets:key==='gold-button'?{left:60,right:60,top:16,bottom:16}:null,crop,previousVersions,encoding:alpha?((key==='hero-home'||key==='hero-blade')?'Transparent PNG palette256 quality90 dither0.5; full composition resized, source alpha retained':crop?'RGBA PNG; transparent-margin extraction with threshold2 + 2px guard, then downscale; no palette':'RGBA PNG; downscaled full image, no crop; no palette'):'JPEG quality82 4:4:4; resized full composition',pageGroups:key==='gold-button'?['all_ui']:key==='hero-home'||key==='hero-blade'||key==='brand-title'?['home']:key==='camp-bg'?['camp','transition','meeting']:key==='map-bg'?['chapters']:[key.split('-')[0]],status:'imported; real Cocos visual acceptance pending',alpha:alpha?{isOpaque:stats.isOpaque}:null};manifest.assets=manifest.assets.filter(a=>a.assetId!==key).concat(entry);fs.writeFileSync(manifestPath,JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify(entry));
}
async function inventory(check=false){
 fs.mkdirSync(evidence,{recursive:true});fs.mkdirSync(docs,{recursive:true});const manifest=readManifest();
 for(const a of manifest.assets){if(!presentationKeys.includes(a.assetId)||!a.runtimePath.startsWith(resourceRoot+'/'))throw Error('Unreviewed presentation manifest path');if(!fs.existsSync(a.runtimePath))throw Error(`Missing runtime resource ${a.assetId}`);const bytes=fs.readFileSync(a.runtimePath);if(hash(bytes)!==a.runtimeSha256)throw Error(`Runtime pixels/encoding changed without import record ${a.assetId}`);if(!fs.existsSync(a.runtimePath+'.meta'))throw Error(`Missing Cocos meta ${a.assetId}`);}
 const missing=presentationKeys.filter(k=>!manifest.assets.some(a=>a.assetId===k)),totalBytes=manifest.assets.reduce((n,a)=>n+a.bytes,0),baseline=18861220,limit=20*1024*1024;
 const budget={at:new Date().toISOString(),status:missing.length?'awaiting-generated-assets':'runtime-assets-present-build-validation-pending',assets:manifest.assets,missing,newRuntimeBytes:totalBytes,estimatedDecodedRgbaBytes:manifest.assets.reduce((n,a)=>n+a.runtimeDimensions[0]*a.runtimeDimensions[1]*4,0),baseline:{version:'v09-rc1',officialPreviewBytes:baseline,note:'Historical v09 preview receipt; not current UI build size'},estimate:{limitBytes:limit,targetMarginBytes:1048576,headroomAfterAddingOnlyTheseFiles:limit-baseline-totalBytes,otherCodeAndResourceChangesNotIncluded:true},actualWebBuild:null,actualWechatBuild:null,actualOfficialPreview:null,quality:'New background artwork resized for mobile and JPEG encoded with declared settings. Hero and brand retain alpha/full composition in PNG; button uses recorded transparent-margin crop and measured9-slice insets. Existing combat atlas pixel-preservation contract unchanged.'};fs.writeFileSync(`${evidence}/PRESENTATION_ASSET_BUDGET.json`,JSON.stringify(budget,null,2)+'\n');
 fs.writeFileSync(`${docs}/ASSET_BUDGET.md`,`# UI-20260925 资源预算\n\n独立表现资源已导入 ${manifest.assets.length}/${presentationKeys.length}，共 ${totalBytes} 字节。未导入：${missing.join('、')||'无'}。\n\nv09 历史官方预览为 ${baseline} 字节；沿用本地工程20MiB预算，仅增加本清单时预计余量 ${limit-baseline-totalBytes} 字节。该估算不包含新代码与其他改动，不是当前微信回执。目标余量至少1MiB，实际构建/当前官方预览仍待父级核验。\n\n背景保留完整生成原图，运行版按声明宽度缩小，以 JPEG quality82、4:4:4 编码；两种主将运行图保留完整构图与透明背景，采用PNG palette256/quality90/dither0.5；完整RGBA源与上一运行版保留。旧战斗图集继续逐像素保护实际帧与4px边界，不降质换占位。\n\n明细：\`evidence/UI-20260925/PRESENTATION_ASSET_BUDGET.json\`；来源及运行指纹：\`art-source/ui20260925/runtime-manifest.json\`。\n`);
 const pack=JSON.parse(fs.readFileSync(`${docs}/source-pack/config/asset_manifest.json`,'utf8'));
 const createMap={'home-bg-far':'home-bg','map-bg':'map-bg','camp-bg':'camp-bg','result-bg':'result-bg','hero-home':'hero-home','hero-blade':'hero-blade','brand-title':'brand-title','button-primary':'gold-button'};
 const rows=pack.assets.map(a=>{const key=createMap[a.assetId],entry=manifest.assets.find(e=>e.assetId===key);if(key)return [a.assetId,'create',entry?.sourcePath||'生成中；包内仅概念参考',entry?.runtimePath||`${resourceRoot}/${key}${(key==='hero-home'||key==='brand-title'||key==='gold-button')?'.png':'.jpg'}`,entry?'已导入；真实构建画面待验':'缺独立原图，未用概念总图冒充运行资源'];if(['home-bg-mid','home-bg-near'].includes(a.assetId))return[a.assetId,'create','暂无独立透明层','待定','当前home-bg若为合成远中近景，只能算一张静态背景；分层视差未完成'];const actor=/portrait-set|battle-actor-set|weapon-icon-set/.test(a.assetId),world=/road|divider|shadow/.test(a.assetId);return[a.assetId,actor?'reuse':'modify',actor?'assets/scripts/ArtSprites.ts 与 ArtAtlas*.ts':world?'assets/scripts/WorldScenery.ts / BattleView.ts':'assets/scripts/Game.ts / BattleView.ts','现有组件及本轮真实实现，由最终代码核对',actor?'现有身份/兵器/动作帧复用，头像裁区由呈现层约束':'已有引擎图形/文字组件；本轮视觉修改与合格状态由父级实际截图核验，不能按ID声称新贴图已制作'];});
 fs.writeFileSync(`${docs}/ASSET_STATUS.md`,'# UI-20260925 资源逐项盘点\n\n源包42项是生产计划，不包含完成运行美术。以下区分现有资源复用、待修改组件与新作独立素材；status不是最终视觉验收。来源PNG和运行图均与UI文字、热区分离。不引入第三方字体或授权不明素材。\n\n|assetId|决策|现有/源路径|最终/候选路径|缺口与实际状态|\n|---|---|---|---|---|\n'+rows.map(r=>'|'+r.join('|')+'|').join('\n')+'\n');
 console.log(JSON.stringify({assets:manifest.assets.length,missing,newRuntimeBytes:totalBytes,estimatedMargin:limit-baseline-totalBytes}));if(check&&missing.length)throw Error('Presentation asset set incomplete');
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const mode=process.argv[2]||'--inventory';if(mode==='--import'){await importAsset(process.argv[3],process.argv[4],process.argv[5]);await inventory();}else if(mode==='--resize'){const entry=readManifest().assets.find(a=>a.assetId===process.argv[3]);if(!entry)throw Error('Existing manifest entry required');await importAsset(entry.assetId,entry.sourcePath,process.argv[4],true);await inventory();}else if(mode==='--inventory'||mode==='--check')await inventory(mode==='--check');else throw Error('Use --import key source [width], --resize key width, --inventory or --check');}
