from pathlib import Path
import json,datetime,hashlib
r=Path('evidence/v09')
def read(p): return json.loads((r/p).read_text())
def write(p,x): (r/p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
d=read('delivery.json');m=read('matrix/checks.json');e=read('errors-regression.json');p=read('phone-preview.json');assert d['passed'] and m['passed'] and e['passed'] and p['passed']
budget=read('ASSET_BUDGET.json');budget['actualBuilds']={name:read('ASSET_BUDGET-'+name+'.json') for name in ['web-mobile','wechatgame']};budget['budget']['officialUploadBytes']=p['serverSize']['total'];budget['budget']['officialMarginBytes']=p['remainingToProjectBudget'];budget['verification']['officialPreview']='generated using same existing local test identity';write('ASSET_BUDGET.json',budget)
x={'runtime':'v09-rc1','generatedAt':datetime.datetime.now().astimezone().isoformat(),'sourceBaseline':'Latest local v081 working tree preserved in .cache/v09-baseline; no reset, stash, commit or push.','sourcePackage':{'file':'YILU_V09_GLOBAL_OPTIMIZATION_CODEX.zip','sha256':'fb56464d22707e05cdbbb83d54228aef74ab5cfa121f3e5549e7f719b05d5070'},'fingerprints':read('FINGERPRINT.json'),'commands':[{'command':'npm run check:v09','exitCode':0,'testsPassed':71,'evidence':'final-checks.log'},{'command':'node tools/v09-platform-check.mjs','exitCode':0,'evidence':'platform-regression.json'},{'command':'YILU_EVIDENCE_DIR=evidence/v09 npm run build:web','exitCode':0,'evidence':'build-web-mobile-result.json'},{'command':'YILU_EVIDENCE_DIR=evidence/v09 npm run build:wechat','exitCode':0,'evidence':'build-wechatgame-result.json'},{'command':'node tools/browser-v09-matrix.mjs','exitCode':0,'evidence':'matrix/checks.json'},{'command':'node tools/browser-v09-errors.mjs','exitCode':0,'evidence':'errors-regression.json'},{'command':'node tools/browser-v09-delivery.mjs','exitCode':0,'evidence':'delivery.json'}],'desktop':{'engine':'Cocos Creator 3.8.8','browser':'Actual installed Chrome on macOS; not phone','viewports':[{'width':390,'height':844},{'width':360,'height':640}],'notch':'synthetic safe/capsule metrics, not a claimed device','matrixChecks':len(m['checks']),'pageStates':len(m['pages']),'comparison':'six fresh v081 before and v09 after images, same 390x844 isolated fixture states','density':m['density'],'restarts':m['restarts']},'natural':{'continuous':True,'failedEarlierAttempts':['failed-attempt-1.json','failed-attempt-2.json'],'retryReason':'Second-level contact failures retained; corrected aiming and evasion inputs only, no gameplay parameters changed','legalTouchOnly':True,'injectedCombatState':False,'speed':'real time','runs':[{k:v for k,v in run.items() if k not in ['ledger','samples','pacing']} for run in d['runs']],'sound':d['sound'],'recording':'final-three-levels.mp4','highlights':'highlights.mp4','ledger':'delivery.json','saveRestored':d['savedAndRestored']},'errors':e,'faultSegment':read('browser-kite-segment.json'),'wechatPreview':p,'reviewBoundaries':['Desktop tests and official preview generation do not establish phone touch feel, safe-area appearance, sound listening or sustained phone performance.','Art uses existing approved rear/side-facing sprites; no new approved front-facing portraits supplied.','Original Last War formulas remain explicit local defaults, not a full reconstruction.','Existing sharp high advisory retained; development dependency audit is not all clear.'],'noBGM':True,'unverified':['Actual user phone acceptance','Public release'],'knownIssues':['sharp development dependency high advisory: see dependency-audit.json']}
write('VERIFICATION.json',x);print(json.dumps({'verified':True,'tests':71,'matrix':len(m['checks']),'naturalRuns':len(d['runs'])}))
