import {MANIFEST} from './manifest';
import {_decorator,Component,Node,UITransform,Layers,view,ResolutionPolicy,input,Input,EventTouch,sys,profiler} from 'cc';
import {Platform} from '../Platform';
import {PresentationAssets,PresentationKey} from '../ui/PresentationAssets';
import {NativePaint} from './NativePaint';
import {createBattle} from './battle';
import {FormalStore} from './store';
import {CHAPTERS,PEOPLE,WEAPON_DATA,TREASURES,RANKS,TUNING,Slot,WeaponId,routeFor} from './data';
const {ccclass}=_decorator;
declare const wx:any;
type Hit={id:string;x:number;y:number;w:number;h:number;action:()=>void};
type Screen='loading'|'error'|'home'|'chapters'|'prepare'|'collection'|'battle'|'pause'|'result'|'transition'|'settings';
@ccclass('FormalGame')
export class FormalGame extends Component {
 private root!:Node;private bg!:Node;private ui!:Node;private paint!:NativePaint;private menu!:NativePaint;private art=new PresentationAssets();private platform!:Platform;private store!:FormalStore;private battle:ReturnType<typeof createBattle>|null=null;
 private lastSound='';private lastDamage=0;private screen:Screen='loading';private hits:Hit[]=[];private chapter=0;private page=0;private tab='companions';private runId='';private settled=false;private first=false;private elapsed=0;private acc=0;private finishAge=0;private touch=-1;private lastX=0;private startX=0;private startY=0;private pressed:Hit|null=null;private loadingError='';private rev=0;private avg=60;private frames:number[]=[];private lastSize='';
 private make(name:string,parent=this.node){const n=new Node(name);n.layer=Layers.Enum.UI_2D;parent.addChild(n);n.addComponent(UITransform);return n;}
 private get size(){const m=this.platform?.windowMetrics;const v=view.getVisibleSize();const W=m?.width||390,H=W*v.height/v.width,k=v.width/W,top=Math.max(8,m?.safe.top||0),bottom=Math.max(8,(m?.height||H)-(m?.safe.bottom||H));return{W,H,k,top,bottom,capsule:m?.capsule?{x:m.capsule.left,y:m.capsule.top,w:m.capsule.right-m.capsule.left,h:m.capsule.bottom-m.capsule.top}:null};}
 async start(){view.setDesignResolutionSize(720,1280,ResolutionPolicy.FIXED_WIDTH);profiler.hideStats();this.root=this.make('FormalWorld');this.bg=this.make('FormalBackground');this.ui=this.make('FormalInterface');this.paint=new NativePaint(this.root);this.menu=new NativePaint(this.ui);
 const storage={getItem:(k:string)=>typeof wx!=='undefined'&&wx.getStorageSync?wx.getStorageSync(k)||null:(sys.isBrowser?window.localStorage:sys.localStorage).getItem(k),setItem:(k:string,v:string)=>{if(typeof wx!=='undefined'&&wx.setStorageSync)wx.setStorageSync(k,v);else(sys.isBrowser?window.localStorage:sys.localStorage).setItem(k,v);}};
 this.store=new FormalStore(storage);this.platform=new Platform(this.node,()=>{this.cancel();if(this.screen==='battle')this.show('pause');},true);
 input.on(Input.EventType.TOUCH_START,this.down,this);input.on(Input.EventType.TOUCH_MOVE,this.move,this);input.on(Input.EventType.TOUCH_END,this.up,this);input.on(Input.EventType.TOUCH_CANCEL,this.cancel,this);
 (globalThis as any).__YLCG__={snapshot:()=>this.snapshot()};this.show('loading');await this.load();}
 private async load(){try{await Promise.all([NativePaint.load(),PresentationAssets.load(),this.platform.load()]);const gold=PresentationAssets.frame('gold-button');if(gold)NativePaint.textures.ui_gold=gold.texture as any;this.show('home');}catch(e){this.loadingError=String(e);this.show('error');}}
 private at(e:EventTouch){const p=e.getUILocation(),u=this.node.getComponent(UITransform)!,v=u.convertToNodeSpaceAR({x:p.x,y:p.y,z:0} as any),s=this.size;return{x:v.x/s.k+s.W/2,y:s.H/2-v.y/s.k};}
 private down(e:EventTouch){if(this.touch!==-1)return;this.touch=e.getID()??-1;const p=this.at(e);this.lastX=this.startX=p.x;this.startY=p.y;this.pressed=this.hits.find(h=>p.x>=h.x&&p.x<=h.x+h.w&&p.y>=h.y&&p.y<=h.y+h.h)||null;this.platform.syncAudio(this.screen==='battle');}
 private move(e:EventTouch){if(e.getID()!==this.touch)return;const p=this.at(e);if(this.screen==='battle'&&!this.pressed&&this.battle)this.battle.move(this.battle.state.targetX+(p.x-this.lastX)/(this.size.W*.4));this.lastX=p.x;}
 private up(e:EventTouch){if(e.getID()!==this.touch)return;const p=this.at(e),h=this.pressed;this.cancel();if(h&&Math.abs(p.x-this.startX)<24&&Math.abs(p.y-this.startY)<24&&p.x>=h.x&&p.x<=h.x+h.w&&p.y>=h.y&&p.y<=h.y+h.h)h.action();}
 private cancel(){this.touch=-1;this.pressed=null;this.battle?.cancel();}
 private button(id:string,title:string,x:number,y:number,w:number,action:()=>void,primary=false,disabled=false){const p=this.menu;p.fillStyle=primary?'#C9A45C':'#172C40';p.strokeStyle='#8E7549';p.lineWidth=1;if(primary&&NativePaint.textures.ui_gold){const t=NativePaint.textures.ui_gold;p.drawImage('ui_gold',0,0,t.width,t.height,x,y,w,48);}else{p.fillRect(x,y,w,48);p.strokeRect(x,y,w,48);}this.label(title,x+w/2,y+24,primary?18:14,disabled?'#79818A':primary?'#182638':'#F5EFE2','center');if(!disabled)this.hits.push({id,x,y,w,h:48,action});}
 private label(str:string,x:number,y:number,size=14,col='#F5EFE2',align='left'){const p=this.menu;p.font=`600 ${size}px Arial`;p.fillStyle=col;p.textAlign=align;p.fillText(str,x,y);}
 private title(str:string,sub:string){const s=this.size;this.menu.fillStyle='rgba(15,28,42,.92)';this.menu.fillRect(12,s.top,s.W-24,86);this.label(str,s.W/2,s.top+25,23,'#E6CD93','center');this.label(sub,s.W/2,s.top+61,13,'#D1D4D5','center');}
 private back(action=()=>this.show('home')){const s=this.size;this.button('back','返回',12,s.H-s.bottom-58,76,action);}
 private show(screen:Screen){this.cancel();this.screen=screen;this.rev++;this.battle?.pause(screen!=='battle');this.platform?.syncAudio(screen==='battle');this.drawMenu();}
 private drawMenu(){if(!this.platform)return;const s=this.size,{W,H,top,bottom,k}=s;this.root.setScale(k,k,1);this.ui.setScale(k,k,1);this.bg.setScale(k,k,1);this.hits=[];this.menu.begin(s);this.art.begin();this.root.active=['battle','pause','result'].includes(this.screen);this.bg.active=!this.root.active;
 if(this.bg.active){const key:PresentationKey=this.screen==='home'?'home-bg':this.screen==='chapters'?'map-bg':this.screen==='result'?'result-bg':'camp-bg';this.art.draw(this.bg,'background',key,0,0,W,H,'cover');}
 const footer=H-bottom-58;
 if(this.screen==='loading'){this.title('一路长歌：三国','正在加载战场与人物');}
 if(this.screen==='error'){this.title('资源尚未就绪','加载失败，已保留本机存档');this.button('retry','重新加载',24,footer,W-48,()=>{this.show('loading');this.load();},true);}
 if(this.screen==='home'){
 this.art.draw(this.bg,'home-hero','hero-home',0,35,W*.92,Math.max(260,H*.55),'contain');this.art.draw(this.bg,'brand','brand-title',0,H/2-top-88,W-32,90,'contain');
 const shade=this.menu.createLinearGradient();shade.addColorStop(0,'rgba(14,27,41,0)');shade.addColorStop(.3,'rgba(14,27,41,.90)');shade.addColorStop(1,'rgba(14,27,41,.98)');this.menu.fillStyle=shade;this.menu.fillRect(0,H-280,W,280);this.menu.fillStyle='rgba(14,27,41,.85)';this.menu.fillRect(12,top,W-82,48);this.label(RANKS[Math.min(9,this.store.completed)]+' · '+(this.store.completed===10?'十关已贯通':CHAPTERS[this.store.completed].faction+'征程'),20,top+20,15,'#E6CD93');
 this.button('settings','设',W-62,top+4,50,()=>this.show('settings'));this.label(this.store.completed===10?'重游故地，再聚同袍':'下一站 · '+CHAPTERS[this.store.completed].title,W/2,H-203,20,'#F5EFE2','center');
 this.button('start',this.store.completed===10?'重游征程':'开始征程',20,H-176,W-40,()=>{this.chapter=Math.min(9,this.store.completed);this.tab='companions';this.page=0;this.show('prepare');},true);
 this.button('chapters','征 程',20,H-116,(W-52)/2,()=>this.show('chapters'));this.button('collection','图 鉴',32+(W-52)/2,H-116,(W-52)/2,()=>{this.tab='people';this.page=0;this.show('collection');});
 }
 if(this.screen==='chapters'){
 this.title('十关长歌','群雄 → 魏 → 吴 → 蜀');const cell=(W-40)/2;CHAPTERS.forEach((c,i)=>{const open=this.store.unlocked(i),y=top+100+Math.floor(i/2)*58,x=16+(i%2)*(cell+8);this.button('level'+i,(this.store.data.cleared.includes(c.id)?'✓ ':open?'':'锁 ')+(i+1)+' · '+(open?c.place:'未开'),x,y,cell,()=>{this.chapter=i;this.page=0;this.show('prepare');},false,!open);});this.back();
 }
 if(this.screen==='prepare'||this.screen==='collection'){
 const prep=this.screen==='prepare',tabs=prep?['companions','support','treasures']:['people','weapons','treasures'];if(!tabs.includes(this.tab))this.tab=tabs[0];this.title(prep?CHAPTERS[this.chapter].title:'军中图鉴',prep?'匣内 · '+Array.from(new Set(routeFor(this.chapter,this.store.loadout().weapons,[]).filter(e=>e.kind==='weapon').map(e=>WEAPON_DATA[e.gives as WeaponId].label))).join(' / '):'收服同行 · 寻访支援 · 盟约共鸣');
 const tw=(W-40)/3;tabs.forEach((id,i)=>this.button('tab-'+id,({companions:'随军',support:'支援',treasures:'宝物',people:'人物',weapons:'兵器'} as any)[id],12+i*(tw+8),top+96,tw,()=>{this.tab=id;this.page=0;this.drawMenu();},this.tab===id));
 let rows:{id:string;label:string;detail:string;action:()=>void;disabled?:boolean}[]=[];
 if(this.tab==='companions'){rows=this.store.data.captures.map(id=>({id:'comp-'+id,label:(this.store.data.companions.includes(id)?'✓ ':'')+PEOPLE[id],detail:'收 · 随军',action:()=>{this.store.equipCompanion(id);this.drawMenu();}}));}
 if(this.tab==='support'){rows=this.store.data.visits.map(id=>({id:'support-'+id,label:(this.store.data.support===id?'✓ ':'')+PEOPLE[id],detail:id==='hua'?'减员后救回伤兵':['diao','xun','sunjian'].includes(id)?'每12秒鼓舞 +2':'每12秒自动策应',action:()=>{this.store.equipSupport(id);this.drawMenu();},disabled:this.store.completed<2}));}
 if(this.tab==='treasures'){rows=Object.entries(TREASURES).map(([id,t])=>{const owned=this.store.data.treasures.includes(id);return{id:'treasure-'+id,label:(this.store.data.slots[t.slot]===id?'✓ ':'')+t.name,detail:owned?t.effect:'未获得 · '+({dian:'典籍',qi:'器物',ma:'坐骑'}[t.slot]),action:()=>{this.store.equipTreasure(id);this.drawMenu();},disabled:!owned||!this.store.slotOpen(t.slot)};});}
 if(this.tab==='people'){rows=Object.entries(PEOPLE).map(([id,name])=>{const d=this.store.data,relation=d.captures.includes(id)?'收':d.visits.includes(id)?'访':d.allies.includes(id)?'盟':d.seen.includes(id)?'已遇见':'未遇见';return{id:'person-'+id,label:name,detail:relation,action:()=>{},disabled:true};});}
 if(this.tab==='weapons'){rows=Object.entries(WEAPON_DATA).map(([id,w])=>{const owned=this.store.data.weapons.includes(id),lv=this.store.data.weaponLevels[id]||1;return{id:'upgrade-'+id,label:w.label+' Lv.'+lv,detail:owned?(lv>=5?'已满级':'升级需 '+TUNING.upgradeCost(lv)+' 军功 · 现有 '+this.store.data.xp):'尚未入池',action:()=>{this.store.upgrade(id);this.drawMenu();},disabled:!owned||lv>=5||this.store.data.xp<TUNING.upgradeCost(lv)};});}
 const previewTop=H-bottom-248-Math.min(96,Math.max(60,(H-420)*.35));const count=prep?Math.max(1,Math.min(3,Math.floor((previewTop-24-(top+154)-50)/62))):Math.max(2,Math.min(6,Math.floor((H-bottom-top-292)/62)));const pages=Math.max(1,Math.ceil(rows.length/count));this.page=Math.min(this.page,pages-1);const first=top+154;
 rows.slice(this.page*count,(this.page+1)*count).forEach((r,i)=>{const y=first+i*62;this.button(r.id,r.label,16,y,125,r.action,false,r.disabled);const max=Math.floor((W-164)/12),lines=r.detail.length>max?[r.detail.slice(0,max),r.detail.slice(max)]:[r.detail];lines.forEach((line,j)=>this.label(line,151,y+(lines.length===1?24:16+j*17),12,r.disabled?'#B1B4B8':'#E6CD93'));});
 if(!rows.length)this.label(this.tab==='support'?'第二关寻访华佗后开放支援':'通关后可邀请同袍同行',W/2,first+55,14,'#F5EFE2','center');
 if(prep){const load=this.store.loadout(),foot=footer-172,height=Math.min(96,Math.max(60,(H-420)*.35));this.menu.frame('g_run_spear0',W/2,foot,height,{refH:MANIFEST.frames.g_run_spear0.bh});load.companions.forEach((id,i)=>this.menu.frame('g_'+id+'Run0',W/2+(i?74:-74),foot+8,height*.72,{refH:MANIFEST.frames['g_'+id+'Run0']?.bh||180}));this.label('随军 '+load.companions.length+'/'+this.store.companionLimit+' · 支援 '+(PEOPLE[load.support||'']||'未编入'),W/2,foot+27,12,'#E6CD93','center');(['dian','qi','ma'] as Slot[]).forEach((slot,i)=>{const id=load.treasures[slot],x=W/2+(i-1)*64;this.menu.fillStyle='rgba(15,28,42,.9)';this.menu.fillRect(x-25,footer-85,50,46);if(id)this.menu.frame(TREASURES[id].icon,x,footer-62,30,{center:true});else this.label(this.store.slotOpen(slot)?({dian:'典',qi:'器',ma:'骑'}[slot]):'锁',x,footer-62,14,'#AAA799','center');});this.button('tactic','兵法 · '+(load.tactic==='zhenjun'?'震军':'贯阵'),W/2-66,footer-135,132,()=>{this.store.equipTactic();this.drawMenu();});this.label('敌将 · '+PEOPLE[CHAPTERS[this.chapter].boss],W/2,foot-height-18,14,'#E6CD93','center');}const py=prep?first+count*62+2:footer-60;if(pages>1){this.button('prev-page','‹',W/2-95,py,48,()=>{this.page=(this.page+pages-1)%pages;this.drawMenu();});this.label((this.page+1)+' / '+pages,W/2,py+24,14,'#E6CD93','center');this.button('next-page','›',W/2+47,py,48,()=>{this.page=(this.page+1)%pages;this.drawMenu();});}
 this.back();if(prep)this.button('depart','出 征',100,footer,W-116,()=>this.begin(),true);else this.label('兵器等级永久保留 · 局内阶位每局重置',W-15,footer+24,12,'#E6CD93','right');
 }
 if(this.screen==='battle'){this.hits.push({id:'pause',x:4,y:top,w:48,h:48,action:()=>this.show('pause')});}
 if(this.screen==='pause'){
 this.menu.fillStyle='rgba(9,19,30,.8)';this.menu.fillRect(0,0,W,H);this.title('暂 歇','松开手指后可继续出征');this.button('continue','继续战斗',32,H*.43,W-64,()=>this.show('battle'),true);this.button('restart','重新挑战',32,H*.43+64,W-64,()=>this.begin());this.button('quit','返回营地',32,H*.43+128,W-64,()=>this.show('home'));
 }
 if(this.screen==='result'){
 const won=this.battle!.state.troops>0,c=CHAPTERS[this.chapter];this.menu.fillStyle='rgba(9,19,30,.87)';this.menu.fillRect(0,0,W,H);this.title(won?'凯旋 · '+c.place:'此役未竟',won?(this.first?'首次通关 · 奖励已记入成长':'重游胜利 · 军功 +10'):'调整走位，再聚同袍');
 this.label('兵力 '+Math.round(this.battle!.state.troops)+' · '+RANKS[Math.min(9,this.store.completed)],W/2,top+123,20,'#E6CD93','center');
 if(won&&this.first){const lines=[c.capture.length?'收服 · '+c.capture.map(x=>PEOPLE[x]).join('、'):'',c.visit.length?'寻访 · '+c.visit.map(x=>PEOPLE[x]).join('、'):'',c.allies.length?'结盟 · '+c.allies.map(x=>PEOPLE[x]).join('、'):'',c.weapon?'兵器入池 · '+WEAPON_DATA[c.weapon].label:'',c.treasure?'宝物 · '+TREASURES[c.treasure].name:''].filter(Boolean);lines.forEach((l,i)=>this.label(l,W/2,top+180+i*34,14,'#F5EFE2','center'));}
 this.button('next',won&&this.chapter<9?'整军 · 下一关':won?'返回营地':'再战本关',24,footer-62,W-48,()=>{if(this.store.notice){this.store.retry();this.drawMenu();return;}if(!won)this.begin();else if(this.chapter<9)this.show('transition');else this.show('home');},true);this.back();
 }
 if(this.screen==='transition'){const c=CHAPTERS[this.chapter];this.title('整军再发','战利品与成长已保存');this.label(c.place+' → '+CHAPTERS[Math.min(9,this.chapter+1)].place,W/2,H*.42,26,'#E6CD93','center');this.label('休整部曲 · 带上新得的同袍与宝物',W/2,H*.51,14,'#F5EFE2','center');this.button('prepare-next','前往整备',24,footer,W-48,()=>{this.chapter++;this.tab='companions';this.page=0;this.show('prepare');},true);}
 if(this.screen==='settings'){this.title('行军设置','音乐保持关闭');const b=this.platform.book;this.button('sfx','音效 · '+(b.data.settings.sfx?'开':'关'),24,top+130,W-48,()=>{b.data.settings.sfx=!b.data.settings.sfx;b.persist();this.drawMenu();});this.button('vibration','震动 · '+(b.data.settings.vibration?'开':'关'),24,top+195,W-48,()=>{b.data.settings.vibration=!b.data.settings.vibration;b.persist();this.drawMenu();});this.label('旧三关记录与收藏已原样保留',W/2,top+290,14,'#E6CD93','center');this.back();}
 if(this.store.notice){this.menu.fillStyle='#722B22';this.hits=[];this.menu.fillRect(0,H-110-bottom,W,110);this.label('保存未完成：请重试，当前进度仍保留',W/2,H-89-bottom,12,'#fff','center');this.button('retry-save','重试保存',W/2-52,H-68-bottom,104,()=>{this.store.retry();this.drawMenu();});}
 this.menu.end();this.art.end();}
 private begin(){if(!this.store.unlocked(this.chapter))return;if(this.store.notice&&!this.store.retry()){this.drawMenu();return;}this.runId=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);this.first=!this.store.data.cleared.includes(CHAPTERS[this.chapter].id);this.settled=false;this.acc=0;this.finishAge=0;this.elapsed=0;this.lastSound='';this.lastDamage=0;this.battle=createBattle({chapter:this.chapter,lineup:this.store.loadout(),renderer:this.paint});this.show('battle');}
 update(dt:number){if(!this.platform)return;const s=this.size,signature=[s.W,s.H,s.top,s.bottom,this.platform.windowMetrics.revision].join(':');if(signature!==this.lastSize){this.lastSize=signature;this.drawMenu();}if(this.screen==='battle'&&this.battle){this.frames.push(dt);if(this.frames.length>600)this.frames.shift();this.acc+=Math.min(.1,dt);while(this.acc>=1/60){this.battle.step();this.acc-=1/60;}this.elapsed+=dt;const st=this.battle.state;if(st.ended){this.finishAge+=dt;if(!this.settled){this.settled=true;this.store.settle({id:this.runId,chapter:this.chapter,won:st.troops>0,troops:st.troops,treasures:st.runGot});}if(this.finishAge>1.6)this.show('result');}const last=st.log[st.log.length-1],key=last?last.t+':'+last.msg:'';if(key!==this.lastSound){this.lastSound=key;if(last?.kind==='gate'||last?.kind==='crate'||last?.kind==='weapon')this.platform.sound('gather');if(last?.kind==='boss')this.platform.sound(last.msg.includes('中招')?'hurt':'warn');}const dmg=this.battle.totals.damage;if(dmg>this.lastDamage){this.lastDamage=dmg;this.platform.sound('hit');}}
 if(this.battle&&['battle','pause','result'].includes(this.screen))this.battle.render(s);}
 snapshot(){return{version:TUNING.version,engine:'Cocos native Sprite/Graphics/Label',screen:this.screen,chapter:this.chapter,runId:this.runId,revision:this.rev,save:JSON.parse(JSON.stringify(this.store?.data||{})),saveNotice:this.store?.notice,battle:this.battle?.snapshot(),ledger:this.battle?.ledger.slice(-100),diagnostics:this.battle?.diagnostics,buttons:this.hits.map(({id,x,y,w,h})=>({id,x,y,w,h})),viewport:this.platform?.windowMetrics,nativeNodes:this.paint?.activeNodes,missingArt:Array.from(this.paint?.missing||[]),fps:this.frames.length?this.frames.length/this.frames.reduce((a,b)=>a+b,0):0,audio:this.platform?.audioState,error:this.loadingError};}
 onDestroy(){input.off(Input.EventType.TOUCH_START,this.down,this);input.off(Input.EventType.TOUCH_MOVE,this.move,this);input.off(Input.EventType.TOUCH_END,this.up,this);input.off(Input.EventType.TOUCH_CANCEL,this.cancel,this);this.paint?.destroy();this.menu?.destroy();this.art.destroy();this.platform?.destroy();}
}
