import {GroundMesh} from './GroundMesh';
import {Node,Layers,UITransform,Sprite,SpriteFrame,Texture2D,Rect,Size,Vec2,Color,UIOpacity,Graphics,Label,LabelOutline,BitmapFont,resources} from 'cc';
import {MANIFEST} from './manifest';
type Gradient={stops:[number,string][];addColorStop:(at:number,color:string)=>void};
type Matrix=[number,number,number,number,number,number];
const color=(v:any,alpha=1):Color=>{if(typeof v==='object')v=v.stops[Math.floor(v.stops.length/2)]?.[1]||'#ffffff';const c=new Color();if(v?.startsWith('rgba')||v?.startsWith('rgb(')){const a=v.match(/[\d.]+/g).map(Number);c.set(a[0],a[1],a[2],(a[3]??1)*255);}else c.fromHEX(v||'#ffffff');c.a=Math.min(255,Math.max(0,c.a*alpha));return c;};
/** Retained Cocos primitives. This class never uses DOM Canvas or uploads a painted framebuffer. */
export class NativePaint {
 static textures:Record<string,Texture2D>={};static digits:BitmapFont;
 static async load(){await new Promise<void>((resolve,reject)=>resources.load('formal20260927/gate-digits',BitmapFont,(e,f)=>{if(e||!f)reject(e||Error('digits'));else{this.digits=f;resolve();}}));await Promise.all(Object.entries(MANIFEST.sheets as Record<string,string>).map(([key,p])=>new Promise<void>((resolve,reject)=>{if(this.textures[key])return resolve();resources.load(p+'/texture',Texture2D,(e,t)=>{if(e||!t)return reject(e||Error(p));this.textures[key]=t;resolve();});})));}
 private nodes:{n:Node;type:string;frame?:SpriteFrame;mesh?:GroundMesh}[]=[];private pools:Record<string,any[]>={};private used:Record<string,number>={};createdNodes=0;invalidRects=new Set<string>();private index=0;private lastGraphics:Graphics|null=null;private matrix:Matrix=[1,0,0,1,0,0];private stack:any[]=[];private path:{p:[number,number][];closed:boolean}[]=[];private current:{p:[number,number][];closed:boolean}|null=null;private lastPoint:[number,number]=[0,0];private L:any;
 globalAlpha=1;globalCompositeOperation='source-over';fillStyle:any='#fff';strokeStyle:any='#fff';lineWidth=1;lineJoin='round';lineCap='round';font='600 14px sans-serif';textAlign='left';textBaseline='middle';shadowColor='';shadowBlur=0;shadowOffsetY=0;private outline:any=null;activeNodes=0;missing=new Set<string>();
 constructor(private root:Node){}
 begin(L:any){this.L=L;this.index=0;this.used={};this.lastGraphics=null;this.matrix=[1,0,0,1,0,0];this.stack=[];this.globalAlpha=1;this.outline=null;}
 end(){for(const [type,pool] of Object.entries(this.pools))for(let i=this.used[type]||0;i<pool.length;i++)pool[i].n.active=false;this.activeNodes=this.index;}
 destroy(){this.nodes.forEach(e=>{e.mesh?.destroy();e.frame?.destroy();e.n.destroy();});this.nodes=[];}
 private take(type:string){this.lastGraphics=null;const pool=this.pools[type]||(this.pools[type]=[]),slot=this.used[type]||0;this.used[type]=slot+1;let e=pool[slot];if(!e){const n=new Node('native-'+this.index+'-'+type);n.layer=Layers.Enum.UI_2D;this.root.addChild(n);n.addComponent(UITransform);n.addComponent(UIOpacity);e={n,type};if(type==='sprite'){n.addComponent(Sprite).sizeMode=Sprite.SizeMode.CUSTOM;e.frame=new SpriteFrame();}if(type==='label'){n.addComponent(Label);n.addComponent(LabelOutline);}if(type==='graphics')n.addComponent(Graphics);if(type==='ground')e.mesh=new GroundMesh(n);pool[slot]=e;this.nodes.push(e);this.createdNodes++;}e.n.active=true;e.n.setSiblingIndex(this.index++);e.n.setScale(1,1,1);e.n.angle=0;return e;}
 private graphics(){if(this.lastGraphics)return this.lastGraphics;const e=this.take('graphics');e.n.setPosition(0,0);e.n.getComponent(UIOpacity)!.opacity=255;const g=e.n.getComponent(Graphics)!;g.clear();this.lastGraphics=g;return g;}
 private xy(x:number,y:number):[number,number]{const [a,b,c,d,e,f]=this.matrix;return[a*x+c*y+e-this.L.W/2,this.L.H/2-(b*x+d*y+f)];}
 save(){this.stack.push({matrix:[...this.matrix],globalAlpha:this.globalAlpha,fillStyle:this.fillStyle,strokeStyle:this.strokeStyle,lineWidth:this.lineWidth,font:this.font,textAlign:this.textAlign,textBaseline:this.textBaseline,globalCompositeOperation:this.globalCompositeOperation});}
 restore(){const s=this.stack.pop();if(s)Object.assign(this,s);}
 translate(x:number,y:number){const m=this.matrix;m[4]+=m[0]*x+m[2]*y;m[5]+=m[1]*x+m[3]*y;}
 scale(x:number,y:number){const m=this.matrix;m[0]*=x;m[1]*=x;m[2]*=y;m[3]*=y;}
 rotate(t:number){const m=this.matrix,[a,b,c,d]=m,co=Math.cos(t),si=Math.sin(t);m[0]=a*co+c*si;m[1]=b*co+d*si;m[2]=c*co-a*si;m[3]=d*co-b*si;}
 beginPath(){this.path=[];this.current=null;}
 moveTo(x:number,y:number){this.current={p:[this.xy(x,y)],closed:false};this.path.push(this.current);this.lastPoint=[x,y];}
 lineTo(x:number,y:number){if(!this.current)this.moveTo(x,y);else this.current.p.push(this.xy(x,y));this.lastPoint=[x,y];}
 closePath(){if(this.current)this.current.closed=true;}
 arc(x:number,y:number,r:number,a:number,b:number){this.ellipse(x,y,r,r,0,a,b);}
 ellipse(x:number,y:number,rx:number,ry:number,rot:number,a:number,b:number){const total=Math.min(Math.PI*2,b-a),n=Math.max(8,Math.ceil(Math.abs(total)*6));for(let i=0;i<=n;i++){const t=a+total*i/n,px=x+Math.cos(t)*rx*Math.cos(rot)-Math.sin(t)*ry*Math.sin(rot),py=y+Math.cos(t)*rx*Math.sin(rot)+Math.sin(t)*ry*Math.cos(rot);if(i===0&&!this.current)this.moveTo(px,py);else this.lineTo(px,py);}}
 arcTo(x:number,y:number,x2:number,y2:number,r:number){const [x0,y0]=this.lastPoint,la=Math.hypot(x0-x,y0-y)||1,lb=Math.hypot(x2-x,y2-y)||1,t=Math.min(r,la/2,lb/2),ax=x+(x0-x)/la*t,ay=y+(y0-y)/la*t,bx=x+(x2-x)/lb*t,by=y+(y2-y)/lb*t;this.lineTo(ax,ay);for(let i=1;i<=4;i++){const u=i/4;this.lineTo((1-u)**2*ax+2*u*(1-u)*x+u*u*bx,(1-u)**2*ay+2*u*(1-u)*y+u*u*by);}}
 private paint(stroke:boolean){const g=this.graphics();g.fillColor=color(this.fillStyle,this.globalAlpha);g.strokeColor=color(this.strokeStyle,this.globalAlpha);g.lineWidth=this.lineWidth*Math.hypot(this.matrix[0],this.matrix[1]);for(const p of this.path){if(!p.p.length)continue;g.moveTo(...p.p[0]);for(const v of p.p.slice(1))g.lineTo(...v);if(p.closed)g.close();}if(stroke)g.stroke();else g.fill();}
 fill(){this.paint(false);}stroke(){this.paint(true);}setLineDash(_v:number[]){}
 fillRect(x:number,y:number,w:number,h:number){if(typeof this.fillStyle==='object'&&this.fillStyle.stops){const grad=this.fillStyle as Gradient;const stops=grad.stops;for(let i=0;i<32;i++){const t=(i+.5)/32;let j=1;while(j<stops.length-1&&stops[j][0]<t)j++;const lo=stops[Math.max(0,j-1)],hi=stops[Math.min(j,stops.length-1)],k=Math.max(0,Math.min(1,(t-lo[0])/(hi[0]-lo[0]||1))),a=color(lo[1]),b=color(hi[1]);this.fillStyle=`rgba(${a.r+(b.r-a.r)*k},${a.g+(b.g-a.g)*k},${a.b+(b.b-a.b)*k},${(a.a+(b.a-a.a)*k)/255})`;this.fillRect(x,y+h*i/32,w,h/32);}this.fillStyle=grad;return;}this.beginPath();this.moveTo(x,y);this.lineTo(x+w,y);this.lineTo(x+w,y+h);this.lineTo(x,y+h);this.closePath();this.fill();}
 strokeRect(x:number,y:number,w:number,h:number){this.beginPath();this.moveTo(x,y);this.lineTo(x+w,y);this.lineTo(x+w,y+h);this.lineTo(x,y+h);this.closePath();this.stroke();}
 createLinearGradient(..._a:number[]):Gradient{const stops:[number,string][]=[];return{stops,addColorStop:(at,c)=>{stops.push([at,c]);stops.sort((a,b)=>a[0]-b[0]);}};}
 createRadialGradient(...a:number[]){return this.createLinearGradient(...a);}
 measure(str:string,size:number){return Array.from(String(str)).reduce((n,c)=>n+(/[\u2e80-\uffff]/.test(c)?1:/[il1 .·]/.test(c)?.33:.59)*size,0);}
 measureText(str:string){return{width:this.measure(str,Number(this.font.match(/([\d.]+)px/)?.[1]||14))};}
 strokeText(str:string,x:number,y:number){this.outline={str,x,y,color:this.strokeStyle,width:this.lineWidth};}
 fillText(str:string,x:number,y:number){str=String(str);const size=Number(this.font.match(/([\d.]+)px/)?.[1]||14),e=this.take('label'),n=e.n,l=n.getComponent(Label)!,u=n.getComponent(UITransform)!;const width=this.measure(str,size)+4;u.setAnchorPoint(this.textAlign==='center'?.5:this.textAlign==='right'?1:0,.5);u.setContentSize(width*2,size*3.3);n.setPosition(...this.xy(x,y));const m=this.matrix;n.setScale(Math.hypot(m[0],m[1])/2,Math.hypot(m[2],m[3])/2,1);n.angle=-Math.atan2(m[1],m[0])*180/Math.PI;l.font=/^[+−0-9-]+$/.test(str)?NativePaint.digits:null;l.string=str;l.fontSize=size*2;l.lineHeight=size*3;l.fontFamily='Arial';l.isBold=true;l.horizontalAlign=Label.HorizontalAlign.CENTER;l.verticalAlign=Label.VerticalAlign.CENTER;l.overflow=Label.Overflow.NONE;l.color=color(this.fillStyle);n.getComponent(UIOpacity)!.opacity=Math.round(this.globalAlpha*255);const out=n.getComponent(LabelOutline)!;out.enabled=!!this.outline&&!l.font;if(this.outline){out.color=color(this.outline.color);out.width=this.outline.width;}this.outline=null;}
 drawImage(im:any,sx:number,sy:number,sw:number,sh:number,x:number,y:number,w:number,h:number){const sheet=typeof im==='string'?im:im?.sheet,tex=NativePaint.textures[sheet];if(!tex){this.missing.add(String(sheet));return;}if(im?.frame){const f=MANIFEST.frames[im.frame];sx+=f.r[0];sy+=f.r[1];}const e=this.take('sprite'),n=e.n,u=n.getComponent(UITransform)!,s=n.getComponent(Sprite)!,f=e.frame!;if(![sx,sy,sw,sh].every(Number.isFinite)||sx<0||sy<0||sw<=0||sh<=0||sx+sw>tex.width+.01||sy+sh>tex.height+.01){this.invalidRects.add(sheet+':'+[sx,sy,sw,sh].join(','));e.n.active=false;return;}const oldRect=f.rect;const changed=f.texture!==tex||oldRect.x!==sx||oldRect.y!==sy||oldRect.width!==sw||oldRect.height!==sh;if(changed)s.spriteFrame=null;if(f.texture!==tex)f.texture=tex;const r=f.rect;if(r.x!==sx||r.y!==sy||r.width!==sw||r.height!==sh){f.rect=new Rect(sx,sy,sw,sh);f.originalSize=new Size(sw,sh);f.offset=new Vec2();}f.packable=false;s.spriteFrame=f;s.color=color(im?.tint||'#ffffff');u.setAnchorPoint(0,1);u.setContentSize(Math.abs(w),Math.abs(h));n.setPosition(...this.xy(x,y));const m=this.matrix,det=m[0]*m[3]-m[1]*m[2];n.setScale(Math.hypot(m[0],m[1])*Math.sign(w),Math.hypot(m[2],m[3])*Math.sign(det)*Math.sign(h),1);n.angle=-Math.atan2(m[1],m[0])*180/Math.PI;n.getComponent(UIOpacity)!.opacity=Math.round(Math.min(1,Math.max(0,this.globalAlpha))*255);}
 frame(key:string,x:number,y:number,h:number,o:any={}){const f=MANIFEST.frames[key];if(!f){this.missing.add(String(key));return null;}const [sx,sy,sw,sh]=f.r,sc=h/(o.refH||sh),w=sw*sc,hh=sh*sc,cx=o.grip?o.grip[0]*w:o.center?w/2:f.a[0]*w,cy=o.grip?o.grip[1]*hh:o.center?hh/2:hh*(1-f.a[1]);this.save();this.translate(x,y);if(o.rot)this.rotate(o.rot);if(o.flip)this.scale(-1,1);if(o.sy)this.scale(1,o.sy);if(o.alpha!=null)this.globalAlpha*=o.alpha;this.drawImage({sheet:f.s,tint:o.tint},sx,sy,sw,sh,-cx,-cy,w,hh);this.restore();return{x:x-cx,y:y-cy,w,h:hh};}
 backdrop(L:any,S:any){this.fillStyle='#b6c3c6';this.fillRect(0,0,L.W,L.H);const w=L.W*1.25,h=w*450/768;this.drawImage('battle20260925_distant',0,0,768,450,(L.W-w)/2-S.heroX*8,L.P0+34-h,w,h);}
 ground(L:any,S:any){const y0=Math.floor(L.P0-14),grass=[],road=[];for(let y=y0;y<L.H;y+=3){const z=L.zAt(y+.5),sc=L.c/(z+L.c),wz=z+S.dist,v=((wz*110)%512+512)%512,r=((wz*220)%640+640)%640,rw=640/220*L.ppu*sc*.98,gw=512/220*L.ppu*sc*1.6;road.push({x0:-rw/2,x1:rw/2,y0:L.H/2-y-3.1,y1:L.H/2-y,u0:0,u1:1,v:r/640});const half=L.W/2;for(let x=-half;x<half;){const left=((x/gw)%1+1)%1,w=Math.min(half-x,(1-left)*gw||gw);grass.push({x0:x,x1:x+w+.15,y0:L.H/2-y-3.1,y1:L.H/2-y,u0:left,u1:left+w/gw,v:v/512});x+=w;}}for(const [sheet,quads] of [['battle20260925_grass',grass],['battle20260925_road',road]] as const){for(let i=0;i<quads.length;i+=512){const e=this.take('ground');e.n.setPosition(0,0);e.mesh!.draw(NativePaint.textures[sheet],quads.slice(i,i+512) as any);}}const g=this.createLinearGradient();g.addColorStop(0,'rgba(226,228,214,.9)');g.addColorStop(1,'rgba(226,228,214,0)');this.fillStyle=g;this.fillRect(0,y0,L.W,L.Z1[1]+10-y0);}
}
